import { positiveId } from '@/lib/ids';
import { invalid, record } from '@/features/messages/contracts';
export interface HelpRequest { id:number;student_id:number;request_text:string;status:'open'|'resolved';created_at:string;student_name:string|null;subject:string|null;priority:number;content_id:number|null;content_title:string|null;content_type:string|null;study_plan_id:number|null;study_plan_title:string|null;question_id:number|null;question_text:string|null;client_request_id?:string|null }
export interface RequestContext { content_id:number|null; study_plan_id:number|null; session_id:number|null; question_id:number|null }
export interface RequestInput extends RequestContext { subject:string;description:string;urgency:number;client_request_id:string }
export function parseRequest(value:unknown,mutation=false):HelpRequest {
 if(!record(value) || typeof value.id!=='number' || !positiveId(value.id) || typeof value.student_id!=='number' || !positiveId(value.student_id) || typeof value.request_text!=='string' || !['open','resolved'].includes(String(value.status)) || typeof value.created_at!=='string' || typeof value.priority!=='number' || !Number.isInteger(value.priority) || value.priority<1 || value.priority>5)return invalid(mutation);
 for(const key of ['content_id','study_plan_id','question_id'])if(value[key]!==null && (typeof value[key]!=='number' || !positiveId(value[key])))return invalid(mutation);
 for(const key of ['student_name','subject','content_title','content_type','study_plan_title','question_text'])if(value[key]!==null && typeof value[key]!=='string')return invalid(mutation);
 return value as unknown as HelpRequest;
}
export function parseRequests(value:unknown,studentId?:number):HelpRequest[]{if(!Array.isArray(value))return invalid();const requests=value.map(item=>parseRequest(item));if(new Set(requests.map(item=>item.id)).size!==requests.length || studentId && requests.some(item=>item.student_id!==studentId))return invalid();return requests;}
export function confirmRequest(value:unknown,payload:RequestInput,owner:number):HelpRequest {const result=parseRequest(value,true);if(result.student_id!==owner || result.client_request_id!==payload.client_request_id || result.request_text!==`${payload.subject}: ${payload.description}` || result.priority!==payload.urgency || result.content_id!==payload.content_id || result.study_plan_id!==payload.study_plan_id || result.question_id!==payload.question_id)invalid(true);return result;}
export function confirmResolution(value:unknown):void{if(!record(value) || value.status!=='resolved' || typeof value.resolved_at!=='string')invalid(true);}
export function parseRequestContext(params:URLSearchParams):RequestContext|null {const result:RequestContext={content_id:null,study_plan_id:null,session_id:null,question_id:null};for(const key of Object.keys(result) as (keyof RequestContext)[]){const raw=params.get(key) ?? (key==='study_plan_id'?params.get('plan_id'):null);if(raw!==null){const id=positiveId(raw);if(!id)return null;result[key]=id;}}if(result.session_id && !result.content_id)return null;return result;}
export function helpFilters(params:URLSearchParams):URLSearchParams{const result=new URLSearchParams();for(const key of ['q','status','priority']){const value=params.get(key);if(value)result.set(key,value);}return result;}
export function filterRequests(requests:HelpRequest[],params:URLSearchParams):HelpRequest[]{const search=(params.get('q')||'').trim().toLocaleLowerCase();const status=params.get('status')||'all';const priority=Number(params.get('priority')||0);return requests.filter(item=>(status==='all'||item.status===status)&&(!priority||item.priority===priority)&&(!search||[item.request_text,item.subject,item.student_name,item.content_title,item.study_plan_title].some(value=>value?.toLocaleLowerCase().includes(search))));}
export function requestSubject(request:HelpRequest,fallback:string){return request.subject || fallback;}
