import { ApiError } from '@/lib/api';
import { positiveId } from '@/lib/ids';
import type { User } from '@/lib/types';
export type Purpose = 'handout' | 'teacher' | 'import' | 'revision';
export type ExportFormat = 'html' | 'markdown' | 'json';
export interface Selection { id: number; audience: 'learner' | 'teacher'; format: ExportFormat }
export interface Plan { id: number; title: string; creator_id: number | null }
export interface Preview { audience: 'learner' | 'teacher'; package_version: number; compatible_versions: number[]; counts: Record<string,number>; includes: string[]; excludes: string[]; warnings: string[]; import_effect: string; validation: {valid:true;content_graph:string;source:string}; selected_format?: ExportFormat }
export interface BackupPreview { audience:'private_backup'; format:'slmeducator-private-backup'; key_fingerprint:string; includes:string[]; excludes:string[]; warnings:string[] }
export const exportFormats: Record<ExportFormat,{type:string;extension:string}> = {html:{type:'text/html',extension:'html'},markdown:{type:'text/markdown',extension:'md'},json:{type:'application/json',extension:'json'}};
export const MAX_IMPORT_BYTES = 10 * 1024 * 1024;
function invalid(mutation = false): never { throw new ApiError(200,'invalid',mutation,mutation ? 'uncertain' : 'invalidResponse'); }
function object(value: unknown): Record<string,unknown> { if (!value || typeof value !== 'object' || Array.isArray(value)) return invalid(); return value as Record<string,unknown>; }
function strings(value: unknown): value is string[] { return Array.isArray(value) && value.every(item => typeof item === 'string'); }
export function parsePlans(value: unknown): Plan[] { if (!Array.isArray(value)) return invalid(); return value.map(item => { const v = object(item); if (typeof v.id !== 'number' || !positiveId(v.id) || typeof v.title !== 'string' || !(v.creator_id === null || v.creator_id === undefined || typeof v.creator_id === 'number' && positiveId(v.creator_id))) return invalid(); return {id:v.id,title:v.title,creator_id:typeof v.creator_id === 'number' ? v.creator_id : null}; }); }
export function allowedPurposes(user: User): Purpose[] { return user.role === 'student' ? ['handout'] : ['handout','teacher','import','revision']; }
export function canManagePlan(plan: Plan,user: User) { return user.role === 'admin' || user.role === 'teacher' && plan.creator_id === user.id; }
export function parsePreview(value: unknown, audience: Selection['audience'], format?: ExportFormat): Preview {
 const v = object(value); const validation = object(v.validation); const counts = object(v.counts);
 if (v.audience !== audience || ![1,2].includes(Number(v.package_version)) || typeof v.package_version !== 'number' || !Array.isArray(v.compatible_versions) || v.compatible_versions.some(x => !Number.isSafeInteger(x) || x < 1) || !strings(v.includes) || !strings(v.excludes) || !strings(v.warnings) || typeof v.import_effect !== 'string' || validation.valid !== true || validation.content_graph !== 'checked' || typeof validation.source !== 'string' || Object.values(counts).some(x => typeof x !== 'number' || !Number.isSafeInteger(x) || x < 0) || ['contents','assessments','books','questions'].some(k => !(k in counts))) return invalid();
 if (format && (v.selected_format !== format || !Array.isArray(v.available_formats) || !v.available_formats.includes(format) || audience === 'teacher' && (format !== 'json' || v.available_formats.some(x => x !== 'json')))) return invalid();
 return {audience,package_version:v.package_version,compatible_versions:v.compatible_versions as number[],counts:counts as Record<string,number>,includes:v.includes,excludes:v.excludes,warnings:v.warnings,import_effect:v.import_effect,validation:{valid:true,content_graph:validation.content_graph,source:validation.source},...(format ? {selected_format:format} : {})};
}
export function parseBackup(value: unknown): BackupPreview { const v = object(value); if (v.audience !== 'private_backup' || v.format !== 'slmeducator-private-backup' || typeof v.key_fingerprint !== 'string' || !/^[a-f0-9]{64}$/.test(v.key_fingerprint) || !strings(v.includes) || !strings(v.excludes) || !strings(v.warnings)) return invalid(); return {audience:'private_backup',format:'slmeducator-private-backup',key_fingerprint:v.key_fingerprint,includes:v.includes,excludes:v.excludes,warnings:v.warnings}; }
export function selectionKey(selection: Selection) { return `${selection.id}:${selection.audience}:${selection.format}`; }
export function exportPath(selection: Selection, operation: 'preview'|'export') { return `/api/portability/plans/${selection.id}/${operation}?audience=${selection.audience}&format=${selection.format}`; }
export function parseImportText(text: string): Record<string,unknown> { let value: unknown; try { value = JSON.parse(text); } catch { throw new ApiError(422,'invalid',false,'validation'); } if (!value || typeof value !== 'object' || Array.isArray(value) || new TextEncoder().encode(JSON.stringify({package:value,confirm:true})).length > MAX_IMPORT_BYTES) throw new ApiError(422,'invalid',false,'validation'); return value as Record<string,unknown>; }
export function parseDraftReceipt(value: unknown, type: 'import'|'revision'): number { let v: Record<string,unknown>; try { v = object(value); } catch { return invalid(true); } const id = v[type === 'import' ? 'study_plan_id' : 'id']; if (typeof id !== 'number' || !positiveId(id) || v.status !== 'draft') return invalid(true); return id; }
export function parsed<T>(value: unknown, parse: (value: unknown)=>T): {data?:T;error?:ApiError} { if (value === undefined) return {}; try { return {data:parse(value)}; } catch(error) { return {error:error instanceof ApiError ? error : new ApiError(200,'invalid',false,'invalidResponse')}; } }

/** Translate known API scope descriptions without interpreting or hiding unknown server text. */
export const scopeLabels: Record<string,string> = {
 'course structure and ordered learning content':'scopeStructure', 'assessment questions':'scopeQuestions', 'answer keys and rubrics':'scopeAnswers', 'accounts and credentials':'scopeAccounts', 'student assignments and submissions':'scopeAssignments', 'learning notes, annotations and messages':'scopeNotes', 'provider configuration':'scopeProvider', 'original source binaries, external media and linked files':'scopeFiles', 'answer keys, rubrics and grading metadata':'scopeGrading', 'draft assessments':'scopeDraftAssessments', 'teacher workflow and generation state':'scopeWorkflow',
 'Teacher packages contain answer keys; share only with intended instructors.':'scopeTeacherWarning', 'Learner handouts are not restorable teacher course packages.':'scopeLearnerWarning', 'all database accounts, roles and enrollment':'scopeAllAccounts', 'course content and grading assets':'scopeCourseGrading', 'student work, notes and messages':'scopeStudentWork', 'encrypted provider credential records':'scopeEncryptedKeys', 'encryption key':'scopeKey', 'JWT signing secret':'scopeJWT', 'local configuration files':'scopeConfigFiles', 'uploaded files stored outside the database':'scopeUploads', 'Keep this private archive and the original encryption key separately.':'scopeSeparateKey', 'Restore requires the matching key and always creates a new database file.':'scopeRestoreNew', 'This is a database backup, not a copy of the complete installation.':'scopeDatabaseOnly',
};
