import { act, render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { createMemoryRouter, RouterProvider } from 'react-router';
import { QueryClientProvider } from '@tanstack/react-query';
import { createInstance } from 'i18next';
import { I18nextProvider, initReactI18next } from 'react-i18next';
import { createQueryClient } from '@/lib/query';
import { ApiError } from '@/lib/api';
import { routes } from '@/features/authoring/routes';
import { MaterialPreviewPage } from '@/features/learning/routes';
import { locales as learningLocales } from '@/features/learning/locales';
import { locales } from '@/features/authoring/locales';
import { locales as assessmentLocales } from '@/features/assessments/locales';
import { DraftAdapter } from '@/lib/drafts';
import { authoredSource } from '@/features/authoring/contracts';
import { generationDefaults, isGenerationDraft } from '@/features/authoring/contracts';
const auth=vi.hoisted(()=>({user:{id:7,role:'teacher',username:'synthetic_teacher'},scope:'account:7',credentialEpoch:1,status:'authenticated',api:{get:vi.fn(),post:vi.fn(),put:vi.fn(),delete:vi.fn()},registerResource:()=>()=>undefined,getSnapshot:()=>({scope:auth.scope,credentialEpoch:auth.credentialEpoch,status:auth.status})}));
vi.mock('@/app/AuthProvider',()=>({useAuth:()=>auth}));
vi.mock('@/app/DirtyGuard',()=>({useDirtyGuard:vi.fn()}));
const summary={id:12,creator_id:7,title:'Synthetic course',description:'Demo',is_public:false,created_at:'2026-10-07T12:00:00Z'};
const material={id:2,title:'Motion',content_type:'lesson',difficulty:3,is_personal:false,creator_id:7,can_edit:true,content_data:{sections:[{title:'Introduction',content:'Original lesson'}],summary:'Summary',generation:{provider:'synthetic',source_document_id:'a'.repeat(64)}}};
let data:Record<string,unknown>;
async function mount(path:string,language='en') {const i18n=createInstance();await i18n.use(initReactI18next).init({lng:language,resources:{en:{authoring:locales.en,learning:learningLocales.en,assessments:assessmentLocales.en,translation:{loading:'Loading',cancel:'Cancel',saved:'Saved',dirty:'Unsaved changes',errors:{uncertain:'Unknown result',failed:'Could not complete',invalidResponse:'Invalid response',validation:'Check input',network:'Network unavailable'}}},es:{authoring:locales.es,learning:learningLocales.es,assessments:assessmentLocales.es,translation:{loading:'Cargando',cancel:'Cancelar'}}}});const router=createMemoryRouter([...routes,{path:'cursos/:id/editar',element:<p>Course editor</p>},{path:'materiales/:contentId',Component:MaterialPreviewPage}],{initialEntries:[path]});const client=createQueryClient();const result=render(<I18nextProvider i18n={i18n}><QueryClientProvider client={client}><RouterProvider router={router}/></QueryClientProvider></I18nextProvider>);return{...result,router,client,user:userEvent.setup()};}
function deferred<T>() {let resolve!:(value:T)=>void;const promise=new Promise<T>(done=>{resolve=done;});return{promise,resolve};}
beforeEach(()=>{vi.clearAllMocks();auth.user.role='teacher';auth.scope='account:7';auth.credentialEpoch=1;auth.status='authenticated';data={'/api/content/':[material],'/api/content/2':structuredClone(material),'/api/study-plans/':[summary],'/api/study-plans/12/tree':{...summary,phases:[{name:'Unit'}],contents:[],content_count:0},'/api/study-plans/12/workflow':{status:'draft',version:0,read_only:false},'/api/study-plans/12/source':{source:null},'/api/generate/courses/12/jobs':{jobs:{}}};auth.api.get.mockImplementation(async(path:string)=>data[path]);auth.api.put.mockImplementation(async(path:string,payload:Record<string,unknown>)=>({...material,...payload,id:Number(path.split('/').at(-1))}));auth.api.post.mockImplementation(async(_path:string,payload:Record<string,unknown>)=>({...material,...payload,id:20}));auth.api.delete.mockResolvedValue({message:'Content deleted successfully',id:2});});

describe('previous designer recovery journeys',()=>{
 const original=()=>({currentConfig:{subject:'Recovered science',grade_level:'10',duration:8},generatedOutline:{title:'Old course',description:'Kept outline',units:[{title:'Unit',lessons:[{title:'Saved topic',learning_objectives:[]},{title:'Interrupted topic',learning_objectives:['Original goal']}]}]},createdStudyPlanId:12,generationTasks:[{unit:0,lesson:0,status:'saved'},{unit:0,lesson:1,status:'running'}],sourceMaterialText:'Old source text',sourceCoverage:authoredSource('old.txt','Old source text'),sourceDocumentId:null,sourceSavedVersion:null});
 it('requires explicit restore and source save, keeps the original, and never replays generation',async()=>{
  const drafts=new DraftAdapter(7);drafts.write('course','designer','active',original());const before=localStorage.getItem('slm_draft_v1:7:course:designer:active');
  const {user}=await mount('/generar');expect(screen.getByLabelText('Subject')).toHaveValue('');expect(auth.api.post).not.toHaveBeenCalled();
  await user.click(screen.getByRole('button',{name:'Restore previous designer setup'}));expect(await screen.findByLabelText('Course title')).toHaveValue('Old course');expect(screen.getByLabelText('Subject')).toHaveValue('Recovered science');expect(screen.getAllByRole('checkbox',{name:'Generate this topic'})[0]).not.toBeChecked();expect(screen.getAllByRole('checkbox',{name:'Generate this topic'})[1]).toBeChecked();
  expect(screen.getByRole('button',{name:'Generate selected topics'})).toBeDisabled();expect(screen.getByRole('button',{name:'Generate with AI'})).toBeDisabled();expect(screen.getByLabelText('Source text')).toHaveValue('Old source text');expect(auth.api.post).not.toHaveBeenCalled();expect(auth.api.put).not.toHaveBeenCalled();
  const saved={document_id:'a'.repeat(64),filename:'old.txt',extracted_text:'Old source text',sections:[],original_bytes_hash:null,parser:null,extraction_coverage:'unknown',truncated:false,unreadable_pages:[],total_pages:null,provenance:'authored_or_legacy_text',original_binary_included:false};
  auth.api.put.mockImplementation(async()=>{data['/api/study-plans/12/source']={source:saved};return {source:saved,document_id:saved.document_id,review_required:true};});
  await user.click(screen.getByRole('button',{name:'Save recovered source to course 12'}));expect(auth.api.put).not.toHaveBeenCalled();await user.click(within(await screen.findByRole('dialog')).getByRole('button',{name:'Save recovered source to course 12'}));
  await waitFor(()=>expect(screen.getByRole('button',{name:'Generate selected topics'})).toBeEnabled());expect(auth.api.put).toHaveBeenCalledWith('/api/study-plans/12/source',authoredSource('old.txt','Old source text'));expect(auth.api.post).not.toHaveBeenCalled();expect(localStorage.getItem('slm_draft_v1:7:course:designer:active')).toBe(before);
  await user.click(screen.getByRole('button',{name:'Keep generation setup on this device'}));expect(drafts.read('course','generation','active',isGenerationDraft)?.recoveredSource).toBeNull();
 });
 it('adopts identical verified saved source without rewriting it',async()=>{new DraftAdapter(7).write('course','designer','active',original());data['/api/study-plans/12/source']={source:{document_id:'a'.repeat(64),filename:'saved.txt',extracted_text:'Old source text',sections:[],original_bytes_hash:null,parser:null,extraction_coverage:'unknown',truncated:false,unreadable_pages:[],total_pages:null,provenance:'authored_or_legacy_text',original_binary_included:false}};const {user}=await mount('/generar');await user.click(screen.getByRole('button',{name:'Restore previous designer setup'}));await screen.findByLabelText('Course title');expect(screen.queryByLabelText('Source text')).not.toBeInTheDocument();expect(auth.api.put).not.toHaveBeenCalled();expect(screen.getByRole('button',{name:'Generate selected topics'})).toBeEnabled();});
 it('refuses a source replacement when the course changes after confirmation was prepared',async()=>{new DraftAdapter(7).write('course','designer','active',original());const {user}=await mount('/generar');await user.click(screen.getByRole('button',{name:'Restore previous designer setup'}));await user.click(await screen.findByRole('button',{name:'Save recovered source to course 12'}));await screen.findByRole('dialog');data['/api/study-plans/12/workflow']={status:'published',version:2,read_only:true};await user.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Save recovered source to course 12'}));await waitFor(()=>expect(auth.api.get).toHaveBeenCalledWith('/api/study-plans/12/workflow'));expect(auth.api.put).not.toHaveBeenCalled();expect(screen.getByLabelText('Source text')).toHaveValue('Old source text');expect(screen.getByRole('button',{name:'Generate selected topics'})).toBeDisabled();});
 it('retains recovered source after an unconfirmed source-save receipt',async()=>{new DraftAdapter(7).write('course','designer','active',original());auth.api.put.mockResolvedValue({document_id:'a'.repeat(64)});const {user}=await mount('/generar');await user.click(screen.getByRole('button',{name:'Restore previous designer setup'}));await user.click(await screen.findByRole('button',{name:'Save recovered source to course 12'}));await user.click(within(await screen.findByRole('dialog')).getByRole('button',{name:'Save recovered source to course 12'}));expect(await screen.findByText('Unknown result')).toBeInTheDocument();expect(screen.getByLabelText('Source text')).toHaveValue('Old source text');expect(screen.getByRole('button',{name:'Generate selected topics'})).toBeDisabled();expect(auth.api.put).toHaveBeenCalledTimes(1);});
 it('does not let an old draft overwrite an unresolved modern recovery',async()=>{const drafts=new DraftAdapter(7);drafts.write('course','designer','active',original());drafts.write('course','generation','active',{form:{...generationDefaults,subject:'Newer setup'},outline:null,createdPlanId:null});await mount('/generar');expect(screen.getByRole('button',{name:'Restore previous designer setup'})).toBeDisabled();expect(screen.getByRole('button',{name:'Restore setup'})).toBeEnabled();});
 it('preserves an unsupported draft as an explicitly copyable snapshot',async()=>{new DraftAdapter(7).write('course','designer','active',{currentConfig:{duration:'broken'},unconverted:'Keep this work'});await mount('/generar');expect(screen.getByRole('button',{name:'Restore previous designer setup'})).toBeDisabled();expect((screen.getByLabelText('Original designer draft') as HTMLTextAreaElement).value).toContain('Keep this work');expect(auth.api.post).not.toHaveBeenCalled();});
 it('leaves the original in place when its server course is no longer authorized',async()=>{new DraftAdapter(7).write('course','designer','active',original());data['/api/study-plans/12/tree']={...summary,creator_id:8,phases:[],contents:[],content_count:0};await mount('/generar');expect(await screen.findByText('Invalid response')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Restore previous designer setup'})).toBeDisabled();expect(screen.queryByLabelText('Original designer draft')).not.toBeInTheDocument();expect(screen.getByLabelText('Subject')).toHaveValue('');expect(new DraftAdapter(7).hasDrafts()).toBe(true);expect(auth.api.put).not.toHaveBeenCalled();});
 it('does not apply a recovered draft after the credential epoch changes',async()=>{new DraftAdapter(7).write('course','designer','active',original());const pending=deferred<unknown>();let treeReads=0;auth.api.get.mockImplementation((path:string)=>path==='/api/study-plans/12/tree'&&treeReads++>0?pending.promise:Promise.resolve(data[path]));const {user}=await mount('/generar');await waitFor(()=>expect(screen.getByRole('button',{name:'Restore previous designer setup'})).toBeEnabled());await user.click(screen.getByRole('button',{name:'Restore previous designer setup'}));auth.credentialEpoch++;await act(async()=>pending.resolve(data['/api/study-plans/12/tree']));expect(screen.getByLabelText('Subject')).toHaveValue('');expect(screen.queryByLabelText('Course title')).not.toBeInTheDocument();expect(auth.api.put).not.toHaveBeenCalled();});
});
describe('material authoring journeys',()=>{
 it('filters visible materials without issuing mutations and preserves query in route',async()=>{data['/api/content/']=[material,{...material,id:3,title:'Practice',content_type:'exercise',can_edit:false}];const {user,router}=await mount('/materiales');await screen.findByRole('link',{name:'Motion'});await user.selectOptions(screen.getByLabelText('Material type'),'exercise');expect(screen.queryByRole('link',{name:'Motion'})).not.toBeInTheDocument();expect(screen.getByRole('link',{name:'Practice'})).toBeInTheDocument();expect(router.state.location.search).toBe('?tipo=exercise');expect(auth.api.post).not.toHaveBeenCalled();expect(screen.queryByRole('link',{name:'Edit material'})).not.toBeInTheDocument();});
 it.each(['/materiales/nuevo','/materiales/2/editar','/generar','/fuentes?plan_id=12'])('denies student structured authoring at %s without reading private sources',async path=>{auth.user.role='student';await mount(path);expect(screen.getByText('Material authoring is for teachers and administrators.')).toBeInTheDocument();expect(auth.api.get).not.toHaveBeenCalled();});
 it('validates route IDs before any API call',async()=>{await mount('/materiales/NaN/editar');expect(screen.getByText('This material is unavailable.')).toBeInTheDocument();expect(auth.api.get).not.toHaveBeenCalled();});
 it('honors backend immutability rather than visible ownership alone',async()=>{data['/api/content/2']={...material,can_edit:false};await mount('/materiales/2/editar');expect(await screen.findByText('This material is read-only.')).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Save draft'})).not.toBeInTheDocument();});
 it('saves manual sections while retaining source provenance and uses the actual PUT contract',async()=>{const{user}=await mount('/materiales/2/editar');const field=await screen.findByLabelText('Section 1 content');await user.clear(field);await user.type(field,'Edited lesson');await user.click(screen.getByRole('button',{name:'Save draft'}));await waitFor(()=>expect(auth.api.put).toHaveBeenCalledTimes(1));expect(auth.api.put.mock.calls[0][0]).toBe('/api/content/2');expect(auth.api.put.mock.calls[0][1]).toMatchObject({title:'Motion',difficulty:3,content_data:{sections:[{title:'Introduction',content:'Edited lesson'}],generation:material.content_data.generation,summary:'Summary'}});expect(auth.api.post).not.toHaveBeenCalled();});
 it('creates an independent exercise with explicit structured choices and answer key',async()=>{const{user}=await mount('/materiales/nuevo');await user.type(screen.getByLabelText('Material title'),'Choice exercise');await user.selectOptions(screen.getByLabelText('Material type'),'exercise');await user.selectOptions(screen.getByLabelText('Exercise type'),'multiple_choice');await user.type(screen.getByLabelText('Question'),'Which one?');await user.click(screen.getByRole('button',{name:'Add choice'}));await user.click(screen.getByRole('button',{name:'Add choice'}));await user.type(screen.getByLabelText('Choice 1 text'),'First');await user.type(screen.getByLabelText('Choice 2 text'),'Second');await user.selectOptions(screen.getByLabelText('Correct answer'),'2');await user.click(screen.getByRole('button',{name:'Save draft'}));await waitFor(()=>expect(auth.api.post).toHaveBeenCalled());expect(auth.api.post.mock.calls[0][1]).toMatchObject({content_type:'exercise',is_personal:false,content_data:{options:{'1':'First','2':'Second'},correct_answer:'2'}});});
 it('requires explicit destructive confirmation and reports only a validated delete receipt',async()=>{const{user}=await mount('/materiales/2/editar');await screen.findByLabelText('Material title');await user.click(screen.getByRole('button',{name:'Delete material'}));expect(auth.api.delete).not.toHaveBeenCalled();const dialog=await screen.findByRole('dialog');await user.click(within(dialog).getByRole('button',{name:'Delete material'}));expect(await screen.findByText('Material deleted.')).toBeInTheDocument();expect(auth.api.delete).toHaveBeenCalledWith('/api/content/2');});
 it('single-flights double saves and retains text after unknown network outcome',async()=>{const pending=deferred<never>();auth.api.put.mockImplementation(()=>pending.promise);const{user}=await mount('/materiales/2/editar');await user.type(await screen.findByLabelText('Section 1 content'),' edited');await user.dblClick(screen.getByRole('button',{name:'Save draft'}));expect(auth.api.put).toHaveBeenCalledTimes(1);});
 it('does not retry a malformed save receipt or show success',async()=>{auth.api.put.mockResolvedValue({id:99});const{user}=await mount('/materiales/2/editar');await user.type(await screen.findByLabelText('Section 1 content'),' changed');await user.click(screen.getByRole('button',{name:'Save draft'}));expect(await screen.findByText('Unknown result')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Save draft'})).toBeDisabled();expect(screen.getByLabelText('Section 1 content')).toHaveValue('Original lesson changed');expect(auth.api.put).toHaveBeenCalledTimes(1);});
 it('uses Spanish labels throughout the editor',async()=>{await mount('/materiales/2/editar','es');expect(await screen.findByLabelText('Contenido de la sección 1')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Guardar borrador'})).toBeInTheDocument();});
});
describe('source and generation interruptions',()=>{
 it('uploads FormData, keeps local edits until explicit adoption, and never saves extraction automatically',async()=>{auth.api.post.mockResolvedValue({...authoredSource('sample.txt','[text:1]\nExtracted text'),source_version:'f'.repeat(64),sections:[{reference:'text:1',text:'Extracted text'}]});const{user}=await mount('/fuentes?plan_id=12');await user.type(await screen.findByLabelText('Source text'),'My existing notes');await user.upload(screen.getByLabelText('Extract source file'),new File(['text'],'sample.txt',{type:'text/plain'}));await screen.findByText('Extracted source proposal');expect(auth.api.post.mock.calls[0][1]).toBeInstanceOf(FormData);expect(screen.getByLabelText('Source text')).toHaveValue('My existing notes');expect(auth.api.put).not.toHaveBeenCalled();await user.click(screen.getByRole('button',{name:'Use extracted text'}));await user.click(within(await screen.findByRole('dialog')).getByRole('button',{name:'Use extracted text'}));expect(screen.getByLabelText('Source text')).toHaveValue('[text:1]\nExtracted text');});
 it('rejects wrong upload type and oversized files before a server call',async()=>{await mount('/fuentes?plan_id=12');const input=await screen.findByLabelText('Extract source file');await userEvent.setup({applyAccept:false}).upload(input,new File(['x'],'unsafe.exe'));expect(auth.api.post).not.toHaveBeenCalled();});
 it('never generates on mount, refetch or mode selection',async()=>{const{user}=await mount('/generar?plan_id=12');await screen.findByText('No source is saved for this course. Generation uses general knowledge.');await user.selectOptions(screen.getByLabelText('Generation mode'),'lesson');await user.click(screen.getByRole('button',{name:'Refresh saved jobs'}));expect(auth.api.post).not.toHaveBeenCalled();});
 it('maps individual generation to proposal editor without saving or overwriting later request input',async()=>{const pending=deferred<unknown>();auth.api.post.mockImplementation(()=>pending.promise);const{user}=await mount('/generar');await user.selectOptions(screen.getByLabelText('Generation mode'),'lesson');await user.type(screen.getByLabelText('Subject'),'Science');await user.type(screen.getByLabelText('Grade or learning level'),'10');await user.type(screen.getByLabelText('Topic'),'Motion');await user.click(screen.getByRole('button',{name:'Generate with AI'}));await waitFor(()=>expect(auth.api.post).toHaveBeenCalledTimes(1));await user.clear(screen.getByLabelText('Topic'));await user.type(screen.getByLabelText('Topic'),'Energy');await act(async()=>pending.resolve({title:'Old topic',content:'Generated motion'}));expect(await screen.findByLabelText('Section 1 content')).toHaveValue('Generated motion');expect(screen.getByLabelText('Topic')).toHaveValue('Energy');expect(screen.getByLabelText('Material title')).toHaveValue('Motion');expect(auth.api.put).not.toHaveBeenCalled();expect(auth.api.post.mock.calls[0][0]).toBe('/api/generate/lesson');});
 it('preserves edited proposal when a later AI response arrives',async()=>{auth.api.post.mockResolvedValueOnce({content:'First proposal'}).mockResolvedValueOnce({content:'Second proposal'});const{user}=await mount('/generar');await user.selectOptions(screen.getByLabelText('Generation mode'),'lesson');for(const[label,value]of[['Subject','Science'],['Grade or learning level','10'],['Topic','Motion']])await user.type(screen.getByLabelText(label),value);await user.click(screen.getByRole('button',{name:'Generate with AI'}));const field=await screen.findByLabelText('Section 1 content');await user.clear(field);await user.type(field,'My careful edit');await user.click(screen.getByRole('button',{name:'Generate with AI'}));await waitFor(()=>expect(screen.getAllByLabelText('Section 1 content')).toHaveLength(2));expect(screen.getAllByLabelText('Section 1 content')[0]).toHaveValue('My careful edit');expect(screen.getAllByLabelText('Section 1 content')[1]).toHaveValue('Second proposal');});
 it('rejects a late response after credential replacement and does not display old private proposal',async()=>{const pending=deferred<unknown>();auth.api.post.mockImplementation(()=>pending.promise);const{user}=await mount('/generar');await user.selectOptions(screen.getByLabelText('Generation mode'),'lesson');for(const[label,value]of[['Subject','Science'],['Grade or learning level','10'],['Topic','Motion']])await user.type(screen.getByLabelText(label),value);await user.click(screen.getByRole('button',{name:'Generate with AI'}));await waitFor(()=>expect(auth.api.post).toHaveBeenCalled());auth.credentialEpoch=2;await act(async()=>pending.resolve({content:'Old credential response'}));expect(screen.queryByLabelText('Section 1 content')).not.toBeInTheDocument();});
 it('shows confirmed partial package items and leaves retry explicit',async()=>{auth.api.post.mockResolvedValue({success:false,topic_name:'Motion',lesson:{content:'Body'},exercises:[],assessment:null,saved_content_ids:[2],items:[{key:'lesson',status:'ready',content_id:2},...[0,1,2,3].map(index=>({key:`exercise-${index}`,status:'failed',error_code:'provider_failure'}))],job_key:'a'.repeat(64)});const{user}=await mount('/generar?plan_id=12');await screen.findByText('No source is saved for this course. Generation uses general knowledge.');for(const[label,value]of[['Subject','Science'],['Grade or learning level','10'],['Topic','Motion']])await user.type(screen.getByLabelText(label),value);await user.click(screen.getByRole('button',{name:'Generate with AI'}));expect(await screen.findByText('1 of 5 items confirmed saved')).toBeInTheDocument();expect(screen.getByRole('link',{name:'Review material 2'})).toHaveAttribute('href','/materiales/2/editar');expect(auth.api.post).toHaveBeenCalledTimes(1);await user.click(screen.getByRole('button',{name:'Retry the captured request'}));expect(auth.api.post).toHaveBeenCalledTimes(1);});
 it('treats network uncertainty as unknown and does not replay generation after reads',async()=>{auth.api.post.mockRejectedValue(new ApiError(0,'network',true,'uncertain'));const{user}=await mount('/generar?plan_id=12');await screen.findByText('No source is saved for this course. Generation uses general knowledge.');for(const[label,value]of[['Subject','Science'],['Grade or learning level','10'],['Topic','Motion']])await user.type(screen.getByLabelText(label),value);await user.click(screen.getByRole('button',{name:'Generate with AI'}));expect(await screen.findByText('Unknown result')).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Refresh saved jobs'}));expect(auth.api.post).toHaveBeenCalledTimes(1);});
});

describe('authoring recovery and source truth',()=>{
 it('persists editable outline recovery including selected topics and revalidates ownership before restoring',async()=>{
  const saved={form:{mode:'outline',subject:'Science',topic:'',grade:'10',objectives:'',weeks:4,minutes:30,difficulty:'medium',exerciseType:'multiple_choice',lesson:true,exercises:false,assessment:false,exerciseCount:4,questionCount:5,questionType:'mixed',autoSave:true,planId:'12',phase:0},outline:{title:'Recovered course',description:'',units:[{title:'Unit',lessons:[{title:'Motion',learning_objectives:['Velocity'],selected:true}]}]},createdPlanId:12};new DraftAdapter(7).write('course','generation','active',saved);
  const{user}=await mount('/generar');expect(await screen.findByRole('button',{name:'Restore setup'})).toBeInTheDocument();expect(auth.api.post).not.toHaveBeenCalled();await user.click(screen.getByRole('button',{name:'Restore setup'}));expect(await screen.findByLabelText('Course title')).toHaveValue('Recovered course');expect(auth.api.get).toHaveBeenCalledWith('/api/study-plans/12/tree');expect(auth.api.post).not.toHaveBeenCalled();
 });
 it('does not restore another teachers course recovery',async()=>{data['/api/study-plans/12/tree']={...summary,creator_id:8,phases:[],contents:[],content_count:0};new DraftAdapter(7).write('course','generation','active',{form:{mode:'lesson',subject:'Science',topic:'Motion',grade:'10',objectives:'',weeks:4,minutes:30,difficulty:'medium',exerciseType:'multiple_choice',lesson:true,exercises:true,assessment:false,exerciseCount:4,questionCount:5,questionType:'mixed',autoSave:true,planId:'12',phase:0},outline:null,createdPlanId:null});const{user}=await mount('/generar');await user.click(await screen.findByRole('button',{name:'Restore setup'}));expect(await screen.findByText('Invalid response')).toBeInTheDocument();expect(screen.getByLabelText('Subject')).toHaveValue('');expect(auth.api.post).not.toHaveBeenCalled();});
 it('saves edited source as authored text and requires confirmation before resetting review',async()=>{const source={document_id:'a'.repeat(64),filename:'source.txt',extracted_text:'[text:1]\nOriginal',sections:[{reference:'text:1',text:'Original'}],original_bytes_hash:'f'.repeat(64),parser:'synthetic',extraction_coverage:'complete',truncated:false,unreadable_pages:[],total_pages:null,provenance:'reported_extraction',original_binary_included:false};data['/api/study-plans/12/source']={source};auth.api.put.mockImplementation(async(_path:string,input:Record<string,unknown>)=>({document_id:'b'.repeat(64),review_required:true,source:{...source,document_id:'b'.repeat(64),extracted_text:input.extracted_text,sections:[{reference:'authored:1',text:input.extracted_text}],original_bytes_hash:null,parser:null,extraction_coverage:'unknown',provenance:'authored_or_legacy_text'}}));const{user}=await mount('/fuentes?plan_id=12');const text=await screen.findByLabelText('Source text');await user.clear(text);await user.type(text,'My revised source');await user.click(screen.getByRole('button',{name:'Save source revision'}));expect(auth.api.put).not.toHaveBeenCalled();await user.click(within(await screen.findByRole('dialog')).getByRole('button',{name:'Save source revision'}));expect(await screen.findByText('Source saved. Previous material remains available; review is required again.')).toBeInTheDocument();expect(auth.api.put.mock.calls[0][1]).toMatchObject({extracted_text:'My revised source',source_version:null,sections:[],coverage:'unknown'});expect(auth.api.post).not.toHaveBeenCalled();});
 it('does not let an immutable course source mutate or extract files',async()=>{data['/api/study-plans/12/workflow']={status:'published',version:2,read_only:true};await mount('/fuentes?plan_id=12');expect(await screen.findByText('This material is read-only.')).toBeInTheDocument();expect(screen.getByLabelText('Source text')).toBeDisabled();expect(screen.queryByLabelText('Extract source file')).not.toBeInTheDocument();expect(screen.getByRole('link',{name:'Create course revision'})).toHaveAttribute('href','/cursos/12/editar');expect(auth.api.put).not.toHaveBeenCalled();});
 it('cancels only the explicitly selected durable job and keeps provider uncertainty visible',async()=>{data['/api/generate/courses/12/jobs']={jobs:{['a'.repeat(64)]:{items:{lesson:{status:'running'}}}}};auth.api.post.mockResolvedValue({status:'cancellation_requested',in_flight_call_may_finish:true});const{user}=await mount('/generar?plan_id=12');await user.click(await screen.findByRole('button',{name:'Request cancellation'}));await waitFor(()=>expect(auth.api.post).toHaveBeenCalledWith(`/api/generate/courses/12/jobs/${'a'.repeat(64)}/cancel`));expect(screen.getByText(/Cancellation does not prove the provider stopped/)).toBeInTheDocument();expect(auth.api.post).toHaveBeenCalledTimes(1);});
 it('creates valid course PhaseModel structure from plan preview without sending raw generated topics',async()=>{auth.api.post.mockImplementation(async(path:string,payload:Record<string,unknown>)=>path==='/api/generate/study-plan'?{title:'Planned course',description:'Plan',phases:[{title:'Unit',topics:[{title:'Motion',learning_objectives:['Velocity']}]}]}:{...summary,...payload,id:25});const{user}=await mount('/generar');await user.selectOptions(screen.getByLabelText('Generation mode'),'plan');for(const[label,value]of[['Subject','Science'],['Grade or learning level','10']])await user.type(screen.getByLabelText(label),value);await user.click(screen.getByRole('button',{name:'Generate with AI'}));await user.click(await screen.findByRole('button',{name:'Use this outline'}));await user.click(within(await screen.findByRole('dialog')).getByRole('button',{name:'Use this outline'}));await user.click(screen.getByRole('button',{name:'Save course structure'}));await waitFor(()=>expect(auth.api.post).toHaveBeenCalledTimes(2));expect(auth.api.post.mock.calls[1]).toEqual(['/api/study-plans/',{title:'Planned course',description:'Plan',is_public:false,phases:[{name:'Unit',content_ids:[]}]}]);});
 it('blocks accidental create replay after unconfirmed course structure response',async()=>{auth.api.post.mockImplementation(async(path:string)=>path==='/api/generate/course-outline'?{title:'Planned course',units:[{title:'Unit',lessons:[]}]}:{id:999});const{user}=await mount('/generar');await user.selectOptions(screen.getByLabelText('Generation mode'),'outline');for(const[label,value]of[['Subject','Science'],['Grade or learning level','10']])await user.type(screen.getByLabelText(label),value);await user.click(screen.getByRole('button',{name:'Generate with AI'}));await user.click(await screen.findByRole('button',{name:'Use this outline'}));await user.click(within(await screen.findByRole('dialog')).getByRole('button',{name:'Use this outline'}));await user.click(screen.getByRole('button',{name:'Save course structure'}));expect(await screen.findByText('Unknown result')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Save course structure'})).toBeDisabled();});
 it('exposes a full standalone assessment proposal with its per-question rubric and performs no automatic save',async()=>{auth.api.post.mockResolvedValue({success:true,topic_name:'Motion',lesson:null,exercises:[],assessment:{title:'Assessment draft',questions:[{question:'Explain velocity',type:'short_answer',points:10,correct_answer:'Rate of displacement',explanation:'Explanation',hints:['Direction'],rubric:{name:'Velocity rubric',criteria:[{name:'Reasoning',max_points:10}]}}]},saved_content_ids:[],items:[{key:'assessment',status:'ready'}],job_key:'a'.repeat(64)});const{user}=await mount('/generar');for(const[label,value]of[['Subject','Science'],['Grade or learning level','10'],['Topic','Motion']])await user.type(screen.getByLabelText(label),value);await user.click(screen.getByRole('checkbox',{name:'Lesson'}));await user.click(screen.getByRole('checkbox',{name:'Practice exercise'}));await user.click(screen.getByRole('checkbox',{name:'Assessment'}));await user.click(screen.getByRole('checkbox',{name:'Save each confirmed item to the selected course'}));await user.click(screen.getByRole('button',{name:'Generate with AI'}));expect(await screen.findByText('Velocity rubric')).toBeInTheDocument();expect(screen.getByRole('heading',{name:'Assessment proposal'})).toBeInTheDocument();expect(auth.api.post).toHaveBeenCalledTimes(1);});
});

describe('source revision and route reconciliation regressions',()=>{
 const config={mode:'outline',subject:'Science',topic:'',grade:'10',objectives:'',weeks:4,minutes:30,difficulty:'medium',exerciseType:'multiple_choice',lesson:true,exercises:false,assessment:false,exerciseCount:4,questionCount:5,questionType:'mixed',autoSave:true,planId:'12',phase:0};
 const outline={title:'Recovered course',description:'',units:[{title:'Unit',lessons:[{title:'Motion',learning_objectives:['Velocity'],selected:true},{title:'Energy',learning_objectives:['Work'],selected:true}]}]};
 const source=(version:string,name:string)=>({document_id:version.repeat(64),filename:name,extracted_text:`Text ${version}`,sections:[{reference:'authored:1',text:`Text ${version}`}],original_bytes_hash:null,parser:null,extraction_coverage:'unknown',truncated:false,unreadable_pages:[],total_pages:null,provenance:'authored_or_legacy_text',original_binary_included:false,metadata_revision:version.repeat(64)});
 it('keeps plan_id URL, course selector and requests aligned across same-route navigation and Back',async()=>{data['/api/study-plans/']=[summary,{...summary,id:13,title:'Second course'}];for(const suffix of ['tree','source','workflow'])data[`/api/study-plans/13/${suffix}`]=suffix==='tree'?{...summary,id:13,phases:[],contents:[],content_count:0}:data[`/api/study-plans/12/${suffix}`];data['/api/generate/courses/13/jobs']={jobs:{}};const{router}=await mount('/generar?plan_id=12');await waitFor(()=>expect(screen.getByLabelText('Course draft')).toHaveValue('12'));await act(async()=>router.navigate('/generar?plan_id=13'));await waitFor(()=>expect(screen.getByLabelText('Course draft')).toHaveValue('13'));expect(auth.api.get.mock.calls.some(call=>call[0]==='/api/study-plans/13/source')).toBe(true);await act(async()=>router.navigate(-1));await waitFor(()=>expect(screen.getByLabelText('Course draft')).toHaveValue('12'));expect(auth.api.post).not.toHaveBeenCalled();});
 it('reuses a matching restored source without writing or requiring a copy',async()=>{const original=source('a','Original');data['/api/study-plans/12/source']={source:original};new DraftAdapter(7).write('course','generation','active',{form:config,outline,createdPlanId:12,outlineSource:original,outlineSourcePlanId:12});const{user}=await mount('/generar');await user.click(await screen.findByRole('button',{name:'Restore setup'}));expect(await screen.findByRole('button',{name:'Generate selected topics'})).toBeEnabled();expect(screen.queryByRole('button',{name:'Save captured source to this new course'})).not.toBeInTheDocument();expect(auth.api.put).not.toHaveBeenCalled();});
 it('requires named replacement confirmation for a newer destination source and detects another change before writing',async()=>{const original=source('a','Original snapshot');data['/api/study-plans/12/source']={source:source('b','New revision')};new DraftAdapter(7).write('course','generation','active',{form:config,outline,createdPlanId:12,outlineSource:original,outlineSourcePlanId:12});const{user}=await mount('/generar');await user.click(await screen.findByRole('button',{name:'Restore setup'}));expect(await screen.findByRole('button',{name:'Generate selected topics'})).toBeDisabled();await user.click(screen.getByRole('button',{name:'Save captured source to this new course'}));const dialog=await screen.findByRole('dialog');expect(within(dialog).getByText(/Replace New revision with the captured Original snapshot in course 12/)).toBeInTheDocument();expect(auth.api.put).not.toHaveBeenCalled();data['/api/study-plans/12/source']={source:source('c','Third revision')};await user.click(within(dialog).getByRole('button',{name:'Save captured source to this new course'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Save captured source to this new course'})).toBeEnabled());expect(auth.api.put).not.toHaveBeenCalled();expect(screen.getByRole('button',{name:'Generate selected topics'})).toBeDisabled();});
 it('announces partial batch completion and keeps confirmed item links across a later failed topic',async()=>{new DraftAdapter(7).write('course','generation','active',{form:config,outline,createdPlanId:12});auth.api.post.mockImplementation(async(_path:string,input:Record<string,unknown>)=>({success:input.topic_name==='Motion',topic_name:input.topic_name,lesson:input.topic_name==='Motion'?{content:'Body'}:null,exercises:[],assessment:null,saved_content_ids:input.topic_name==='Motion'?[2]:[],items:input.topic_name==='Motion'?[{key:'lesson',status:'ready',content_id:2}]:[{key:'lesson',status:'failed',error_code:'provider_failure'}],job_key:(input.topic_name==='Motion'?'a':'b').repeat(64)}));const{user}=await mount('/generar');await user.click(await screen.findByRole('button',{name:'Restore setup'}));await user.click(await screen.findByRole('button',{name:'Generate selected topics'}));await waitFor(()=>expect(auth.api.post).toHaveBeenCalledTimes(2));await waitFor(()=>expect(screen.getAllByRole('status').some(item=>item.textContent==='Some items need attention')).toBe(true));expect(screen.getByRole('link',{name:'Review material 2'})).toBeInTheDocument();expect(screen.getAllByRole('status').some(item=>item.textContent==='Generation finished')).toBe(false);});
 it('shows generated exercise with a missing answer for explicit author repair instead of inventing an answer',async()=>{auth.api.post.mockResolvedValue({question:'What is velocity?',type:'short_answer'});const{user}=await mount('/generar');await user.selectOptions(screen.getByLabelText('Generation mode'),'exercise');for(const[label,value]of[['Subject','Science'],['Grade or learning level','10'],['Topic','Motion']])await user.type(screen.getByLabelText(label),value);await user.click(screen.getByRole('button',{name:'Generate with AI'}));expect(await screen.findByLabelText('Question')).toHaveValue('What is velocity?');expect(screen.getByLabelText('Correct answer')).toHaveValue('');expect(auth.api.post).toHaveBeenCalledTimes(1);});
});

describe('captured retry source binding',()=>{
 it('does not silently rebind a source-free failed request to a newly saved source when retrying',async()=>{auth.api.post.mockRejectedValue(new ApiError(0,'network',true,'uncertain'));const{user}=await mount('/generar?plan_id=12');await screen.findByText('No source is saved for this course. Generation uses general knowledge.');for(const[label,value]of[['Subject','Science'],['Grade or learning level','10'],['Topic','Motion']])await user.type(screen.getByLabelText(label),value);await user.click(screen.getByRole('button',{name:'Generate with AI'}));await screen.findByText('Unknown result');data['/api/study-plans/12/source']={source:{document_id:'a'.repeat(64),filename:'New source',extracted_text:'New text',sections:[{reference:'authored:1',text:'New text'}],original_bytes_hash:null,parser:null,extraction_coverage:'unknown',truncated:false,unreadable_pages:[],total_pages:null,provenance:'authored_or_legacy_text',original_binary_included:false}};await user.click(screen.getByRole('button',{name:'Retry the captured request'}));await user.click(within(await screen.findByRole('dialog')).getByRole('button',{name:'Retry the captured request'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Generate with AI'})).toBeEnabled());expect(auth.api.post).toHaveBeenCalledTimes(1);});
});

describe('captured source transfer',()=>{
 it('saves an authorized captured source to an empty new course only after confirmation, then enables topic generation',async()=>{const original={document_id:'a'.repeat(64),filename:'Source snapshot',extracted_text:'Original source',sections:[{reference:'authored:1',text:'Original source'}],original_bytes_hash:null,parser:null,extraction_coverage:'unknown',truncated:false,unreadable_pages:[],total_pages:null,provenance:'authored_or_legacy_text',original_binary_included:false};new DraftAdapter(7).write('course','generation','active',{form:{mode:'outline',subject:'Science',topic:'',grade:'10',objectives:'',weeks:4,minutes:30,difficulty:'medium',exerciseType:'multiple_choice',lesson:true,exercises:false,assessment:false,exerciseCount:4,questionCount:5,questionType:'mixed',autoSave:true,planId:'12',phase:0},outline:{title:'Course',description:'',units:[{title:'Unit',lessons:[{title:'Motion',learning_objectives:[],selected:true}]}]},createdPlanId:12,outlineSource:original,outlineSourcePlanId:12});auth.api.put.mockImplementation(async()=>{data['/api/study-plans/12/source']={source:original};return {source:original,document_id:original.document_id,review_required:true};});const{user}=await mount('/generar');await user.click(await screen.findByRole('button',{name:'Restore setup'}));await user.click(await screen.findByRole('button',{name:'Save captured source to this new course'}));expect(auth.api.put).not.toHaveBeenCalled();await user.click(within(await screen.findByRole('dialog')).getByRole('button',{name:'Save captured source to this new course'}));await waitFor(()=>expect(screen.getByRole('button',{name:'Generate selected topics'})).toBeEnabled());expect(auth.api.put).toHaveBeenCalledWith('/api/study-plans/12/source',expect.objectContaining({filename:'Source snapshot',extracted_text:'Original source',sections:[],source_version:null}));expect(auth.api.post).not.toHaveBeenCalled();});
});


describe('material current-content cache freshness',()=>{
 it('refreshes saved preview and editor without changing a captured learning snapshot',async()=>{
  data['/api/learning/history/2?limit=100']=[];
  auth.api.put.mockImplementation(async(path:string,payload:Record<string,unknown>)=>{data[path]={...material,...payload};return data[path];});
  const h=await mount('/materiales/2');await screen.findByText('Original lesson');
  const snapshot={id:77,content_snapshot:structuredClone(material)};
  h.client.setQueryData([auth.scope,'learning','snapshot',77],snapshot);
  await act(async()=>h.router.navigate('/materiales/2/editar'));
  await h.user.clear(await screen.findByLabelText('Section 1 content'));await h.user.type(screen.getByLabelText('Section 1 content'),'Updated current lesson');
  await h.user.click(screen.getByRole('button',{name:'Save draft'}));await waitFor(()=>expect(screen.getByText('Saved')).toBeInTheDocument());
  await h.user.click(screen.getByRole('link',{name:'Read material'}));await screen.findByText('Updated current lesson');
  expect(screen.queryByText('Original lesson')).not.toBeInTheDocument();expect(h.client.getQueryData([auth.scope,'learning','snapshot',77])).toEqual(snapshot);expect(h.client.getQueryState([auth.scope,'learning','snapshot',77])?.isInvalidated).toBe(false);
  await act(async()=>h.router.navigate('/materiales/2/editar'));expect(await screen.findByLabelText('Section 1 content')).toHaveValue('Updated current lesson');expect(auth.api.put).toHaveBeenCalledTimes(1);
 });
 it('invalidates only the deleted material preview and never replays deletion',async()=>{
  data['/api/learning/history/2?limit=100']=[];let deleted=false;const normal=auth.api.get.getMockImplementation()!;
  auth.api.get.mockImplementation((path:string)=>path==='/api/content/2'&&deleted?Promise.reject(new ApiError(404)):normal(path));
  auth.api.delete.mockImplementation(async()=>{deleted=true;return{id:2,message:'Content deleted successfully'};});
  const h=await mount('/materiales/2');await screen.findByText('Original lesson');
  await act(async()=>h.router.navigate('/materiales/2/editar'));await screen.findByLabelText('Material title');
  await h.user.click(screen.getByRole('button',{name:'Delete material'}));await h.user.click(within(await screen.findByRole('dialog')).getByRole('button',{name:'Delete material'}));await screen.findByText('Material deleted.');
  await act(async()=>h.router.navigate('/materiales/2'));await screen.findByRole('alert');expect(screen.queryByText('Original lesson')).not.toBeInTheDocument();expect(auth.api.delete).toHaveBeenCalledTimes(1);
 });
});

it('updates a confirmed material detail after same-account departure without reopening the old form value',async()=>{
 const pending=deferred<unknown>();const saved={...material,content_data:{...material.content_data,sections:[{title:'Introduction',content:'Confirmed after departure'}]}};
 auth.api.put.mockImplementation(()=>pending.promise);const h=await mount('/materiales/2/editar');
 await h.user.clear(await screen.findByLabelText('Section 1 content'));await h.user.type(screen.getByLabelText('Section 1 content'),'Confirmed after departure');await h.user.click(screen.getByRole('button',{name:'Save draft'}));
 await waitFor(()=>expect(auth.api.put).toHaveBeenCalledTimes(1));await act(async()=>h.router.navigate('/materiales'));
 data['/api/content/2']=saved;await act(async()=>pending.resolve(saved));
 expect(h.client.getQueryData([auth.scope,'authoring','material',2])).toMatchObject({content_data:{sections:[{content:'Confirmed after departure'}]}});
 await act(async()=>h.router.navigate('/materiales/2/editar'));expect(await screen.findByLabelText('Section 1 content')).toHaveValue('Confirmed after departure');expect(auth.api.put).toHaveBeenCalledTimes(1);
});
