import { describe, expect, it } from 'vitest';
import { authoredSource, confirmedMaterial, generationDefaults, generationRequest, isGenerationDraft, isJobs, isPackage, isSourceDocument, isSourceInput, isSourceReceipt, materialForm, materialPayload, outlineFrom, outlinePayload, sourceInput } from '@/features/authoring/contracts';
import { locales } from '@/features/authoring/locales';
const source={...authoredSource('Synthetic notes','Only readable text'),document_id:'a'.repeat(64),original_bytes_hash:null,extraction_coverage:'unknown' as const,provenance:'authored_or_legacy_text',original_binary_included:false as const,sections:[{reference:'authored:1',text:'Only readable text'}]};
const config={...generationDefaults,subject:'Synthetic science',topic:'Motion',grade:'10',planId:'12'};
describe('material payload parity',()=>{
 it('preserves every lesson field, section clarification and generation provenance without duplicating canonical text',()=>{
  const data={content:'Explanation',sections:[{title:'Reading',content:'Explanation',source_clarification:true}],objectives:['Know this'],vocabulary:[{term:'v',definition:'velocity'}],key_concepts:['speed'],discussion_questions:['Why?'],summary:'Short summary',worked_example:'2 + 2',independent_attempt:'Try this',feedback:'Review',delayed_review:'Tomorrow',prerequisite_check:'Before',generation:{source_document_id:'source',review_status:'draft'},custom_author_field:'kept'};
  const form=materialForm('lesson',data,'Motion');expect(form.sections).toHaveLength(1);form.sections[0].content='My correction';
  const result=materialPayload(form,data);expect(result.content_data).toMatchObject({sections:[{title:'Reading',content:'My correction',source_clarification:true}],generation:data.generation,custom_author_field:'kept',vocabulary:data.vocabulary,worked_example:'2 + 2'});expect(result.content_data).not.toHaveProperty('content');
 });
 it('keeps legacy body when it differs from structured sections',()=>{const form=materialForm('lesson',{body:'Overview',sections:[{title:'Detail',content:'Detail body'}]},'Lesson');expect(form.sections.map(item=>item.content)).toEqual(['Overview','Detail body']);});
 it('retains mapped option keys and chooses canonical correct key',()=>{const data={question_text:'Q?',question_type:'multiple_choice',options:{choices:{alpha:'A',beta:'B'}},answer:'B',hint:'Think',generation:{provider:'synthetic'}};const form=materialForm('exercise',data,'Practice');expect(form.correctAnswer).toBe('beta');form.options[1].value='Corrected B';const payload=materialPayload(form,data);expect(payload.content_data).toMatchObject({options:{alpha:'A',beta:'Corrected B'},correct_answer:'beta',hints:['Think'],generation:{provider:'synthetic'}});expect(payload.content_data).not.toHaveProperty('answer');expect(payload.content_data).not.toHaveProperty('question_type');});
 it.each(['duplicate','missing','empty'] as const)('rejects %s choices before mutation',mode=>{const form=materialForm('exercise',{question:'Q',type:'multiple_choice',options:['A','B'],correct_answer:'A'},'Title');if(mode==='duplicate')form.options[1].key='A';if(mode==='missing')form.correctAnswer='C';if(mode==='empty')form.options[1].value=' ';expect(()=>materialPayload(form)).toThrow();});
 it('prioritizes an exact option key over another option label and does not guess duplicate-label answers',()=>{expect(materialForm('exercise',{question:'Q',type:'multiple_choice',options:{alpha:'beta',beta:'Correct'},correct_answer:'beta'},'Practice').correctAnswer).toBe('beta');const form=materialForm('exercise',{question:'Q',type:'multiple_choice',options:{alpha:'Same',beta:'Same'},correct_answer:'Same'},'Practice');expect(form.correctAnswer).toBe('Same');expect(()=>materialPayload(form)).toThrow();});
 it('preserves false and zero exercise answers without truthiness fallbacks',()=>{expect(materialForm('exercise',{question:'Q',correct_answer:false},'Title').correctAnswer).toBe('false');expect(materialForm('exercise',{question:'Q',correct_answer:0},'Title').correctAnswer).toBe('0');});
 it('checks response resource, author, title, difficulty and kind before claiming save',()=>{const payload=materialPayload(materialForm('lesson',{content:'Body'},'Title',3));const receipt={id:20,title:'Title',content_type:'lesson',difficulty:3,is_personal:false,creator_id:7};expect(confirmedMaterial(receipt,payload,7)).toBe(true);for(const change of [{title:'Other'},{creator_id:8},{difficulty:1},{content_type:'exercise'},{id:0}])expect(confirmedMaterial({...receipt,...change},payload,7)).toBe(false);});
});
describe('actual source and generation API mapping',()=>{
 it('round-trips authored source without inventing original bytes or generated section labels',()=>{expect(isSourceDocument(source)).toBe(true);expect(isSourceInput(sourceInput(source))).toBe(true);expect(sourceInput(source).sections).toEqual([]);expect(sourceInput(source).source_version).toBeNull();expect(isSourceReceipt({source,document_id:source.document_id,review_required:true},source.extracted_text)).toBe(true);expect(isSourceReceipt({source,document_id:'b'.repeat(64),review_required:true},source.extracted_text)).toBe(false);});
 it('rejects altered extraction manifests, duplicate section refs and oversize text',()=>{const extracted={...authoredSource('demo.txt','[text:1]\nHello'),sections:[{reference:'text:1',text:'Hello'}],source_version:'f'.repeat(64)};expect(isSourceInput(extracted)).toBe(true);expect(isSourceInput({...extracted,extracted_text:'Changed'})).toBe(false);expect(isSourceInput({...extracted,sections:[...extracted.sections,...extracted.sections]})).toBe(false);expect(isSourceInput(authoredSource('demo','a'.repeat(100001)))).toBe(false);});
 it('uses study plan objectives and never attaches unsupported source text',()=>{expect(generationRequest({...config,mode:'plan'},source)).toEqual({path:'/api/generate/study-plan',body:{subject:config.subject,grade_level:'10',objectives:[],duration_weeks:4}});});
 it.each(['lesson','exercise','outline'] as const)('maps %s source-aware protocol',mode=>{const result=generationRequest({...config,mode},source);expect(result.path).toBe(`/api/generate/${mode==='outline'?'course-outline':mode}`);expect(result.body).toMatchObject({source_material:source.extracted_text,grade_level:'10'});});
 it('maps phase, durable item flags, source revision and correct assessment enums without defaults losing zero exercises',()=>{expect(generationRequest({...config,exerciseCount:0,questionType:'long_answer',phase:2},source).body).toMatchObject({source_document_id:source.document_id,source_material:source.extracted_text,study_plan_id:12,phase_index:2,num_exercises:0,assessment_question_types:['long_answer'],auto_save:true});});
 it('requires a course for durable package generation and at least one requested item',()=>{expect(()=>generationRequest({...config,planId:''},null)).toThrow();expect(()=>generationRequest({...config,lesson:false,exercises:false,assessment:false},null)).toThrow();});
 it('recognizes partial receipts while rejecting phantom saved counts and malformed successes',()=>{const receipt={success:false,topic_name:'Motion',lesson:{content:'Body'},exercises:[],assessment:null,saved_content_ids:[2],items:[{key:'lesson',status:'ready',content_id:2},{key:'exercise-0',status:'failed',error_code:'provider_failure'}],job_key:'f'.repeat(64)};expect(isPackage(receipt,true)).toBe(true);expect(isPackage({...receipt,success:true},true)).toBe(false);expect(isPackage({...receipt,saved_content_ids:[2,3]},true)).toBe(false);expect(isPackage({...receipt,items:[{key:'lesson',status:'ready'}],saved_content_ids:[],success:true},true)).toBe(false);});
 it('validates durable jobs including cancelled, partial and obsolete-source state',()=>{expect(isJobs({jobs:{['a'.repeat(64)]:{obsolete_source:true,cancel_requested:true,items:{lesson:{status:'ready',content_id:2},'exercise-0':{status:'cancelled',error_code:'cancelled'}}}}})).toBe(true);expect(isJobs({jobs:{'not-a-hash':{items:{}}}})).toBe(false);expect(isJobs({jobs:{['a'.repeat(64)]:{items:{lesson:{status:'invented'}}}}})).toBe(false);});
 it('maps generated plan titles/topics to valid course phases rather than sending unsupported raw AI schemas',()=>{const outline=outlineFrom({title:'Plan',description:'Desc',phases:[{title:'Unit',weeks:2,topics:[{title:'Motion',learning_objectives:['Speed']}]}]},'plan')!;expect(outline.units[0].lessons[0].title).toBe('Motion');expect(outlinePayload(outline)).toEqual({title:'Plan',description:'Desc',is_public:false,phases:[{name:'Unit',content_ids:[]}]});expect(outlineFrom({title:'Invalid',units:[{title:'Unit',lessons:[{}]}]},'outline')).toBeNull();});
 it('validates local recovery setup without accepting foreign schema or invalid course IDs',()=>{expect(isGenerationDraft({form:config,outline:null,createdPlanId:12})).toBe(true);expect(isGenerationDraft({form:{...config,autoSave:'true'},outline:null,createdPlanId:12})).toBe(false);expect(isGenerationDraft({form:config,outline:null,createdPlanId:-2})).toBe(false);});
 it('provides matching ES/EN keys and interpolation parameters',()=>{function leaves(value:object,prefix=''):Record<string,string>{return Object.assign({},...Object.entries(value).map(([key,item])=>typeof item==='object'?leaves(item,`${prefix}${key}.`):{[`${prefix}${key}`]:item}));}const en=leaves(locales.en),es=leaves(locales.es);expect(Object.keys(en).sort()).toEqual(Object.keys(es).sort());for(const key of Object.keys(en))expect(es[key].match(/{{\w+}}/g)||[]).toEqual(en[key].match(/{{\w+}}/g)||[]);});
});
