import { describe, expect, it } from 'vitest';
import { ApiError } from '@/lib/api';
import { canAttachMaterial, canReuse, courseForm, coursePayload, isAssignment, isCourseForm, isCourseList, isCourseTree, isMaterialList, isProgress, isStudents, isWorkflow, materialHref, moveItem, type CourseTree } from '@/features/courses/contracts';
import { locales } from '@/features/courses/locales';
import type { User } from '@/lib/types';
const base = {id: 12, creator_id: 7, title: 'Synthetic course', description: null, is_public: false, created_at: '2026-10-07T10:00:00Z'};
const tree: CourseTree = {...base, phases: [{name: 'First', content_ids: [999]}], contents: [{id: 3, title: 'Third phase lesson', content_type: 'lesson', difficulty: 1, phase_index: 2, order_index: 4, created_at: base.created_at}, {id: 2, title: 'First lesson', content_type: 'lesson', difficulty: 1, phase_index: 0, order_index: 0, created_at: base.created_at}], content_count: 2};
const teacher: User = {id: 7, username: 'synthetic_teacher', role: 'teacher', first_name: 'Synthetic', last_name: 'Teacher', email: 'teacher@example.test'};

describe('course API contracts', () => {
  it('accepts the real summary/tree shapes without inventing creator or workflow fields', () => {expect(isCourseList([base])).toBe(true); expect(isCourseTree(tree)).toBe(true);});
  it('rejects malformed course responses and duplicate tree references', () => {expect(isCourseList([{...base, id: '12'}])).toBe(false); expect(isCourseTree({...tree, contents: [...tree.contents, tree.contents[0]], content_count: 3})).toBe(false); expect(isCourseTree({...tree, content_count: 9})).toBe(false);});
  it('uses canonical associations and preserves missing intermediate phases', () => {expect(courseForm(tree).phases).toEqual([{name: 'First', content_ids: [2]}, {name: '', content_ids: []}, {name: '', content_ids: [3]}]);});
  it('preserves keyboard order without mutating the source', () => {const ids = [3,2,5]; expect(moveItem(ids, 1, -1)).toEqual([2,3,5]); expect(ids).toEqual([3,2,5]); expect(moveItem(ids, 0, -1)).toEqual(ids);});
  it('validates draft uniqueness across phases and bounded graph positions', () => {expect(isCourseForm({title: 'x', description: '', phases: [{name: 'a', content_ids: [1]}, {name: 'b', content_ids: [1]}]})).toBe(false); expect(isCourseForm({title: 'x', description: '', phases: Array.from({length: 102}, () => ({name: '', content_ids: []}))})).toBe(false);});
  it('always saves a private draft rather than publishing through save', () => {expect(coursePayload({title: ' Course ', description: '', phases: [{name: ' Unit ', content_ids: [3,2]}]})).toEqual({title: 'Course', description: '', is_public: false, phases: [{name: 'Unit', content_ids: [3,2]}]});});
  it('rejects blank titles or unit names before transport', () => {expect(() => coursePayload({title: ' ', description: '', phases: []})).toThrow(ApiError); expect(() => coursePayload({title: 'x', description: '', phases: [{name: ' ', content_ids: []}]})).toThrow(ApiError);});
  it('does not treat shared personal Q&A or can_edit as reuse permission', () => {const item = {id: 4, title: 'Personal Q&A', content_type: 'qa', difficulty: 1, creator_id: 8, is_personal: true, can_edit: false}; expect(canReuse(item, teacher)).toBe(false); expect(canReuse({...item, is_personal: false}, teacher)).toBe(false); expect(canReuse({...item, is_personal: false, creator_id: 7}, teacher)).toBe(true); expect(canReuse({...item, is_personal: false}, {...teacher, role: 'admin'})).toBe(true);});
  it('allows original public reuse without confusing admin editing with learner provenance', () => {const item = {id: 4, title: 'Cross-author lesson', content_type: 'lesson', difficulty: 1, creator_id: 7, is_personal: false}; expect(canAttachMaterial(item, {...teacher, role: 'admin'}, 9)).toBe(false); expect(canAttachMaterial({...item, public_reuse: true}, {...teacher, role: 'admin'}, 9)).toBe(true); expect(canAttachMaterial({...item, creator_id: 9, public_reuse: true}, teacher, 7)).toBe(true); expect(canAttachMaterial(item, teacher, 7)).toBe(true);});
  it('accepts the actual content and student list shapes', () => {expect(isMaterialList([{id: 4, title: 'Saved lesson', content_type: 'lesson', difficulty: 1, is_personal: false, creator_id: 7}])).toBe(true); expect(isStudents([{id: 6, username: 'learner', first_name: '', last_name: '', teacher_id: 7}])).toBe(true);});
  it('requires explicit assigned immutability in workflow reads', () => {expect(isWorkflow({status: 'published', version: 1, read_only: true})).toBe(true); expect(isWorkflow({status: 'published', version: 1})).toBe(false);});
  it('checks assignment receipt matches every exact requested identity once', () => {expect(isAssignment({study_plan_id: 12, assigned_student_ids: [9], already_assigned_student_ids: [8]}, 12, [8,9])).toBe(true); expect(isAssignment({study_plan_id: 12, assigned_student_ids: [9], already_assigned_student_ids: []}, 12, [8,9])).toBe(false); expect(isAssignment({study_plan_id: 12, assigned_student_ids: [9], already_assigned_student_ids: [9]}, 12, [9])).toBe(false);});
  it('keeps plan context in canonical learner material links', () => {expect(materialHref(3,12)).toBe('/materiales/3?plan_id=12');});
  it('preserves valid zero progress and rejects another course', () => {expect(isProgress({study_plan_id: 12, completed_content_ids: [], last_content_id: null, completion_percentage: 0},12)).toBe(true); expect(isProgress({study_plan_id: 13, completed_content_ids: [], last_content_id: null, completion_percentage: 0},12)).toBe(false);});
  it('keeps English and Spanish labels and placeholders aligned', () => {expect(Object.keys(locales.en).sort()).toEqual(Object.keys(locales.es).sort()); for (const key of Object.keys(locales.en) as (keyof typeof locales.en)[]) expect(locales.en[key].match(/{{\w+}}/g) ?? [], key).toEqual(locales.es[key].match(/{{\w+}}/g) ?? []);});
});
