import { describe,it,expect,vi } from 'vitest';
import { requestLegacyWorkerUpdate } from '@/app/retire-legacy-worker';
const origin='http://127.0.0.1:8765';
function registration(scope=`${origin}/`,scriptURL=`${origin}/sw.js`){return {scope,active:{scriptURL},waiting:null,installing:null,update:vi.fn().mockResolvedValue(undefined),unregister:vi.fn()} as unknown as ServiceWorkerRegistration;}
describe('existing worker update request only',()=>{
 it('does not register a worker on a fresh origin',async()=>{const getRegistrations=vi.fn().mockResolvedValue([]);expect(await requestLegacyWorkerUpdate({getRegistrations},origin)).toBe('none');expect(getRegistrations).toHaveBeenCalledOnce();});
 it('requests update only on the exact known origin/scope/script',async()=>{const owned=registration(),foreignScope=registration(`${origin}/other/`),foreignScript=registration(`${origin}/`,`${origin}/other.js`),otherPort=registration('http://127.0.0.1:8080/','http://127.0.0.1:8080/sw.js');expect(await requestLegacyWorkerUpdate({getRegistrations:async()=>[owned,foreignScope,foreignScript,otherPort]},origin)).toBe('requested');expect(owned.update).toHaveBeenCalledOnce();for(const value of [foreignScope,foreignScript,otherPort])expect(value.update).not.toHaveBeenCalled();for(const value of [owned,foreignScope,foreignScript,otherPort])expect(value.unregister).not.toHaveBeenCalled();});
 it('does not take over a registration with a different waiting worker',async()=>{const reg=registration();Object.assign(reg,{waiting:{scriptURL:`${origin}/another-app.js`}});expect(await requestLegacyWorkerUpdate({getRegistrations:async()=>[reg]},origin)).toBe('none');expect(reg.update).not.toHaveBeenCalled();});
 it('does not broaden a script URL by dropping its query string',async()=>{const reg=registration(`${origin}/`,`${origin}/sw.js?another=app`);expect(await requestLegacyWorkerUpdate({getRegistrations:async()=>[reg]},origin)).toBe('none');});
 it('handles unavailable APIs and interrupted update without activation/reload',async()=>{expect(await requestLegacyWorkerUpdate(undefined,origin)).toBe('unsupported');expect(await requestLegacyWorkerUpdate({getRegistrations:vi.fn().mockRejectedValue(Error('offline'))},origin)).toBe('failed');const reg=registration();vi.mocked(reg.update).mockRejectedValue(Error('offline'));expect(await requestLegacyWorkerUpdate({getRegistrations:async()=>[reg]},origin)).toBe('failed');expect(reg.unregister).not.toHaveBeenCalled();});
});
