import { describe,it,expect } from 'vitest';
import { legacyDashboardDestination } from '@/app/legacy-dashboard';
import { safeReturnPath } from '@/app/route-contracts';
describe('bounded legacy dashboard translation',()=>{
 it.each([['overview','/inicio'],['inbox','/mensajes'],['library','/materiales'],['study-plans','/materiales'],['assessments','/evaluaciones'],['grading','/correcciones'],['students','/personas?role=student'],['teachers','/personas?role=teacher'],['admins','/personas?role=admin'],['leaderboard','/progreso?tab=leaderboard'],['help-queue','/solicitudes'],['create','/generar'],['tutor','/tutor'],['settings','/ajustes/perfil']])('maps only the named %s view', (view,target)=>expect(legacyDashboardDestination('/inicio','',`#${view}`)).toBe(target));
 it('keeps legacy hash-over-view-over-tab precedence, including unknown hash no-op',()=>{expect(legacyDashboardDestination('/inicio','?view=library&tab=settings','#grading')).toBe('/correcciones');expect(legacyDashboardDestination('/inicio','?view=library&tab=settings','')).toBe('/materiales');expect(legacyDashboardDestination('/inicio','?tab=settings','')).toBe('/ajustes/perfil');expect(legacyDashboardDestination('/inicio','?view=library','#unknown')).toBeNull();});
 it('never interprets a hash outside /inicio or follows arbitrary destinations',()=>{expect(legacyDashboardDestination('/cursos/1','','#settings')).toBeNull();for(const view of ['https://evil.example','//evil.example','__proto__','constructor'])expect(legacyDashboardDestination('/inicio','',`#${view}`)).toBeNull();});
 it('retains only validated legacy context and never credentials or arbitrary targets',()=>expect(legacyDashboardDestination('/inicio','?content_id=4&plan_id=7&from_session=1&ask_help=1&password=secret&redirect=https://evil.example','#tutor')).toBe('/ayuda?content_id=4&plan_id=7&from_session=1&ask_help=1'));
 it('preserves bounded grading filters and review mode without arbitrary values',()=>{expect(legacyDashboardDestination('/inicio','?grading_filter=pending&filter=graded&mode=review','#grading')).toBe('/correcciones?filter=pending&mode=review');expect(legacyDashboardDestination('/inicio','?filter=secret&mode=edit','#grading')).toBe('/correcciones');});
 it('opens contextual help only for the verified legacy request flag combination',()=>{expect(legacyDashboardDestination('/inicio','?content_id=4&plan_id=7&from_session=1','#tutor')).toBe('/tutor?content_id=4&plan_id=7&from_session=1');expect(legacyDashboardDestination('/inicio','?ask_help=1&content_id=4','#tutor')).toBe('/tutor?content_id=4&ask_help=1');expect(legacyDashboardDestination('/inicio','?from_session=1&ask_help=1&content_id=bad','#tutor')).toBe('/tutor?from_session=1&ask_help=1');});
 it('rejects invalid IDs/flags and allows the shared data settings return',()=>{expect(legacyDashboardDestination('/inicio','?content_id=-2&plan_id=x&ask_help=true','#tutor')).toBe('/tutor');expect(safeReturnPath('/ajustes/datos')).toBe('/ajustes/datos');});
});
