import {it,expect,vi} from 'vitest';
import {act,render,screen,waitFor,within} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {QueryClientProvider} from '@tanstack/react-query';
import {createMemoryRouter,RouterProvider} from 'react-router';
import {AuthController} from '@/app/auth-controller';
import {AuthProvider} from '@/app/AuthProvider';
import {ProtectedLayout} from '@/app/AppShell';
import {LearningWorkspace} from '@/features/learning/routes';
import {locales} from '@/features/learning/locales';
import {createQueryClient} from '@/lib/query';
import i18n from '@/i18n';
const account={id:1,username:'a',role:'student',first_name:'A',last_name:'Test',email:'a@example.test'};
const content={id:4,title:'Pinned lesson',content_type:'lesson',content_data:{content:'Synthetic lesson'}};
const session={id:7,content_id:4,start_time:'2026-10-07T12:00:00Z',status:'active',notes:'Server note',duration_minutes:0,duration_known:true,timestamp_provenance:'utc',content_snapshot:content,context_revision:{study_plan_id:null,content_digest:'pinned'}};
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status});
it('does not produce an unhandled invalidation rejection after completion expires',async()=>{
 await i18n.changeLanguage('en');i18n.addResourceBundle('en','learning',locales.en);window.scrollTo=vi.fn();
 let resolve!:(value:Response)=>void;
 const transport=vi.fn(async(path:RequestInfo|URL)=>{
  const p=String(path);
  if(p==='/api/classroom/messages/unread-count')return json({unread_count:0});if(p==='/api/auth/me')return json(account);
  if(p.endsWith('/end'))return new Promise<Response>(done=>{resolve=done;});
  if(p.startsWith('/api/learning/history/'))return json([session]);
  if(p==='/api/settings/timezone')return json({timezone:'UTC'});
  if(p.startsWith('/api/annotations'))return json([]);
  return json(null);
 });
 const queries=createQueryClient();const auth=new AuthController(queries,localStorage,transport);localStorage.setItem('token','A');
 const router=createMemoryRouter([{element:<ProtectedLayout/>,children:[{path:'/estudio/:sessionId',element:<LearningWorkspace/>},{path:'/cursos',element:<p>Course list</p>}]}],{initialEntries:['/estudio/7?content_id=4']});
 render(<QueryClientProvider client={queries}><AuthProvider controller={auth}><RouterProvider router={router}/></AuthProvider></QueryClientProvider>);
 await userEvent.click(await screen.findByRole('button',{name:'Complete session'}));
 await userEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Complete session'}));
 await waitFor(()=>expect(resolve).toBeTypeOf('function'));
 act(()=>auth.lock());
 await act(async()=>{resolve(json({...session,status:'completed'}));await new Promise(done=>setTimeout(done,10));});
 expect(auth.snapshot().status).toBe('locked');
 expect(router.state.location.pathname).toBe('/estudio/7');
});
