import { describe, expect, it, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import { ApiClient, ApiError, responseError, type Lease } from '@/lib/api';
import { browserStorage } from '@/lib/storage';
import { DraftAdapter, DRAFT_TTL } from '@/lib/drafts';
import { AuthController, normalizeUser } from '@/app/auth-controller';
import { createQueryClient } from '@/lib/query';
import { safeContent } from '@/components/content/ContentRenderer';
import { ErrorState, Field, Input } from '@/components/ui';
import { safeReturnPath, pathRoleAllowed } from '@/app/route-contracts';
import i18n, { bridgeInterpolation } from '@/i18n';
const user = { id:1,username:'demo',role:'teacher',first_name:'Demo',last_name:'Teacher',email:'demo@example.com' };
const json = (data: unknown, status=200) => new Response(JSON.stringify(data), { status, headers:{'Content-Type':'application/json'} });
function apiHarness(transport: typeof fetch) { let epoch=1; const unauthorized=vi.fn(); const api = new ApiClient({ lease: () => ({ token:'synthetic',epoch,scope:'1:1',permitted:true }), isCurrent:(lease:Lease) => lease.epoch===epoch, unauthorized }, transport); return {api,unauthorized,switchAccount:()=>epoch++}; }
describe('safe error boundary', () => {
 it.each([400,401,403,404,409,422,429,500])('never echoes arbitrary detail at %i', status => { const error=responseError(status,{detail:'Secret <script>value</script>'},true); expect(error.message).not.toContain('Secret'); expect(JSON.stringify(error)).not.toContain('Secret'); });
 it.each(['__proto__','constructor','toString'])('rejects inherited allowlist property %s',detail=>expect(responseError(400,{detail},false).messageKey).toBe('failed'));
 it('maps allowlisted D3 validator fields without msg/input/ctx', () => { const error=responseError(422,{detail:[{loc:['body','email'],type:'value_error',msg:'secret',input:'secret',ctx:{password:'secret'}},{loc:['body','password'],type:'missing',msg:'secret'},{loc:['query','password'],type:'missing'},{loc:['body','unknown'],type:'missing'}]},true); expect(error.fieldErrors).toEqual({email:'invalidEmail',password:'required'}); expect(JSON.stringify(error)).not.toContain('secret'); });
 it.each(['en','es'])('renders safe localized summary in %s', async language => { await i18n.changeLanguage(language); render(<ErrorState error={responseError(422,{detail:[{loc:['body','email'],type:'value_error',input:'private'}]},true)}/>); expect(screen.getByRole('alert')).not.toHaveTextContent('private'); expect(screen.getByRole('alert')).toHaveTextContent(language==='en' ? 'valid email' : 'correo válido'); });
 it('drops arbitrary JavaScript error messages',()=>{ render(<ErrorState error={new Error('database password leaked')}/>); expect(screen.getByRole('alert')).not.toHaveTextContent('password leaked'); });
 it('keeps 5xx mutation outcomes unknown even for a known detail',()=>expect(responseError(500,{detail:'Username already exists'},true)).toMatchObject({uncertain:true,messageKey:'uncertain'}));
});
describe('API ownership and certainty',()=>{
 it('uses same-origin relative bearer transport and signal',async()=>{ const fetcher=vi.fn().mockResolvedValue(json({id:1})); const {api}=apiHarness(fetcher); expect(await api.get('/api/content/1')).toEqual({id:1}); expect(fetcher.mock.calls[0][1]).toMatchObject({cache:'no-store',headers:{Authorization:'Bearer synthetic'}}); expect(fetcher.mock.calls[0][1].signal).toBeInstanceOf(AbortSignal); });
 it.each(['https://evil.example/api/x','//evil.example/api/x','/api/../../private','/api/\\evil','/web/index'])('rejects unsafe path %s',async path=>{const fetcher=vi.fn();await expect(apiHarness(fetcher).api.get(path)).rejects.toMatchObject({kind:'invalid'});expect(fetcher).not.toHaveBeenCalled();});
 it('sends explicit multipart data through the same ownership boundary without overriding its boundary header',async()=>{const transport=vi.fn().mockResolvedValue(json({id:1}));const api=apiHarness(transport).api;const form=new FormData();form.append('file',new Blob(['synthetic lesson'],{type:'text/plain'}),'demo.txt');await api.post('/api/upload/source-material',form);expect(transport.mock.calls[0][1].body).toBe(form);expect(transport.mock.calls[0][1].headers).not.toHaveProperty('Content-Type');expect(transport.mock.calls[0][1].headers.Authorization).toBe('Bearer synthetic');});
 it('marks network mutation uncertain and does not replay',async()=>{const fetcher=vi.fn().mockRejectedValue(new TypeError('secret host')); await expect(apiHarness(fetcher).api.post('/api/content/',{})).rejects.toMatchObject({kind:'network',uncertain:true});expect(fetcher).toHaveBeenCalledTimes(1);});
 it('distinguishes read network failure',async()=>{await expect(apiHarness(vi.fn().mockRejectedValue(new Error())).api.get('/api/content/')).rejects.toMatchObject({uncertain:false,messageKey:'network'});});
 it('treats non-JSON mutation success as unknown',async()=>{await expect(apiHarness(vi.fn().mockResolvedValue(new Response('not json'))).api.post('/api/content/',{})).rejects.toMatchObject({kind:'invalid',uncertain:true});});
 it('allows valid 204 receipt',async()=>expect(await apiHarness(vi.fn().mockResolvedValue(new Response(null,{status:204}))).api.delete('/api/content/1')).toBeNull());
 it('locks on 401 exactly once',async()=>{const {api,unauthorized}=apiHarness(vi.fn().mockResolvedValue(json({detail:'private'},401)));await expect(api.get('/api/content/')).rejects.toMatchObject({status:401});expect(unauthorized).toHaveBeenCalledOnce();});
 it('rejects a late response from the previous account',async()=>{let resolve!:(response:Response)=>void;const harness=apiHarness(vi.fn(()=>new Promise<Response>(done=>{resolve=done;})));const promise=harness.api.get('/api/content/');harness.switchAccount();resolve(json({private:'old'}));await expect(promise).rejects.toMatchObject({kind:'stale'});});
 it('rechecks ownership after asynchronous JSON decoding',async()=>{let resolve!:(value:unknown)=>void;const response={ok:true,status:200,json:()=>new Promise(done=>{resolve=done;})} as Response;const harness=apiHarness(vi.fn().mockResolvedValue(response));const promise=harness.api.get('/api/content/');await Promise.resolve();harness.switchAccount();resolve({private:'old'});await expect(promise).rejects.toMatchObject({kind:'stale'});});
 it('prevents old render-owned API handlers from using a replacement account token',async()=>{const fetcher=vi.fn().mockResolvedValue(json({id:1}));const harness=apiHarness(fetcher);const owned=harness.api.bind();harness.switchAccount();await expect(owned.post('/api/content/',{private:'old form'})).rejects.toMatchObject({kind:'stale',uncertain:false});expect(fetcher).not.toHaveBeenCalled();});
 it('blocks writes while reauthentication is being verified',async()=>{const transport=vi.fn();const api=new ApiClient({lease:()=>({token:'demo',epoch:1,scope:'demo',permitted:true,mutationsPermitted:false}),isCurrent:()=>true,unauthorized(){}},transport);await expect(api.post('/api/content/',{})).rejects.toMatchObject({status:401});expect(transport).not.toHaveBeenCalled();});
});
describe('account-owned bounded drafts',()=>{
 const isNote=(value:unknown):value is {notes:string}=>!!value&&typeof value==='object'&&'notes' in value&&typeof value.notes==='string';
 it('reads established note keys with exact owner',()=>{const a=new DraftAdapter(1);expect(a.write('notes',4,8,{notes:'A'})).toBe(true);expect(a.read('notes',4,8,isNote)).toEqual({notes:'A'});expect(new DraftAdapter(2).read('notes',4,8,isNote)).toBeNull();expect(localStorage.key(0)).toBe('slm_draft_v1:1:notes:4:8');});
 it('rejects expired, malicious long-lived and malformed payloads',()=>{const a=new DraftAdapter(1);for(const entry of [{owner:'1',expiresAt:Date.now()-1,value:{notes:'expired'}},{owner:'1',expiresAt:Date.now()+DRAFT_TTL*2,value:{notes:'too long'}},{owner:'1',expiresAt:Date.now()+10000,value:{notes:44}},{owner:'2',expiresAt:Date.now()+10000,value:{notes:'other'}}]){localStorage.setItem('slm_draft_v1:1:notes:4:8',JSON.stringify(entry));expect(a.read('notes',4,8,isNote)).toBeNull();}});
 it('clears only the exact owner prefix and leaves unrelated and unowned data intact',()=>{new DraftAdapter(1).write('notes',4,8,{notes:'A'});new DraftAdapter(10).write('notes',4,8,{notes:'B'});localStorage.setItem('unrelated','keep');localStorage.setItem('notes_legacy','keep');expect(new DraftAdapter(1).clearOwner()).toBe(true);expect(new DraftAdapter(10).hasDrafts()).toBe(true);expect(localStorage.getItem('unrelated')).toBe('keep');expect(localStorage.getItem('notes_legacy')).toBe('keep');});
 it('survives a denied localStorage property',()=>{const denied=browserStorage(()=>{throw new Error('Blocked');});const adapter=new DraftAdapter(1,denied);expect(adapter.write('notes',1,1,{})).toBe(false);expect(adapter.read('notes',1,1,isNote)).toBeNull();});
 it('reports blocked storage writes and deletion',()=>{const blocked={getItem(){throw Error();},setItem(){throw Error();},get length(){throw Error();}} as unknown as Storage;const adapter=new DraftAdapter(1,blocked);expect(adapter.write('notes',1,1,{})).toBe(false);expect(adapter.clearOwner()).toBe(false);expect(adapter.read('notes',1,1,isNote)).toBeNull();});
});
describe('authentication lifecycle',()=>{
 function harness() { const users:Record<string,unknown>={tokenA:user,tokenB:{...user,id:2,username:'other'}}; let forbidden=false; const calls:string[]=[]; const transport=vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{ const path=String(input);calls.push(`${init?.method||'GET'} ${path}`);if(path==='/api/auth/login'){const username=(init?.body as URLSearchParams).get('username');const token=username==='other'?'tokenB':'tokenA';return json({access_token:token,user:users[token]});}const token=(init?.headers as Record<string,string>)?.Authorization?.split(' ')[1];if(path==='/api/auth/me') return json(users[token]||{detail:'Not authenticated'},users[token]?200:401);if(forbidden) return json({detail:'Private owner details'},403);return json({id:9,title:'Protected'});});const queries=createQueryClient();const controller=new AuthController(queries,localStorage,transport);return {controller,queries,calls,users,forbid:()=>{forbidden=true;}}; }
 it('does not trust a persisted user without a verified token',async()=>{localStorage.setItem('user',JSON.stringify(user));const {controller}=harness();await controller.verify();expect(controller.snapshot()).toMatchObject({status:'anonymous',user:null});});
 it('canonicalizes enum-shaped roles and rejects malformed identity',()=>{expect(normalizeUser({...user,role:{value:'UserRole.ADMIN'}}).role).toBe('admin');expect(()=>normalizeUser({...user,id:0})).toThrow(ApiError);expect(()=>normalizeUser({...user,role:'root'})).toThrow(ApiError);});
 it('rejects login JSON that resolves after an explicit logout',async()=>{let release!:(value:unknown)=>void;const transport=vi.fn(async()=>({ok:true,status:200,json:()=>new Promise(done=>{release=done;})}) as Response);const controller=new AuthController(createQueryClient(),localStorage,transport);const pending=controller.login('demo','synthetic');await Promise.resolve();await controller.logout('keep');release({access_token:'old',user});await expect(pending).rejects.toMatchObject({kind:'stale'});expect(controller.snapshot()).toMatchObject({status:'anonymous',user:null});expect(localStorage.getItem('token')).toBeNull();expect(transport).toHaveBeenCalledTimes(1);});
 it('refreshes confirmed profile identity without unmounting the same-account buffer',async()=>{const h=harness();await h.controller.login('demo','synthetic');const scope=h.controller.snapshot().scope;h.users.tokenA={...user,first_name:'Updated'};await h.controller.refreshIdentity();expect(h.controller.snapshot()).toMatchObject({scope,status:'authenticated',user:{first_name:'Updated'}});});
 it('same account reauthentication keeps scope, revalidates resource and never replays mutation',async()=>{const h=harness();await h.controller.login('demo','synthetic');const scope=h.controller.snapshot().scope;h.controller.registerResource('/api/content/9');h.controller.lock();expect(h.controller.snapshot().status).toBe('locked');await h.controller.login('demo','synthetic');expect(h.controller.snapshot()).toMatchObject({status:'authenticated',scope});expect(h.calls.filter(path=>path==='GET /api/content/9')).toHaveLength(1);expect(h.calls.filter(path=>path.startsWith('POST '))).toEqual(['POST /api/auth/login','POST /api/auth/login']);});
 it('keeps private buffer locked after same-account permission revocation',async()=>{const h=harness();await h.controller.login('demo','synthetic');h.controller.registerResource('/api/content/9');h.controller.lock();h.forbid();await expect(h.controller.login('demo','synthetic')).rejects.toMatchObject({status:403});expect(h.controller.snapshot().status).toBe('locked');});
 it('switching accounts clears queries and changes scope',async()=>{const h=harness();await h.controller.login('demo','synthetic');const before=h.controller.snapshot().scope;h.queries.setQueryData([before,'private'],{secret:'A'});h.controller.lock();await h.controller.login('other','synthetic');expect(h.controller.snapshot().user?.id).toBe(2);expect(h.controller.snapshot().scope).not.toBe(before);expect(h.queries.getQueryCache().getAll()).toHaveLength(0);});
 it('same ID with changed role resets scope and private caches',async()=>{const h=harness();await h.controller.login('demo','synthetic');const before=h.controller.snapshot().scope;h.queries.setQueryData([before,'private'],{secret:'A'});h.users.tokenA={...user,role:'student'};h.controller.lock();await h.controller.login('demo','synthetic');expect(h.controller.snapshot().scope).not.toBe(before);expect(h.queries.getQueryCache().getAll()).toHaveLength(0);});
 it('clears private memory and discloses an unconfirmed persisted logout',async()=>{const store=browserStorage(()=>{throw new Error('Blocked');});const transport=vi.fn(async(path:RequestInfo|URL)=>String(path).endsWith('/login')?json({access_token:'synthetic',user}):json(user));const queries=createQueryClient();const controller=new AuthController(queries,store,transport);await controller.login('demo','synthetic');await controller.logout('keep');expect(controller.snapshot()).toMatchObject({status:'anonymous',user:null,error:{messageKey:'logoutStorage'}});});
 it('logout keep and delete are explicit and owner-specific',async()=>{const h=harness();await h.controller.login('demo','synthetic');new DraftAdapter(1).write('notes',1,1,{});new DraftAdapter(2).write('notes',1,1,{});await h.controller.logout('keep');expect(new DraftAdapter(1).hasDrafts()).toBe(true);await h.controller.login('demo','synthetic');await h.controller.logout('delete');expect(new DraftAdapter(1).hasDrafts()).toBe(false);expect(new DraftAdapter(2).hasDrafts()).toBe(true);expect(localStorage.getItem('token')).toBeNull();});
 it('storage/BFCache verification checks the current account before accepting it',async()=>{const h=harness();await h.controller.login('demo','synthetic');localStorage.setItem('token','tokenB');const promise=h.controller.verify();expect(h.controller.snapshot().status).toBe('locked');await promise;expect(h.controller.snapshot().user?.id).toBe(2);});
});
describe('content, routes and fields',()=>{
 it('strips scripts, event handlers, SVG, styles and unsafe URLs',()=>{const html=safeContent('<script>alert(1)</script><svg onload="alert(2)"></svg><p style="display:none" onclick="alert(3)">Visible</p><a href="javascript:alert(4)">link</a><iframe src="https://evil.example"></iframe>','html');expect(html).toContain('Visible');expect(html).not.toMatch(/<script|<svg|onclick|style=|javascript:|iframe/);});
 it('preserves accessible table and markdown structure without remote fonts',()=>{expect(safeContent('## Title\n\n**Read** [link](https://example.com)')).toContain('<h2>Title</h2>');expect(safeContent('[link](https://example.com)')).toContain('rel="noopener noreferrer"');});
 it.each(['https://evil.example/inicio','//evil.example/inicio','/api/auth/me','/entrar','/cursos/../private','/cursos/0'])('rejects return path %s',path=>expect(safeReturnPath(path)).toBe('/inicio'));
 it('keeps valid deep-link resource context',()=>expect(safeReturnPath('/estudio/2?content_id=9&plan_id=3#notes')).toBe('/estudio/2?content_id=9&plan_id=3#notes'));
 it('does not grant role authority from route text',()=>{expect(pathRoleAllowed('/personas/nueva','student')).toBe(false);expect(pathRoleAllowed('/administracion/copias','teacher')).toBe(false);});
 it('bridges only bare legacy interpolation once',()=>expect(bridgeInterpolation({message:'Hello {name}; {{count}}'})).toEqual({message:'Hello {{name}}; {{count}}'}));
 it('connects visible label, hint and error to field',()=>{render(<Field label="Email" hint="Hint" error="Fix email"><Input/></Field>);const input=screen.getByLabelText('Email');expect(input).toHaveAttribute('aria-invalid','true');expect(input).toHaveAccessibleDescription('Hint Fix email');});
});
