import {describe,expect,it} from 'vitest';
import {confirmRequest,confirmResolution,filterRequests,helpFilters,parseRequestContext,parseRequests} from '@/features/help/contracts';
import {helpRequest} from './messages-fixtures';
describe('help request API contracts',()=>{
 it('accepts open and resolved with actual priority, without unread metadata',()=>{expect(parseRequests([helpRequest(),helpRequest({id:22,status:'resolved',priority:5})])).toHaveLength(2);expect(()=>parseRequests([helpRequest({status:'pending' as 'open'})])).toThrow();expect(()=>parseRequests([helpRequest({priority:6})])).toThrow();expect(()=>parseRequests([helpRequest()],7)).toThrow();});
 it('accepts only validated numeric contextual handoffs',()=>{expect(parseRequestContext(new URLSearchParams('content_id=12&plan_id=22&session_id=32&question_id=42'))).toEqual({content_id:12,study_plan_id:22,session_id:32,question_id:42});expect(parseRequestContext(new URLSearchParams('content_id=12&from_session=1'))?.session_id).toBeNull();for(const query of ['content_id=0','plan_id=1e3','session_id=1','content_id=https://evil.test','content_id=1.5'])expect(parseRequestContext(new URLSearchParams(query))).toBeNull();});
 it('preserves safe list filters and excludes destinations or arbitrary context',()=>{expect(helpFilters(new URLSearchParams('q=angle&status=open&priority=2&return=https://evil.test')).toString()).toBe('q=angle&status=open&priority=2');expect(filterRequests([helpRequest(),helpRequest({id:22,status:'resolved'})],new URLSearchParams('status=open&priority=2&q=ANGLE'))).toHaveLength(1);});
 it('confirms request identity, body, context and priority',()=>{const input={subject:'Question',description:'My description',urgency:3,client_request_id:'synthetic-id',content_id:12,study_plan_id:null,session_id:null,question_id:null};const result=helpRequest({student_id:7,subject:input.subject,request_text:'Question: My description',priority:3,client_request_id:input.client_request_id,content_id:12});expect(()=>confirmRequest(result,input,7)).not.toThrow();expect(()=>confirmRequest({...result,client_request_id:'other'},input,7)).toThrow();expect(()=>confirmRequest({...result,content_id:13},input,7)).toThrow();});
 it('requires a real resolved acknowledgement',()=>{expect(()=>confirmResolution({status:'resolved',resolved_at:'2026-10-07T11:00:00Z'})).not.toThrow();expect(()=>confirmResolution({success:true})).toThrow();expect(()=>confirmResolution({status:'resolved'})).toThrow();});
});
