import {act,fireEvent,screen,waitFor,within} from '@testing-library/react';
import {describe,expect,it} from 'vitest';
import {deferred,json,message,mountClassroom} from './messages-fixtures';
const writes=(calls:{method:string;path:string}[])=>calls.filter(call=>call.method!=='GET' && call.path!=='/api/auth/login');
describe('message workflows with synthetic transport',()=>{
 it('reads three folders without mutating merely by visiting',async()=>{const view=await mountClassroom('/mensajes');await screen.findByRole('button',{name:'Synthetic question'});expect(writes(view.calls)).toHaveLength(0);await view.user.click(screen.getByRole('button',{name:'Sent'}));await screen.findByRole('button',{name:'Saved response'});expect(view.router.state.location.search).toContain('folder=sent');view.dispose();});
 it('replies to the exact sender ID when two contacts have the same name',async()=>{const view=await mountClassroom('/mensajes?message=1');await view.user.click(await screen.findByRole('button',{name:'Reply'}));expect(screen.getByLabelText('Recipient')).toHaveValue('9');await view.user.type(screen.getByLabelText('Message',{exact:true}),'A useful response');await view.user.click(screen.getByRole('button',{name:'Send message'}));await screen.findByText(/Message sent\./);expect(writes(view.calls)[0]).toMatchObject({path:'/api/classroom/messages',body:{recipient_id:9,subject:'Re: Synthetic question',body:'A useful response'}});view.dispose();});
 it('limits select-all and bulk action to visible search results and clears folder selection',async()=>{const view=await mountClassroom('/mensajes');await screen.findByRole('button',{name:'Synthetic question'});await view.user.click(screen.getByRole('checkbox',{name:'Select all visible results'}));await view.user.type(screen.getByLabelText('Search messages'),'Another');expect(screen.getByText('0 selected in these results')).toBeVisible();await view.user.click(screen.getByRole('checkbox',{name:'Select all visible results'}));await view.user.click(screen.getByRole('button',{name:'Archive'}));await screen.findByText('Confirmed changes: 1.');expect(writes(view.calls)).toEqual([expect.objectContaining({path:'/api/classroom/messages/2/archive'})]);await view.user.click(screen.getByRole('button',{name:'Archived'}));await screen.findByRole('button',{name:'Another question'});expect(screen.getByText('0 selected in these results')).toBeVisible();view.dispose();});
 it('confirms permanent shared deletion and does not offer a fictional trash',async()=>{const view=await mountClassroom('/mensajes');await view.user.click(await screen.findByRole('checkbox',{name:'Select Synthetic question'}));await view.user.click(screen.getByRole('button',{name:'Delete permanently'}));expect(writes(view.calls)).toHaveLength(0);const dialog=screen.getByRole('dialog');expect(within(dialog).getByText(/both sender and recipient/)).toBeVisible();await view.user.click(within(dialog).getByRole('button',{name:'Delete permanently'}));await screen.findByText('Confirmed changes: 1.');expect(writes(view.calls)[0]).toMatchObject({path:'/api/classroom/messages/1',method:'DELETE'});expect(screen.queryByRole('button',{name:'Trash'})).not.toBeInTheDocument();view.dispose();});
 it('reports partial bulk results and stops on the first unconfirmed result',async()=>{const view=await mountClassroom('/mensajes',{intercept:call=>call.path==='/api/classroom/messages/2/archive'?json({},500):undefined});await view.user.click(await screen.findByRole('checkbox',{name:'Select all visible results'}));await view.user.click(screen.getByRole('button',{name:'Archive'}));await screen.findByText(/Confirmed changes: 1 of 2/);expect(screen.getByRole('button',{name:'Archive'})).toBeDisabled();expect(writes(view.calls)).toHaveLength(2);view.dispose();});
 it('single-flights repeated send clicks and preserves an uncertain draft',async()=>{const pending=deferred<Response>();const view=await mountClassroom('/mensajes?compose=1',{intercept:call=>call.path==='/api/classroom/messages'&&call.method==='POST'?pending.promise:undefined});await view.user.selectOptions(await screen.findByLabelText('Recipient'),'8');await view.user.type(screen.getByLabelText('Subject'),'Synthetic');await view.user.type(screen.getByLabelText('Message',{exact:true}),'Private draft');const button=screen.getByRole('button',{name:'Send message'});fireEvent.click(button);fireEvent.click(button);await waitFor(()=>expect(writes(view.calls)).toHaveLength(1));await act(async()=>pending.resolve(json({})));await screen.findByText(/Delivery is unconfirmed/);expect(screen.getByLabelText('Message',{exact:true})).toHaveValue('Private draft');expect(button).toBeDisabled();expect(writes(view.calls)).toHaveLength(1);view.dispose();});
 it('does not clear a message after a late success following account replacement',async()=>{const pending=deferred<Response>();const view=await mountClassroom('/mensajes?compose=1',{intercept:call=>call.path==='/api/classroom/messages'&&call.method==='POST'?pending.promise:undefined});await view.user.selectOptions(await screen.findByLabelText('Recipient'),'8');await view.user.type(screen.getByLabelText('Subject'),'Private');await view.user.type(screen.getByLabelText('Message',{exact:true}),'Old account text');await view.user.click(screen.getByRole('button',{name:'Send message'}));view.replaceAccount(11,'teacher');await act(async()=>view.controller.login('synthetic_11','synthetic-password'));await act(async()=>pending.resolve(json(message({id:99,from_id:7,to_id:8,subject:'Private',content:'Old account text'}))));expect(screen.queryByDisplayValue('Old account text')).not.toBeInTheDocument();expect(screen.queryByText(/Message sent\./)).not.toBeInTheDocument();view.dispose();});
 it('preserves same-account reauthentication buffers and does not replay writes',async()=>{let reject=true;const view=await mountClassroom('/mensajes?compose=1',{intercept:call=>call.path==='/api/classroom/messages'&&call.method==='POST'&&reject?json({},401):undefined});await view.user.selectOptions(await screen.findByLabelText('Recipient'),'8');await view.user.type(screen.getByLabelText('Subject'),'Private');await view.user.type(screen.getByLabelText('Message',{exact:true}),'Kept draft');await view.user.click(screen.getByRole('button',{name:'Send message'}));await waitFor(()=>expect(view.controller.snapshot().status).toBe('locked'));expect(screen.queryByRole('textbox',{name:'Message'})).not.toBeInTheDocument();reject=false;await act(async()=>view.controller.login(accountName,'synthetic-password'));await screen.findByLabelText('Message',{exact:true});expect(screen.getByLabelText('Message',{exact:true})).toHaveValue('Kept draft');expect(writes(view.calls)).toHaveLength(1);expect(screen.getByRole('button',{name:'Send message'})).toBeDisabled();view.dispose();});
 it('shows Spanish labels and preserves unknown legacy timezone',async()=>{const view=await mountClassroom('/mensajes',{language:'es',messages:[message({sent_at:'2026-10-07T10:00:00'})]});await screen.findByRole('button',{name:'Synthetic question'});expect(screen.getByRole('heading',{name:'Mensajes',level:1})).toBeVisible();expect(screen.getByText(/zona horaria desconocida/)).toBeVisible();view.dispose();});
});
const accountName='synthetic_teacher';
