import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest';
import { act,fireEvent,screen,waitFor,within } from '@testing-library/react';
import { mountSettings,json,preview } from './settings-fixtures';
const mounted:Array<Awaited<ReturnType<typeof mountSettings>>>=[];
const mount:typeof mountSettings=async(...args)=>{const result=await mountSettings(...args);mounted.push(result);return result;};
let clicked:ReturnType<typeof vi.spyOn>;
beforeEach(()=>{vi.spyOn(window,'scrollTo').mockImplementation(()=>undefined);clicked=vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>undefined);Object.defineProperty(URL,'createObjectURL',{configurable:true,value:vi.fn(()=> 'blob:synthetic-download')});Object.defineProperty(URL,'revokeObjectURL',{configurable:true,value:vi.fn()});});
afterEach(()=>{mounted.splice(0).forEach(h=>h.dispose());vi.restoreAllMocks();});
const file=(text='{"version":2}',name='synthetic-course.json')=>{const value=new File([text],name,{type:'application/json'});Object.defineProperty(value,'text',{configurable:true,value:()=>Promise.resolve(text)});return value;};
async function importFile(h:Awaited<ReturnType<typeof mount>>,value=file()) {await h.user.selectOptions(await screen.findByLabelText('Purpose'),'import');await h.user.upload(screen.getByLabelText('Teacher JSON file'),value);await h.user.click(screen.getByRole('button',{name:'Validate import'}));await screen.findByText('Preview ready. Check what is included and excluded before continuing.');}
async function confirm(name:string,h:Awaited<ReturnType<typeof mount>>) {await h.user.click(screen.getByRole('button',{name}));await h.user.click(within(await screen.findByRole('dialog')).getByRole('button',{name}));}
describe('Preview-first portability synthetic journeys',()=>{
 it('learner has reading exports only and no staff or backup API reads',async()=>{const h=await mount('/ajustes/datos','student');const purpose=await screen.findByLabelText('Purpose');expect(within(purpose).getAllByRole('option')).toHaveLength(1);expect(screen.queryByRole('link',{name:'Private database backup'})).not.toBeInTheDocument();expect(screen.queryByLabelText('Teacher JSON file')).not.toBeInTheDocument();expect(h.calls.some(c=>c.path.includes('backup'))).toBe(false);});
 it('direct backup route is unavailable without backend calls for teacher',async()=>{const h=await mount('/administracion/copias','teacher');expect(h.calls.some(c=>c.path.includes('/portability/backup'))).toBe(false);expect(screen.queryByRole('button',{name:'Review backup scope'})).not.toBeInTheDocument();});
 it('preserves contextual plan and invalidates export preview after selection edits',async()=>{
  const h=await mount('/ajustes/datos?plan_id=4','student');const download=await screen.findByRole('button',{name:'Download selected export'});expect(download).toBeDisabled();expect(screen.getByLabelText('Course')).toHaveValue('4');await h.user.click(screen.getByRole('button',{name:'Review preview'}));await waitFor(()=>expect(download).toBeEnabled());await h.user.selectOptions(screen.getByLabelText('File format'),'markdown');expect(download).toBeDisabled();expect(screen.queryByText('Preview ready. Check what is included and excluded before continuing.')).not.toBeInTheDocument();expect(h.calls.some(c=>c.path.includes('/export?'))).toBe(false);
 });
 it('late preview for an edited selection never enables download',async()=>{
  const h=await mount('/ajustes/datos?plan_id=4');let finish!:(response:Response)=>void;h.intercept(call=>call.path.includes('/preview?')?new Promise<Response>(resolve=>{finish=resolve;}):undefined);await h.user.click(await screen.findByRole('button',{name:'Review preview'}));await waitFor(()=>expect(finish).toBeDefined());await h.user.selectOptions(screen.getByLabelText('File format'),'json');await act(async()=>finish(json(preview())));expect(screen.getByRole('button',{name:'Download selected export'})).toBeDisabled();expect(screen.queryByText('Preview ready. Check what is included and excluded before continuing.')).not.toBeInTheDocument();
 });
 it('downloads exact selected media only after preview and confirmation without caching blob',async()=>{
  const h=await mount('/ajustes/datos?plan_id=4');await h.user.click(await screen.findByRole('button',{name:'Review preview'}));await screen.findByText('Preview ready. Check what is included and excluded before continuing.');await confirm('Download selected export',h);expect(await screen.findByText('Download prepared. Store it securely.')).toBeInTheDocument();expect(clicked).toHaveBeenCalledOnce();expect(h.queries.getMutationCache().getAll().every(m=>!(m.state.data instanceof Blob)&&m.state.variables===undefined)).toBe(true);h.unmount();expect(URL.revokeObjectURL).toHaveBeenCalledWith('blob:synthetic-download');
 });
 it('rejects a server response with the wrong download media type',async()=>{
  const h=await mount('/ajustes/datos?plan_id=4');h.intercept(call=>call.path.includes('/export?')?new Response('incorrect',{headers:{'Content-Type':'application/json'}}):undefined);await h.user.click(await screen.findByRole('button',{name:'Review preview'}));await screen.findByText('Preview ready. Check what is included and excluded before continuing.');await confirm('Download selected export',h);expect(await screen.findByRole('alert')).toBeInTheDocument();expect(clicked).not.toHaveBeenCalled();expect(screen.queryByText('Download prepared. Store it securely.')).not.toBeInTheDocument();
 });
 it('teacher packages are JSON-only and limited to managed courses',async()=>{const h=await mount('/ajustes/datos');await h.user.selectOptions(await screen.findByLabelText('Purpose'),'teacher');const course=screen.getByLabelText('Course');expect(within(course).queryByRole('option',{name:'Visible other course'})).not.toBeInTheDocument();expect(screen.getByLabelText('File format')).toHaveValue('json');expect(screen.getByLabelText('File format')).toBeDisabled();});
 it('changing purpose removes previous preview and its pending confirmation',async()=>{const h=await mount('/ajustes/datos?plan_id=4');await h.user.click(await screen.findByRole('button',{name:'Review preview'}));await screen.findByText('Preview ready. Check what is included and excluded before continuing.');await h.user.selectOptions(screen.getByLabelText('Purpose'),'teacher');expect(screen.getByRole('button',{name:'Download selected export'})).toBeDisabled();expect(screen.queryByText('Preview ready. Check what is included and excluded before continuing.')).not.toBeInTheDocument();});
 it('new import creates a private draft only after preview and explicit confirmation',async()=>{
  const h=await mount('/ajustes/datos');await importFile(h);expect(h.calls.some(c=>c.path==='/api/portability/import')).toBe(false);await confirm('Create new draft',h);expect(await screen.findByRole('link',{name:'Open draft for review'})).toHaveAttribute('href','/cursos/41/editar');expect(h.calls.find(c=>c.path==='/api/portability/import')?.body).toEqual({package:{version:2},confirm:true});expect(screen.getByRole('button',{name:'Create new draft'})).toBeDisabled();expect(h.queries.getMutationCache().getAll().every(m=>m.state.variables===undefined)).toBe(true);
 });
 it('replacing the file invalidates the reviewed package',async()=>{const h=await mount('/ajustes/datos');await importFile(h);await h.user.upload(screen.getByLabelText('Teacher JSON file'),file('{"version":1}','other.json'));expect(screen.getByRole('button',{name:'Create new draft'})).toBeDisabled();expect(screen.queryByText('Preview ready. Check what is included and excluded before continuing.')).not.toBeInTheDocument();});
 it('invalid JSON never reaches import preview endpoint',async()=>{const h=await mount('/ajustes/datos');await h.user.selectOptions(await screen.findByLabelText('Purpose'),'import');await h.user.upload(screen.getByLabelText('Teacher JSON file'),file('{broken'));await h.user.click(screen.getByRole('button',{name:'Validate import'}));expect(await screen.findByRole('alert')).toBeInTheDocument();expect(h.calls.some(c=>c.path==='/api/portability/import/preview')).toBe(false);});
 it('unknown import outcome blocks replay and preserves a course inspection link',async()=>{const h=await mount('/ajustes/datos');await importFile(h);h.intercept(call=>call.path==='/api/portability/import'?json({study_plan_id:41,status:'published'}):undefined);await confirm('Create new draft',h);expect(await screen.findByText('The outcome was not confirmed. Check your courses before attempting the action again.')).toBeInTheDocument();expect(screen.getByRole('link',{name:'Open courses'})).toBeInTheDocument();expect(screen.getAllByRole('button',{name:'Create new draft'})[0]).toBeDisabled();expect(h.calls.filter(c=>c.path==='/api/portability/import')).toHaveLength(1);});
 it('revision preserves original and creates a separate draft after preview',async()=>{const h=await mount('/ajustes/datos?plan_id=4');await h.user.selectOptions(await screen.findByLabelText('Purpose'),'revision');await h.user.click(screen.getByRole('button',{name:'Review revision'}));await screen.findByText('Preview ready. Check what is included and excluded before continuing.');await confirm('Create revision draft',h);expect(await screen.findByRole('link',{name:'Open draft for review'})).toHaveAttribute('href','/cursos/42/editar');expect(h.calls.find(c=>c.path==='/api/study-plans/4/copy')?.body).toEqual({reason:'revision'});});
 it('admin backup shows CLI/new-destination guide and requires preview before private POST',async()=>{const h=await mount('/administracion/copias','admin');expect(await screen.findByRole('heading',{name:'Restore guide'})).toBeInTheDocument();expect(screen.getByText(/Existing output files are refused/)).toBeInTheDocument();expect(screen.queryByRole('button',{name:/restore/i})).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Download private backup'})).toBeDisabled();await h.user.click(screen.getByRole('button',{name:'Review backup scope'}));await screen.findByText('Original key fingerprint');expect(h.calls.some(c=>c.path==='/api/portability/backup')).toBe(false);await confirm('Download private backup',h);expect(await screen.findByText('Download prepared. Store it securely.')).toBeInTheDocument();expect(h.calls.find(c=>c.path==='/api/portability/backup')?.body).toEqual({confirm:true});expect(clicked).toHaveBeenCalledOnce();});
 it('same-account reauthentication invalidates old export preview',async()=>{const h=await mount('/ajustes/datos?plan_id=4');await h.user.click(await screen.findByRole('button',{name:'Review preview'}));await screen.findByText('Preview ready. Check what is included and excluded before continuing.');await act(async()=>{await h.controller.login('synthetic.teacher','unused');});expect(screen.getByRole('button',{name:'Download selected export'})).toBeDisabled();expect(screen.queryByText('Preview ready. Check what is included and excluded before continuing.')).not.toBeInTheDocument();});
 it('a late import preview after navigation does not write or publish anything',async()=>{const h=await mount('/ajustes/datos');await h.user.selectOptions(await screen.findByLabelText('Purpose'),'import');const pending=file();let finish!:(value:string)=>void;Object.defineProperty(pending,'text',{configurable:true,value:()=>new Promise<string>(resolve=>{finish=resolve;})});fireEvent.change(screen.getByLabelText('Teacher JSON file'),{target:{files:[pending]}});await h.user.click(screen.getByRole('button',{name:'Validate import'}));await waitFor(()=>expect(finish).toBeDefined());await h.user.selectOptions(screen.getByLabelText('Purpose'),'handout');await act(async()=>finish('{"version":2}'));expect(h.calls.some(c=>c.path==='/api/portability/import/preview')).toBe(false);});
});
