import { describe, expect, it } from 'vitest';
import { confirmGoal, goalInput, parseActivity, parseBadges, parseDue, parseEvidence, parseGoal, parseLeaderboard, parseParticipation, parseStats } from '@/features/progress/contracts';
import { locales } from '@/features/progress/locales';
import { locales as homeLocales } from '@/features/home/locales';
const policy={timezone:'UTC',day_timezone:null,day_provenance:'legacy_unknown',mixed_day_policy:false};
describe('progress contract boundaries',()=>{
 it('preserves zero counts and distinguishes missing final evidence',()=>{const stats={completed_lessons:0,total_study_time_minutes:0,unknown_duration_sessions:0,total_content:0,active_students:0,assessments_created:0,average_score:0};expect(parseStats(stats,true).average_score).toBe(0);expect(parseStats({...stats,average_score:null},true).average_score).toBeNull();expect(()=>parseStats({...stats,completed_lessons:undefined})).toThrow();});
 it('rejects fabricated mastery and invalid confidence',()=>{expect(parseEvidence({items:[{content_id:1,evidence_type:'final_assessment',assessment_percent:0,self_confidence:null}]} )[0]?.assessment_percent).toBe(0);expect(()=>parseEvidence({items:[{content_id:1,evidence_type:'legacy_or_self_report',assessment_percent:90,self_confidence:null}]})).toThrow();expect(()=>parseEvidence({items:[{content_id:1,evidence_type:'final_assessment',assessment_percent:90,self_confidence:6}]})).toThrow();});
 it('validates own-scope ranking rather than trusting another actor',()=>{const item={rank:1,user_id:7,username:'Synthetic',xp:0,level:1,metric_type:'participation',rank_scope:'visible_users'};expect(parseLeaderboard([item],7)[0]?.xp).toBe(0);expect(()=>parseLeaderboard([item],8)).toThrow();expect(()=>parseLeaderboard([{...item,metric_type:'mastery'}])).toThrow();expect(()=>parseLeaderboard([item,item])).toThrow();});
 it('keeps historical day provenance unknown and rejects invalid zones',()=>{const profile={xp:0,level:1,current_streak:0,longest_streak:0,last_activity_date:null,badges_earned:0,timezone:'UTC',day_provenance:'legacy_unknown'};expect(parseParticipation(profile).day_provenance).toBe('legacy_unknown');expect(()=>parseParticipation({...profile,timezone:'Invented/Zone'})).toThrow();});
 it('validates goal numbers and exact receipts',()=>{expect(goalInput('lessons','0',false)).toBeNull();expect(goalInput('time','1.5',false)).toBeNull();expect(goalInput('invalid','3',false)).toBeNull();expect(goalInput('time','45',true)).toEqual({goal_type:'time',target_value:45,save_as_default:true});const receipt={...policy,id:8,goal_type:'lessons',target_value:3,current_value:0,completed:false,goal_date:'2026-10-07'};expect(confirmGoal(receipt,{goal_type:'lessons',target_value:3,save_as_default:false}).id).toBe(8);expect(()=>confirmGoal(receipt,{goal_type:'time',target_value:3,save_as_default:false})).toThrow();});
 it('preserves zero and unknown goal provenance without accepting inconsistent no-goal data',()=>{const goal={...policy,has_goal:true,goal_type:'lessons',target:3,current:0,percentage:0,completed:false};expect(parseGoal(goal).current).toBe(0);expect(()=>parseGoal({...goal,has_goal:false})).toThrow();expect(()=>parseGoal({...goal,day_provenance:'recorded',day_timezone:null})).toThrow();});
 it('treats the legacy no-activity sentinel as empty and invalid payloads as failures',()=>{expect(parseActivity([{id:0,text:'No recent activity',time:'Start learning!'}])).toEqual([]);expect(()=>parseActivity({items:[]})).toThrow();expect(()=>parseActivity([{id:1,text:null,time:'Now'}])).toThrow();});
 it('validates due-review and badge identities',()=>{expect(()=>parseDue([{mastery_node_id:1,content_id:0,content_title:'Synthetic',content_type:'lesson',days_overdue:0,evidence_type:'legacy_or_self_report'}])).toThrow();expect(()=>parseBadges([{id:1,name:'Synthetic',description:'Badge',xp_value:0,earned:'yes',earned_at:null}])).toThrow();});
 it('keeps ES/EN keys and interpolation placeholders in parity',()=>{for(const module of [locales,homeLocales]){expect(Object.keys(module.en).sort()).toEqual(Object.keys(module.es).sort());for(const [key,text] of Object.entries(module.en)){expect(text.match(/{{\w+}}/g)?.sort() || []).toEqual((module.es as Record<string,string>)[key]!.match(/{{\w+}}/g)?.sort() || []);}}});
});
