import { act, screen, waitFor, within } from '@testing-library/react';
import { expect, it } from 'vitest';
import { mountProgress, json, goal, receipt } from './progress-fixtures';
it('shows zero final score distinctly from no score and labels counts as sessions',async()=>{
 const app=await mountProgress('/progreso');expect(await screen.findByText('Average recorded content score: 0%')).toBeVisible();expect(screen.getByText('Completed learning sessions')).toBeVisible();expect(screen.getByText('Completed sessions with unknown duration')).toBeVisible();expect(screen.getByRole('link',{name:'My assessment history'})).toHaveAttribute('href','/evaluaciones/historial');app.dispose();
});
it('keeps final evidence, legacy activity and self-confidence separate with read-only review links',async()=>{
 const app=await mountProgress('/progreso?tab=reviews');expect(await screen.findByText('Recorded final-assessment score: 0%')).toBeVisible();expect(screen.getByText('Self-rated confidence: 2/5')).toBeVisible();expect(screen.getByText('Recorded final-assessment score: No final score recorded')).toBeVisible();expect(screen.getAllByRole('link',{name:'Polygons'})[0]).toHaveAttribute('href','/materiales/21?mode=review');expect(app.calls.every(call=>call.method==='GET')).toBe(true);app.dispose();
});
it('distinguishes failed activity from an empty feed and displays original server text safely',async()=>{
 const app=await mountProgress('/progreso?tab=activity','student','en',call=>call.path==='/api/dashboard/activity'?json({detail:'private error'},500):undefined);expect(await screen.findByRole('alert')).toBeVisible();expect(screen.queryByText('No recent activity reported')).not.toBeInTheDocument();app.intercept(call=>call.path==='/api/dashboard/activity'?json([{id:3,text:"Completed '<script>synthetic</script>'",time:'Just now'}]):undefined);await app.user.click(screen.getByRole('button',{name:'Try again'}));expect(await screen.findByText("Completed '<script>synthetic</script>'")).toBeVisible();expect(document.querySelector('script')).toBeNull();app.dispose();
});
it('uses the nonmutating goal read and keeps zero and legacy provenance visible',async()=>{
 const app=await mountProgress('/progreso?tab=goal');expect(await screen.findByText('0 of 3 lessons')).toBeVisible();expect(screen.getByText('Goal day provenance: Original timezone unknown')).toBeVisible();expect(app.calls.some(call=>call.path==='/api/gamification/daily-goal')).toBe(false);app.dispose();
});
it('saves an exact goal receipt explicitly, once, and clears the dirty guard',async()=>{
 const app=await mountProgress('/progreso?tab=goal');const amount=await screen.findByLabelText('Target amount');await app.user.clear(amount);await app.user.type(amount,'5');await app.user.click(screen.getByRole('button',{name:'Save daily goal'}));expect(await screen.findByText('Daily goal saved for 2026-10-07 (UTC).')).toBeVisible();expect(app.calls.filter(call=>call.method==='POST')).toEqual([{path:'/api/gamification/daily-goal',method:'POST',body:{goal_type:'lessons',target_value:5,save_as_default:false}}]);await app.user.click(screen.getByRole('link',{name:'Overview'}));expect(await screen.findByText('Recorded study activity')).toBeVisible();expect(screen.queryByRole('dialog')).not.toBeInTheDocument();app.dispose();
});
it('protects dirty goal changes when changing progress sections',async()=>{
 const app=await mountProgress('/progreso?tab=goal');await app.user.type(await screen.findByLabelText('Target amount'),'0');await app.user.click(screen.getByRole('link',{name:'Overview'}));const dialog=await screen.findByRole('dialog');await app.user.click(within(dialog).getByRole('button',{name:'Cancel'}));expect(screen.getByLabelText('Target amount')).toHaveValue(30);expect(app.router.state.location.search).toBe('?tab=goal');app.dispose();
});
it('blocks duplicate goal writes and preserves an uncertain draft through a failed reconciliation',async()=>{
 let resolve!:(value:Response)=>void;const app=await mountProgress('/progreso?tab=goal','student','en',call=>call.method==='POST'?new Promise<Response>(done=>{resolve=done;}):undefined);const input=await screen.findByLabelText('Target amount');await app.user.clear(input);await app.user.type(input,'5');await app.user.dblClick(screen.getByRole('button',{name:'Save daily goal'}));expect(app.calls.filter(call=>call.method==='POST')).toHaveLength(1);await act(async()=>resolve(json({...receipt,target_value:99})));expect(await screen.findByText(/The save outcome is unknown/)).toBeVisible();expect(screen.getByRole('button',{name:'Save daily goal'})).toBeDisabled();app.intercept(call=>call.path==='/api/gamification/daily-goal/progress'?json({detail:'failed'},503):undefined);await app.user.click(screen.getByRole('button',{name:'Check current server goal'}));await waitFor(()=>expect(screen.getAllByRole('alert').length).toBeGreaterThan(0));expect(screen.getByLabelText('Target amount')).toHaveValue(5);expect(app.calls.filter(call=>call.method==='POST')).toHaveLength(1);app.dispose();
});
it('makes uncertain default-setting verification limits explicit rather than claiming success',async()=>{
 const app=await mountProgress('/progreso?tab=goal','student','en',call=>call.method==='POST'?json({},200):undefined);await app.user.click(await screen.findByLabelText('Also use this target as my default for future days'));await app.user.click(screen.getByRole('button',{name:'Save daily goal'}));await screen.findByText(/The save outcome is unknown/);await app.user.click(screen.getByRole('button',{name:'Check current server goal'}));expect(await screen.findByText(/does not expose the default for future days/)).toBeVisible();expect(screen.queryByText(/Daily goal saved for/)).not.toBeInTheDocument();await app.user.click(screen.getByRole('button',{name:'Use server goal and discard these edits'}));expect(screen.getByLabelText('Target amount')).toHaveValue(3);expect(app.calls.filter(call=>call.method==='POST')).toHaveLength(1);app.dispose();
});
it('preserves a confirmed save receipt if its following refresh fails',async()=>{
 let saved=false;const app=await mountProgress('/progreso?tab=goal','student','en',call=>{if(call.method==='POST'){saved=true;return json(receipt);}if(saved && call.path==='/api/gamification/daily-goal/progress')return json({},503);});await app.user.clear(await screen.findByLabelText('Target amount'));await app.user.type(screen.getByLabelText('Target amount'),'5');await app.user.click(screen.getByRole('button',{name:'Save daily goal'}));expect(await screen.findByText('Daily goal saved for 2026-10-07 (UTC).')).toBeVisible();await screen.findByRole('alert');expect(screen.queryByText(/The save outcome is unknown/)).not.toBeInTheDocument();expect(screen.getByLabelText('Target amount')).toHaveValue(5);app.dispose();
});
it('never publishes a late goal receipt after an account replacement',async()=>{
 let resolve!:(value:Response)=>void;const app=await mountProgress('/progreso?tab=goal','student','en',call=>call.method==='POST' && call.path==='/api/gamification/daily-goal'?new Promise<Response>(done=>{resolve=done;}):undefined);await app.user.clear(await screen.findByLabelText('Target amount'));await app.user.type(screen.getByLabelText('Target amount'),'5');await app.user.click(screen.getByRole('button',{name:'Save daily goal'}));app.changeAccount(88);app.intercept(call=>call.path==='/api/gamification/daily-goal/progress'?json({...goal,target:9}):undefined);await act(()=>app.controller.login('new','synthetic-password'));await waitFor(()=>expect(screen.getByLabelText('Target amount')).toHaveValue(9));await act(async()=>resolve(json(receipt)));expect(screen.queryByText(/Daily goal saved for/)).not.toBeInTheDocument();expect(screen.getByLabelText('Target amount')).toHaveValue(9);app.dispose();
});
it('labels ranking scope and fallback, preserves unknown badge times and ignores another student query',async()=>{
 const app=await mountProgress('/progreso?tab=leaderboard&student_id=999');expect(await screen.findByText('Synthetic participation badge')).toBeVisible();expect(screen.getByText('2025-01-01T12:00:00 (Original timezone unknown)')).toBeVisible();expect(screen.getAllByText('Only your own active account. This is not a peer or global ranking.').length).toBeGreaterThan(0);expect(screen.getByText(/otherwise lifetime XP/)).toBeVisible();expect(app.calls.some(call=>call.path.includes('999'))).toBe(false);await app.user.selectOptions(screen.getByLabelText('Requested period'),'monthly');await waitFor(()=>expect(app.calls.some(call=>call.path.endsWith('period=monthly'))).toBe(true));app.dispose();
});
it('rejects another student ranking even when the server accidentally returns it',async()=>{
 const app=await mountProgress('/progreso?tab=leaderboard','student','es',call=>call.path.startsWith('/api/gamification/leaderboard?')?json([{rank:1,user_id:999,username:'Foreign person',xp:1,level:1,metric_type:'participation',rank_scope:'visible_users'}]):undefined);expect(await screen.findByRole('alert')).toBeVisible();expect(screen.queryByText('Foreign person')).not.toBeInTheDocument();expect(screen.getByText('Tu participación')).toBeVisible();app.dispose();
});
it('retains an in-flight goal as unresolved through same-account reauthentication without replay',async()=>{
 let resolve!:(value:Response)=>void;const app=await mountProgress('/progreso?tab=goal','student','en',call=>call.method==='POST' && call.path==='/api/gamification/daily-goal'?new Promise<Response>(done=>{resolve=done;}):undefined);await app.user.clear(await screen.findByLabelText('Target amount'));await app.user.type(screen.getByLabelText('Target amount'),'5');await app.user.click(screen.getByRole('button',{name:'Save daily goal'}));act(()=>app.controller.lock());expect(screen.getByLabelText('Target amount')).not.toBeVisible();await act(async()=>resolve(json(receipt)));await act(()=>app.controller.login('synthetic.learner','synthetic-password'));expect(screen.getByLabelText('Target amount')).toHaveValue(5);expect(screen.getByRole('button',{name:'Save daily goal'})).toBeDisabled();expect(screen.getByText(/The save outcome is unknown/)).toBeVisible();expect(app.calls.filter(call=>call.path==='/api/gamification/daily-goal' && call.method==='POST')).toHaveLength(1);expect(screen.queryByText(/Daily goal saved for/)).not.toBeInTheDocument();app.dispose();
});
it('lets a learner explicitly establish today’s displayed default without changing its value',async()=>{
 const app=await mountProgress('/progreso?tab=goal');const button=await screen.findByRole('button',{name:'Save daily goal'});expect(button).toBeEnabled();await app.user.click(button);await screen.findByText('Daily goal saved for 2026-10-07 (UTC).');expect(app.calls.filter(call=>call.method==='POST')[0]?.body).toEqual({goal_type:'lessons',target_value:3,save_as_default:false});app.dispose();
});
it('does not claim that increasing a completed goal reopens server-side counting',async()=>{
 let saved=false;const app=await mountProgress('/progreso?tab=goal','student','en',call=>{if(call.method==='POST' && call.path==='/api/gamification/daily-goal'){saved=true;return json({...receipt,current_value:3,completed:true});}if(call.path==='/api/gamification/daily-goal/progress')return json({...goal,target:saved?5:3,current:3,percentage:saved?60:100,completed:true});});await app.user.clear(await screen.findByLabelText('Target amount'));await app.user.type(screen.getByLabelText('Target amount'),'5');await app.user.click(screen.getByRole('button',{name:'Save daily goal'}));expect(await screen.findByText(/Increasing the target does not restart counting/)).toBeVisible();expect(screen.getByText('Server status: completed; this goal no longer accrues activity.')).toBeVisible();expect(screen.getByText('3 of 5 lessons')).toBeVisible();app.dispose();
});
