import { describe,expect,it } from 'vitest';
import { aiDefaults, aiPayload, aiValues, confirmAI, confirmPassword, parseAI, parseApp, parseModels, parseProfile, parseStatus, parseTest, parseTimezone, passwordValid, sameDestination } from '@/features/settings/contracts';
import { locales } from '@/features/settings/locales';
describe('Settings real-contract boundaries',()=>{
 it('has matching ES/EN labels',()=>expect(Object.keys(locales.en).sort()).toEqual(Object.keys(locales.es).sort()));
 it('keeps public AI settings key-free',()=>{expect(parseAI({...aiDefaults,api_key:null})).not.toHaveProperty('api_key');expect(()=>parseAI({...aiDefaults,api_key:'do-not-cache'})).toThrow();});
 it('rejects unsupported providers and token/temperature ranges',()=>{for(const patch of [{provider:'arbitrary'},{max_tokens:0},{max_tokens:2.5},{max_tokens:16385},{temperature:3},{model:''}])expect(()=>parseAI({...aiDefaults,...patch})).toThrow();});
 it('omits blank secrets and incompatible reasoning overrides',()=>{const values={...aiValues(aiDefaults),reasoning_effort:'none' as const};expect(aiPayload(values)).not.toHaveProperty('api_key');expect(aiPayload(values).reasoning_effort).toBeNull();expect(aiPayload({...values,provider:'lm_studio'}).reasoning_effort).toBe('none');});
 it('clear key takes priority over typed replacement',()=>expect(aiPayload({...aiValues(aiDefaults),api_key:'synthetic',clear_api_key:true})).not.toHaveProperty('api_key'));
 it('identifies configured catalog provenance',()=>{expect(sameDestination(aiValues(aiDefaults),aiDefaults)).toBe(true);expect(sameDestination({...aiValues(aiDefaults),endpoint:'http://new.test'},aiDefaults)).toBe(false);expect(()=>parseModels({provider:'openai',models:['a']},'ollama')).toThrow();});
 it('does not claim mismatched save or test receipts succeeded',()=>{expect(()=>confirmAI({...aiDefaults,model:'other'},aiValues(aiDefaults))).toThrow('uncertain');expect(()=>parseTest({status:'connected',model:'other',provider:'ollama',response_time_ms:1},aiValues(aiDefaults))).toThrow();expect(()=>parseTest({status:'error',error:'private upstream error'},aiValues(aiDefaults))).toThrow('failed');});
 it('validates password bytes and full revocation receipt',()=>{expect(passwordValid('SyntheticExample123!')).toBe(true);expect(passwordValid('synthetic')).toBe(false);expect(passwordValid('SyntheticPassword1 ')).toBe(false);expect(passwordValid('Árbolcontraseña123!')).toBe(true);expect(passwordValid(`A1!${'é'.repeat(36)}`)).toBe(false);expect(()=>confirmPassword({success:true})).toThrow('uncertain');expect(confirmPassword({success:true,reauthentication_required:true})).toBe(true);});
 it('rejects unknown timezone policy and malformed app/status/profile',()=>{expect(()=>parseTimezone({timezone:'UTC'})).toThrow();expect(()=>parseApp({theme:'auto',language:'fr',font_size:'medium',enable_animations:true})).toThrow();expect(()=>parseStatus({status:'healthy',version:'2'})).toThrow();expect(()=>parseProfile({id:0})).toThrow();});
});
