import { useEffect, useState } from 'react';
import { Link, useParams, useSearchParams } from 'react-router';
import { useFieldArray, useForm, useWatch, type Control, type UseFormRegister, type UseFormSetValue } from 'react-hook-form';
import { useTranslation } from 'react-i18next';
import { useAuth } from '@/app/AuthProvider';
import { useContinuation } from '@/features/authoring/MaterialEditor';
import { useDirtyGuard } from '@/app/DirtyGuard';
import { positiveId } from '@/lib/ids';
import { useInvalidate, useOperation } from '@/lib/query';
import { Badge, Button, Card, ConfirmDialog, ErrorState, Field, Input, LoadingState, PageHeader, SaveStatus, Select, Textarea } from '@/components/ui';
import { assistanceModes, gradingModes, invalidResponse, isAssessment, isPolicy, isSubmissionList, isSummary, questionTypes, record, unavailable, type Assessment, type AssistanceMode } from './model';
import { canPublish, editorPayload, editorValues, generatedAssessment, newQuestion, type EditorValues } from './editor-model';
import { QuestionPreview, useValidated } from './shared';

export function AssessmentEditorPage() {
 const { user, scope } = useAuth(); const { assessmentId } = useParams(); const [params] = useSearchParams(); const raw = assessmentId || params.get('copy'); const id = raw ? positiveId(raw) : null;
 return user && user.role !== 'student' && (!raw || id) ? <EditorLoader key={`${scope}:${assessmentId || 'new'}:${params.get('copy') || ''}`} id={id} copy={!assessmentId && !!id} planId={positiveId(params.get('plan_id'))} topicId={positiveId(params.get('content_id'))}/> : <ErrorState error={unavailable()}/>;
}
function EditorLoader({ id, copy, planId, topicId }: { id: number | null; copy: boolean; planId: number | null; topicId: number | null }) {
 const data = useValidated(['assessment', id], id ? `/api/assessments/${id}` : null, value => isAssessment(value, id || undefined));
 const policy = useValidated(['assessment-policy', id], id ? `/api/assessments/${id}/assistance-policy` : null, value => isPolicy(value, id!));
 const attempts = useValidated(['submissions'], id && !copy ? '/api/assessments/submissions' : null, isSubmissionList);
 const [hydrated, setHydrated] = useState(false);
 // Reopening a stale detail must finish its first read before seeding form defaults.
 useEffect(() => { if (data.data && !data.error && !data.isFetching) setHydrated(true); }, [data.data, data.error, data.isFetching]);
 if (id && (!hydrated && data.isFetching || data.isPending || policy.isPending || !copy && attempts.isPending)) return <LoadingState/>;
 if (id && (data.error || policy.error || !copy && attempts.error)) return <ErrorState error={data.error || policy.error || attempts.error} retry={() => { void data.refetch(); void policy.refetch(); if (!copy) void attempts.refetch(); }}/>;
 if (id && !data.data?.can_manage) return <ErrorState error={unavailable()}/>;
 return <AssessmentEditor data={data.data} copy={copy} mode={policy.data?.mode || 'hints_only'} hasAttempts={!copy && !!attempts.data?.some(item => item.assessment_id === id)} planId={planId} topicId={topicId}/>;
}
function AssessmentEditor({ data, copy, mode, hasAttempts, planId, topicId, onDirtyChange, onSaved }: { data?: Assessment; copy: boolean; mode: AssistanceMode; hasAttempts: boolean; planId: number | null; topicId: number | null; onDirtyChange?: (dirty: boolean) => void; onSaved?: (id: number) => void }) {
 const { t } = useTranslation('assessments'); const { api } = useAuth(); const invalidate = useInvalidate(); const current = useContinuation();
 const initial = editorValues(data, copy); if (!data && planId) initial.study_plan_id = String(planId); if (!data && topicId) initial.topic_id = String(topicId);
 const form = useForm<EditorValues>({ defaultValues: initial }); const values = useWatch({ control: form.control }) as EditorValues;
 const questions = useFieldArray({ control: form.control, name: 'questions' }); const criteria = useFieldArray({ control: form.control, name: 'criteria' });
 const [savedId, setSavedId] = useState<number | null>(!copy && data ? data.id : null); const [published, setPublished] = useState(!copy && !!data?.is_published); const [policy, setPolicy] = useState<AssistanceMode>(mode); const [savedPolicy, setSavedPolicy] = useState<AssistanceMode | null>(!copy && data ? mode : null); const [preview, setPreview] = useState(false); const [confirm, setConfirm] = useState(false); const [validation, setValidation] = useState(false); const [blockedRetry, setBlockedRetry] = useState(false);
 const dirty = form.formState.isDirty || policy !== savedPolicy; useDirtyGuard(onDirtyChange ? false : dirty);
 useEffect(() => { onDirtyChange?.(dirty); return () => onDirtyChange?.(false); }, [dirty, onDirtyChange]);
 const save = useOperation(async (input: EditorValues) => { const payload = editorPayload(input, hasAttempts); if (!payload) throw invalidResponse(); const result = savedId ? await api.put<unknown>(`/api/assessments/${savedId}`, payload) : await api.post<unknown>('/api/assessments/', payload); if (!isSummary(result) || savedId !== null && result.id !== savedId || !hasAttempts && result.is_published !== false || !result.can_manage) throw invalidResponse(true); return result; }, async (result, input) => { if (current()) { setSavedId(result.id); setPublished(result.is_published); form.reset(input); onSaved?.(result.id); } await Promise.all([invalidate(['assessment', result.id], { exact: true, refetchType: 'none' }), invalidate(['assessments'])]); });
 const savePolicy = useOperation(async (input: AssistanceMode) => { if (!savedId) throw unavailable(); const result = await api.put<unknown>(`/api/assessments/${savedId}/assistance-policy`, { mode: input }); if (!isPolicy(result, savedId) || result.mode !== input) throw invalidResponse(true); return result; }, async result => { setSavedPolicy(result.mode); await invalidate(['assessment-policy', result.assessment_id]); });
 const publish = useOperation(async () => { if (!savedId || dirty || !canPublish(form.getValues(), savedPolicy)) throw unavailable(); const result = await api.post<unknown>(`/api/assessments/${savedId}/publish`); if (!record(result) || result.id !== savedId || result.is_published !== true) throw invalidResponse(true); return result; }, async () => { if (current()) { setConfirm(false); setPublished(true); } await Promise.all([invalidate(['assessment', savedId], { exact: true, refetchType: 'none' }), invalidate(['assessments'])]); });
 const busy = save.isPending || savePolicy.isPending || publish.isPending; const uncertain = save.error?.uncertain || savePolicy.error?.uncertain || publish.error?.uncertain;
 async function refresh() { if (!savedId) { await invalidate(['assessments']); return; } try { const result = await api.get<unknown>(`/api/assessments/${savedId}`); if (!isAssessment(result, savedId)) throw invalidResponse(); setPublished(result.is_published); const resultPolicy = await api.get<unknown>(`/api/assessments/${savedId}/assistance-policy`); if (!isPolicy(resultPolicy, savedId)) throw invalidResponse(); setSavedPolicy(resultPolicy.mode); setBlockedRetry(false); } catch { setBlockedRetry(true); } }
 async function submit(input: EditorValues) { if (!editorPayload(input, hasAttempts)) { setValidation(true); return; } setValidation(false); setBlockedRetry(true); await save.mutateAsync(input).catch(() => undefined); }
 return <div className="stack"><Link to="/evaluaciones">{t('back')}</Link><PageHeader title={t(savedId ? 'edit' : 'newDraft')} description={copy ? t('copyNotice') : t('immutableNotice')} actions={savedId && <Link to={`/evaluaciones/${savedId}`}>{t('preview')}</Link>}/><Badge tone={published ? 'success' : 'neutral'}>{t(published ? 'published' : 'draft')}</Badge><form className="stack" onSubmit={form.handleSubmit(submit)}><fieldset disabled={busy} className="stack"><Card><div className="form-grid"><Field label={t('title')}><Input {...form.register('title', { required: true })} required/></Field><Field label={t('maxAttempts')}><Input type="number" min={1} max={100} step={1} required {...form.register('max_attempts')}/></Field></div><Field label={t('description')}><Textarea rows={3} {...form.register('description')}/></Field>{!savedId && <div className="form-grid"><Field label={t('courseId')} hint={t('contextHint')}><Input type="number" min={1} step={1} {...form.register('study_plan_id')}/></Field><Field label={t('topicId')} hint={t('contextHint')}><Input type="number" min={1} step={1} {...form.register('topic_id')}/></Field></div>}</Card><fieldset disabled={hasAttempts} className="stack"><Card><div className="form-grid"><Field label={t('timeLimit')} hint={t('optional')}><Input type="number" min={1} max={1440} step={1} {...form.register('time_limit_minutes')}/></Field><Field label={t('passingScore')}><Input type="number" min={0} max={100} step={1} required {...form.register('passing_score')}/></Field><Field label={t('gradingMode')}><Select {...form.register('grading_mode')}>{gradingModes.map(value => <option key={value} value={value}>{t(value)}</option>)}</Select></Field></div><p className="muted">{t('aiNotice')}</p></Card>
 {questions.fields.map((field, index) => <Card key={field.id}><div className="cluster"><h2>{t('previewQuestion', { number: index + 1 })}</h2><Button variant="ghost" aria-label={t('moveUp', { number: index + 1 })} disabled={index === 0} onClick={() => questions.move(index, index - 1)}>↑</Button><Button variant="ghost" aria-label={t('moveDown', { number: index + 1 })} disabled={index === questions.fields.length - 1} onClick={() => questions.move(index, index + 1)}>↓</Button><Button variant="danger" onClick={() => questions.remove(index)}>{t('removeQuestion', { number: index + 1 })}</Button></div><QuestionFields index={index} control={form.control} register={form.register} setValue={form.setValue}/></Card>)}<Button variant="secondary" onClick={() => questions.append(newQuestion())}>{t('addQuestion')}</Button>
 <Card><h2>{t('rubric')}</h2><Field label={t('rubricName')}><Input {...form.register('rubric_name')}/></Field><Field label={t('rubricDescription')}><Textarea {...form.register('rubric_description')}/></Field>{criteria.fields.map((field, index) => <div className="panel stack" key={field.id}><Field label={t('criterionName', { number: index + 1 })}><Input required {...form.register(`criteria.${index}.name`)}/></Field><Field label={t('criterionDescription', { number: index + 1 })}><Textarea {...form.register(`criteria.${index}.description`)}/></Field><Field label={t('criterionPoints', { number: index + 1 })}><Input type="number" min={1} max={10000} step={1} required {...form.register(`criteria.${index}.max_points`)}/></Field><Button variant="danger" onClick={() => criteria.remove(index)}>{t('removeCriterion', { number: index + 1 })}</Button></div>)}<Button variant="secondary" onClick={() => criteria.append({ name: '', description: '', max_points: '10' })}>{t('addCriterion')}</Button></Card></fieldset>
 {validation && <p role="alert" className="field-error">{t('invalidDefinition')}</p>}<ErrorState error={save.error}/><div className="cluster"><Button type="submit" busy={save.isPending} disabled={!!uncertain && blockedRetry}>{t('saveDraft')}</Button><Button variant="secondary" onClick={() => setPreview(value => !value)} aria-expanded={preview}>{t('preview')}</Button></div><SaveStatus state={save.isPending ? 'saving' : save.error?.uncertain ? 'uncertain' : form.formState.isDirty ? 'dirty' : save.isSuccess ? 'saved' : 'idle'}>{save.isSuccess && !form.formState.isDirty ? t('savedDraft') : undefined}</SaveStatus></fieldset></form>
 <Card><h2>{t('assistance')}</h2><Field label={t('assistance')} hint={t('policyScope')}><Select value={policy} disabled={busy || hasAttempts} onChange={event => setPolicy(event.target.value as AssistanceMode)}>{assistanceModes.map(mode => <option key={mode} value={mode}>{t(mode)}</option>)}</Select></Field><Button busy={savePolicy.isPending} disabled={!savedId || busy || hasAttempts || !!uncertain && blockedRetry} onClick={() => { setBlockedRetry(true); savePolicy.mutate(policy); }}>{t('savePolicy')}</Button><ErrorState error={savePolicy.error}/>{savePolicy.isSuccess && savedPolicy === policy && <SaveStatus state="saved">{t('policySaved')}</SaveStatus>}<p className="muted">{t('publishReady')}</p><Button disabled={!savedId || dirty || published || !canPublish(values, savedPolicy) || busy || !!uncertain && blockedRetry} onClick={() => setConfirm(true)}>{t('publish')}</Button><ErrorState error={publish.error}/></Card>
 {uncertain && <Card><p>{t('mutationUncertain')}</p>{!savedId && <Link to="/evaluaciones">{t('back')}</Link>}<Button variant="secondary" onClick={() => void refresh()}>{t('refresh')}</Button></Card>}
 {preview && <section className="stack"><h2>{t('preview')}</h2><p>{t('previewNotice')}</p>{values.questions.map((question, index) => <QuestionPreview key={index} number={index + 1} question={{ id: index + 1, options_supported: true, ...question, points: Number(question.points), options: { choices: Object.fromEntries(question.choices.map(choice => [choice.value, choice.label])) }, correct_answer: question.correct_answer || null }}/>)}</section>}
 <ConfirmDialog open={confirm} onOpenChange={setConfirm} title={t('publish')} description={t('publishDescription')} confirmLabel={t('publish')} busy={publish.isPending} onConfirm={() => { if (uncertain && blockedRetry) return; setConfirm(false); setBlockedRetry(true); publish.mutate(undefined); }}/></div>;
}
function QuestionFields({ index, control, register, setValue }: { index: number; control: Control<EditorValues>; register: UseFormRegister<EditorValues>; setValue: UseFormSetValue<EditorValues> }) {
 const { t } = useTranslation('assessments'); const question = useWatch({ control, name: `questions.${index}` }); const choices = useFieldArray({ control, name: `questions.${index}.choices` });
 useEffect(() => { if (question.question_type === 'true_false' && !question.choices.length) setValue(`questions.${index}.choices`, [{ value: 'True', label: 'True' }, { value: 'False', label: 'False' }], { shouldDirty: true }); }, [question.question_type, question.choices.length, index, setValue]);
 const objective = ['multiple_choice', 'true_false'].includes(question.question_type);
 return <div className="stack">{(question.rubrics.length > 0 || question.content_metadata !== null) && <div className="panel"><p>{t('preservedAssets')}</p>{question.rubrics.map((rubric, rubricIndex) => <details key={rubricIndex}><summary>{rubric.name}</summary><p>{rubric.description}</p><ul>{rubric.criteria.map((criterion, criterionIndex) => <li key={criterionIndex}>{criterion.name}: {criterion.max_points}. {criterion.description}</li>)}</ul></details>)}</div>}<Field label={t('questionText')}><Textarea required {...register(`questions.${index}.question_text`)}/></Field><div className="form-grid"><Field label={t('questionType')}><Select {...register(`questions.${index}.question_type`)} onChange={event => { void register(`questions.${index}.question_type`).onChange(event); setValue(`questions.${index}.correct_answer`, '', { shouldDirty: true }); if (event.target.value === 'true_false') setValue(`questions.${index}.choices`, [{ value: 'True', label: 'True' }, { value: 'False', label: 'False' }], { shouldDirty: true }); }}>{questionTypes.map(type => <option key={type} value={type}>{t(type)}</option>)}</Select></Field><Field label={t('questionPoints')}><Input type="number" min={1} max={10000} step={1} required {...register(`questions.${index}.points`)}/></Field></div>{objective && <><p className="muted">{t('choiceHelp')}</p>{choices.fields.map((field, choiceIndex) => <div className="form-grid" key={field.id}><Field label={t('choiceValue', { number: choiceIndex + 1 })}><Input required {...register(`questions.${index}.choices.${choiceIndex}.value`)}/></Field><Field label={t('choiceLabel', { number: choiceIndex + 1 })}><Input required {...register(`questions.${index}.choices.${choiceIndex}.label`)}/></Field><Button variant="ghost" onClick={() => choices.remove(choiceIndex)}>{t('removeChoice', { number: choiceIndex + 1 })}</Button></div>)}<Button variant="secondary" onClick={() => choices.append({ value: `option_${choices.fields.length + 1}`, label: '' })}>{t('addChoice')}</Button></>}<Field label={t('correctAnswer')} hint={t('optional')}>{objective ? <Select {...register(`questions.${index}.correct_answer`)}><option value="">{t('chooseKey')}</option>{question.choices.map((choice, choiceIndex) => <option key={choiceIndex} value={choice.value.trim().toLocaleLowerCase() === question.correct_answer.trim().toLocaleLowerCase() ? question.correct_answer : choice.value}>{choice.label || choice.value}</option>)}</Select> : <Textarea {...register(`questions.${index}.correct_answer`)}/>}</Field></div>;
}

/** Shared editable local proposal; authoring pages can aggregate its dirty state. */
export function AssessmentProposalEditor({ value, onDirtyChange, onSaved }: { value: unknown; onDirtyChange?: (dirty: boolean) => void; onSaved?: (id: number) => void }) {
 const data = generatedAssessment(value); const { user, scope } = useAuth();
 return data && user && user.role !== 'student' ? <AssessmentEditor key={scope} data={data} copy mode="hints_only" hasAttempts={false} planId={null} topicId={null} onDirtyChange={onDirtyChange} onSaved={onSaved}/> : <ErrorState error={invalidResponse()}/>;
}
