import { useEffect, useState } from 'react';
import { Link, useParams, useSearchParams } from 'react-router';
import { useForm } from 'react-hook-form';
import { useTranslation } from 'react-i18next';
import { useAuth } from '@/app/AuthProvider';
import { useDirtyGuard } from '@/app/DirtyGuard';
import { positiveId } from '@/lib/ids';
import { useInvalidate, useOperation } from '@/lib/query';
import { Button, Card, ConfirmDialog, ErrorState, Field, Input, LoadingState, PageHeader, SaveStatus, Select, Textarea } from '@/components/ui';
import { ContentRenderer } from '@/components/content/ContentRenderer';
import { confirmOk, finalizesQuestion, isAssessment, isSubmission, isSubmissionList, unavailable, validScore, type Assessment, type Submission } from './model';
import { SubmissionList } from './AssessmentPages';
import { RubricGrading } from './RubricGrading';
import { SubmissionBadge, SystemNotices, Timestamp, useValidated } from './shared';

function queueFilter(value: string | null): 'pending' | 'graded' | 'all' { return value === 'graded' || value === 'all' ? value : 'pending'; }
export function GradingQueuePage() { const { user, scope } = useAuth(); return user && user.role !== 'student' ? <GradingQueue key={scope}/> : <ErrorState error={unavailable()}/>; }
function GradingQueue() {
 const { t } = useTranslation('assessments'); const [params, setParams] = useSearchParams(); const filter = queueFilter(params.get('filter'));
 const queue = useValidated(['grading-queue'], '/api/assessments/submissions?status=submitted&status=graded&status=ai_graded&status=returned', isSubmissionList);
 const items = queue.data?.filter(item => filter === 'all' || (filter === 'graded' ? item.status === 'graded' : ['submitted', 'ai_graded', 'returned'].includes(item.status)));
 return <div className="stack"><PageHeader title={t('grading')} description={t('gradingDescription')} actions={<Button variant="secondary" onClick={() => void queue.refetch()}>{t('refresh')}</Button>}/><Card><Field label={t('queueFilter')}><Select value={filter} onChange={event => { const next = new URLSearchParams(params); next.set('filter', queueFilter(event.target.value)); setParams(next); }}><option value="pending">{t('pending')}</option><option value="graded">{t('graded')}</option><option value="all">{t('all')}</option></Select></Field></Card>{queue.isPending && <LoadingState/>}<ErrorState error={queue.error} retry={() => void queue.refetch()}/>{items && !queue.error && <SubmissionList items={items} staff filter={filter}/>}</div>;
}
export function GradingWorkspacePage() {
 const { user, scope } = useAuth(); const { submissionId } = useParams(); const [params] = useSearchParams(); const id = positiveId(submissionId || params.get('submission_id'));
 return user && user.role !== 'student' && id ? <GradingLoader key={`${scope}:${id}`} id={id} filter={queueFilter(params.get('filter'))}/> : <ErrorState error={unavailable()}/>;
}
function GradingLoader({ id, filter }: { id: number; filter: string }) {
 const submission = useValidated(['submission', id], `/api/assessments/submissions/${id}`, value => isSubmission(value, id));
 const assessmentId = submission.data?.assessment_id; const assessment = useValidated(['assessment', assessmentId], assessmentId ? `/api/assessments/${assessmentId}` : null, value => isAssessment(value, assessmentId));
 if (submission.isPending || submission.data && assessment.isPending) return <LoadingState/>;
 if (submission.error || assessment.error || !submission.data || !assessment.data?.can_manage) return <ErrorState error={submission.error || assessment.error || unavailable()} retry={() => { void submission.refetch(); if (assessmentId) void assessment.refetch(); }}/>;
 return <GradingWorkspace submission={submission.data} assessment={assessment.data} filter={filter} refresh={async () => { const result = await submission.refetch(); return !result.error && isSubmission(result.data, id); }}/>;
}
interface GradeForm { total: string; feedback: string; answers: Record<string, { score: string; feedback: string }> }
type GradeChange = { kind: 'question'; responseId: number; score: number; feedback: string } | { kind: 'total'; score: number; feedback: string } | { kind: 'ai' };
function gradeValues(submission: Submission): GradeForm { return { total: submission.score === null ? '' : String(submission.score), feedback: submission.feedback || '', answers: Object.fromEntries(submission.answers.map(answer => [String(answer.response_id), { score: answer.points === null ? '' : String(answer.points), feedback: answer.feedback || '' }])) }; }
function GradingWorkspace({ submission, assessment, filter, refresh }: { submission: Submission; assessment: Assessment; filter: string; refresh: () => Promise<boolean> }) {
 const { t } = useTranslation('assessments'); const { api } = useAuth(); const invalidate = useInvalidate(); const form = useForm<GradeForm>({ defaultValues: gradeValues(submission) }); const { dirtyFields } = form.formState;
 const [confirm, setConfirm] = useState<GradeChange | null>(null); const [checked, setChecked] = useState(false);
 const [rubricDirty, setRubricDirty] = useState<Record<number, boolean>>({}); const hasRubricDraft = Object.values(rubricDirty).some(Boolean);
 useDirtyGuard(form.formState.isDirty || hasRubricDraft);
 const { reset } = form;
 useEffect(() => { reset(gradeValues(submission), { keepDirtyValues: true }); }, [submission, reset]);
 const save = useOperation(async (input: GradeChange) => { const prefix = `/api/assessments/submissions/${submission.id}`; const path = input.kind === 'question' ? `${prefix}/responses/${input.responseId}/grade` : `${prefix}/${input.kind === 'ai' ? 'accept-ai' : 'grade'}`; const result = await api.post<unknown>(path, input.kind === 'ai' ? undefined : { score: input.score, feedback: input.feedback || null }); confirmOk(result); return input; }, async input => { setConfirm(null); if (input.kind === 'question') { form.resetField(`answers.${input.responseId}.score`, { defaultValue: String(input.score) }); form.resetField(`answers.${input.responseId}.feedback`, { defaultValue: input.feedback }); } else if (input.kind === 'total') { form.resetField('total', { defaultValue: String(input.score) }); form.resetField('feedback', { defaultValue: input.feedback }); } await invalidate(['submission', submission.id]); await invalidate(['grading-queue']); await invalidate(['submissions']); await invalidate(['progress']); });
 const submitted = ['submitted', 'ai_graded', 'graded', 'returned'].includes(submission.status); const blocked = !submitted || save.isPending || !!save.error?.uncertain && !checked;
 function saveQuestion(responseId: number, maximum: number) { if (hasRubricDraft) return; const current = form.getValues(`answers.${responseId}`); const score = validScore(current.score, maximum); if (score === null) { form.setError(`answers.${responseId}.score`, { message: t('wholeNumber') }, { shouldFocus: true }); return; } form.clearErrors(`answers.${responseId}.score`); const input: GradeChange = { kind: 'question', responseId, score, feedback: current.feedback }; if (finalizesQuestion(submission, responseId)) setConfirm(input); else { setChecked(false); save.mutate(input); } }
 function saveTotal() { if (hasRubricDraft) return; const score = validScore(form.getValues('total'), submission.total_points ?? 0); if (score === null) { form.setError('total', { message: t('wholeNumber') }, { shouldFocus: true }); return; } form.clearErrors('total'); setConfirm({ kind: 'total', score, feedback: form.getValues('feedback') }); }
 const allSuggestions = submission.answers.length > 0 && submission.answers.every(answer => answer.points !== null || answer.ai_suggested_score !== null);
 return <div className="stack"><Link to={`/correcciones?filter=${filter}`}>{t('backQueue')}</Link><PageHeader title={`${submission.student_name} · ${submission.assessment_title}`} description={t('selected', { id: submission.id })} actions={<Button variant="secondary" disabled={save.isPending} onClick={() => { void refresh().then(success => { if (success) setChecked(true); }); }}>{t('refresh')}</Button>}/><Card><SubmissionBadge status={submission.status}/><p>{t('submittedAt')}: <Timestamp value={submission.submitted_at}/></p><p>{submission.status === 'graded' && submission.score !== null ? `${t('finalScore')}: ${submission.score} / ${submission.total_points ?? '—'}` : t('noFinalScore')}</p><p>{t('aiNotice')}</p>{submission.status === 'ai_graded' && <><Button variant="secondary" disabled={blocked || !allSuggestions || form.formState.isDirty || hasRubricDraft} onClick={() => setConfirm({ kind: 'ai' })}>{t('acceptAll')}</Button>{!allSuggestions && <p>{t('incompleteSuggestions')}</p>}</>}</Card><SystemNotices notices={submission.system_notices}/><ErrorState error={save.error}/>{save.error?.uncertain && <p role="status">{t('mutationUncertain')}</p>}<SaveStatus state={save.isPending ? 'saving' : save.error?.uncertain ? 'uncertain' : form.formState.isDirty || hasRubricDraft ? 'dirty' : save.isSuccess ? 'saved' : 'idle'}>{save.isSuccess && !form.formState.isDirty && !hasRubricDraft ? t('gradeSaved') : undefined}</SaveStatus><form className="stack" onSubmit={event => { event.preventDefault(); if (!blocked) saveTotal(); }}><fieldset disabled={blocked} className="stack">
 {submission.answers.map((answer, index) => { const question = assessment.questions.find(item => item.id === answer.question_id); const rubrics = question?.rubrics.length ? question.rubrics : assessment.rubric && !['multiple_choice', 'true_false'].includes(answer.question_type) ? [assessment.rubric] : []; return <Card key={answer.response_id}><h2>{t('questionGrade', { number: index + 1 })}</h2><ContentRenderer value={answer.question_text}/><h3>{t('learnerAnswer')}</h3><ContentRenderer value={answer.given_answer || t('noAnswer')}/>{answer.correct_answer !== null && <p>{t('correctAnswer')}: {answer.correct_answer}</p>}<p>{answer.points === null ? t('missingGrade') : `${answer.points} / ${answer.max_points}`}</p>{answer.ai_suggested_score !== null && <div className="panel"><p>{t('aiSuggestion')}: {answer.ai_suggested_score} / {answer.max_points}</p>{answer.ai_suggested_feedback && <ContentRenderer value={answer.ai_suggested_feedback}/>}<Button variant="secondary" onClick={() => { form.setValue(`answers.${answer.response_id}.score`, String(answer.ai_suggested_score), { shouldDirty: true }); form.setValue(`answers.${answer.response_id}.feedback`, answer.ai_suggested_feedback || '', { shouldDirty: true }); }}>{t('useSuggestion')}</Button></div>}<SystemNotices notices={answer.system_notices}/>{rubrics.length > 0 && <RubricGrading rubrics={rubrics} maximum={answer.max_points} onDirtyChange={dirty => setRubricDirty(value => ({...value, [answer.response_id]: dirty}))} onApply={(score, breakdown, previous) => { const feedback = form.getValues(`answers.${answer.response_id}.feedback`); const next = previous && feedback.includes(previous) ? feedback.replace(previous, breakdown) : [feedback, breakdown].filter(Boolean).join('\n\n'); form.setValue(`answers.${answer.response_id}.score`, String(score), { shouldDirty: true }); form.setValue(`answers.${answer.response_id}.feedback`, next, { shouldDirty: true }); }}/>}<Field label={t('score')} error={form.formState.errors.answers?.[answer.response_id]?.score?.message}><Input type="number" min={0} max={answer.max_points} step={1} {...form.register(`answers.${answer.response_id}.score`)}/></Field><Field label={t('optionalFeedback')}><Textarea {...form.register(`answers.${answer.response_id}.feedback`)}/></Field>{finalizesQuestion(submission, answer.response_id) && <p>{t('lastQuestionWarning')}</p>}{rubricDirty[answer.response_id] && <p role="status">{t('rubricDraftChanged')}</p>}<Button disabled={blocked || hasRubricDraft} onClick={() => saveQuestion(answer.response_id, answer.max_points)}>{t('saveQuestion')}</Button>{dirtyFields.answers?.[answer.response_id] && <span className="muted">{t('common:dirty')}</span>}</Card>; })}
 <Card><h2>{t('saveTotal')}</h2><p>{t('totalWarning')}</p><Field label={t('totalPoints')} error={form.formState.errors.total?.message}><Input type="number" min={0} max={submission.total_points ?? 0} step={1} {...form.register('total')}/></Field><Field label={t('feedback')}><Textarea {...form.register('feedback')}/></Field><Button type="submit" busy={save.isPending} disabled={hasRubricDraft}>{t('saveTotal')}</Button></Card></fieldset></form><ConfirmDialog open={confirm !== null} onOpenChange={open => { if (!open) setConfirm(null); }} title={t(confirm?.kind === 'ai' ? 'acceptAll' : confirm?.kind === 'question' ? 'saveQuestion' : 'saveTotal')} description={t(confirm?.kind === 'ai' ? 'acceptAllDescription' : confirm?.kind === 'question' ? 'lastQuestionWarning' : 'totalWarning')} confirmLabel={t(confirm?.kind === 'ai' ? 'acceptAll' : 'save')} busy={save.isPending} onConfirm={() => { if (confirm && !blocked) { setChecked(false); const input = confirm; setConfirm(null); save.mutate(input); } }}/></div>;
}
