import { ApiError } from '@/lib/api';
import { validTimezone } from '@/lib/time';

export const record = (value: unknown): value is Record<string, unknown> => !!value && typeof value === 'object' && !Array.isArray(value);
const natural = (value: unknown): value is number => typeof value === 'number' && Number.isSafeInteger(value) && value >= 0;
const id = (value: unknown): value is number => natural(value) && value > 0;
const percent = (value: unknown): value is number => typeof value === 'number' && Number.isFinite(value) && value >= 0 && value <= 100;
const date = (value: unknown): value is string => typeof value === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(value);
export function invalid(mutation = false): never { throw new ApiError(200, 'invalid', mutation, mutation ? 'uncertain' : 'invalidResponse'); }
function list<T>(value: unknown, parse: (item: unknown) => T, identity: (item: T) => number): T[] { if (!Array.isArray(value)) return invalid(); const items = value.map(parse); if (new Set(items.map(identity)).size !== items.length) return invalid(); return items; }
export interface Stats { completed_lessons: number; total_study_time_minutes: number; unknown_duration_sessions: number; total_content: number; active_students?: number; assessments_created?: number; average_score?: number | null }
export function parseStats(value: unknown, teacher = false): Stats {
 if (!record(value) || !['completed_lessons','total_study_time_minutes','unknown_duration_sessions','total_content'].every(key => natural(value[key])) || teacher && (!natural(value.active_students) || !natural(value.assessments_created) || !(value.average_score === null || percent(value.average_score)))) return invalid();
 return value as unknown as Stats;
}
export interface Activity { id: number; text: string; time: string }
export function parseActivity(value: unknown): Activity[] { return list(value, item => { if (!record(item) || !natural(item.id) || typeof item.text !== 'string' || typeof item.time !== 'string') return invalid(); return item as unknown as Activity; }, item => item.id).filter(item => item.id !== 0); }
export interface Evidence { content_id: number; evidence_type: 'final_assessment' | 'legacy_or_self_report'; assessment_percent: number | null; self_confidence: number | null }
export function parseEvidence(value: unknown): Evidence[] { if (!record(value)) return invalid(); return list(value.items, item => { if (!record(item) || !id(item.content_id) || !['final_assessment','legacy_or_self_report'].includes(String(item.evidence_type)) || !(item.assessment_percent === null || percent(item.assessment_percent)) || item.evidence_type !== 'final_assessment' && item.assessment_percent !== null || !(item.self_confidence === null || id(item.self_confidence) && item.self_confidence <= 5)) return invalid(); return item as unknown as Evidence; }, item => item.content_id); }
export interface DueReview { mastery_node_id: number; content_id: number; content_title: string; content_type: string; days_overdue: number; evidence_type: 'final_assessment' | 'legacy_or_self_report' }
export function parseDue(value: unknown): DueReview[] { return list(value, item => { if (!record(item) || !id(item.mastery_node_id) || !id(item.content_id) || typeof item.content_title !== 'string' || typeof item.content_type !== 'string' || !natural(item.days_overdue) || !['final_assessment','legacy_or_self_report'].includes(String(item.evidence_type))) return invalid(); return item as unknown as DueReview; }, item => item.content_id); }
export interface Participation { xp: number; level: number; current_streak: number; longest_streak: number; badges_earned: number; last_activity_date: string | null; timezone: string; day_provenance: string }
export function parseParticipation(value: unknown): Participation { if (!record(value) || !['xp','current_streak','longest_streak','badges_earned'].every(key => natural(value[key])) || !id(value.level) || !(value.last_activity_date === null || date(value.last_activity_date)) || !validTimezone(value.timezone) || !['recorded','legacy_unknown'].includes(String(value.day_provenance))) return invalid(); return value as unknown as Participation; }
export interface LeaderboardEntry { rank: number; user_id: number; username: string; xp: number; level: number; metric_type: 'participation'; rank_scope: 'visible_users' }
export function parseLeaderboard(value: unknown, studentId?: number): LeaderboardEntry[] { return list(value, item => { if (!record(item) || !id(item.rank) || !id(item.user_id) || studentId !== undefined && item.user_id !== studentId || typeof item.username !== 'string' || !natural(item.xp) || !id(item.level) || item.metric_type !== 'participation' || item.rank_scope !== 'visible_users') return invalid(); return item as unknown as LeaderboardEntry; }, item => item.user_id); }
export interface BadgeData { id: number; name: string; description: string; xp_value: number; earned: boolean; earned_at: string | null }
export function parseBadges(value: unknown): BadgeData[] { return list(value, item => { if (!record(item) || !id(item.id) || typeof item.name !== 'string' || typeof item.description !== 'string' || !natural(item.xp_value) || typeof item.earned !== 'boolean' || !(item.earned_at === null || typeof item.earned_at === 'string')) return invalid(); return item as unknown as BadgeData; }, item => item.id); }
export const goalTypes = ['lessons','exercises','time'] as const;
export type GoalType = typeof goalTypes[number];
export interface GoalClock { timezone: string; day_timezone: string | null; day_provenance: 'recorded' | 'legacy_unknown' | 'current_policy'; mixed_day_policy: boolean }
export interface GoalProgress extends GoalClock { goal_type: GoalType | null; target: number; current: number; percentage: number; completed: boolean; has_goal: boolean }
export interface GoalReceipt extends GoalClock { id: number; goal_type: GoalType; target_value: number; current_value: number; completed: boolean; goal_date: string }
export interface GoalInput { goal_type: GoalType; target_value: number; save_as_default: boolean }
function clock(value: Record<string, unknown>): boolean { return validTimezone(value.timezone) && (value.day_timezone === null || validTimezone(value.day_timezone)) && ['recorded','legacy_unknown','current_policy'].includes(String(value.day_provenance)) && typeof value.mixed_day_policy === 'boolean' && (value.day_provenance !== 'recorded' || validTimezone(value.day_timezone)); }
export function parseGoal(value: unknown): GoalProgress { if (!record(value) || !clock(value) || typeof value.has_goal !== 'boolean' || !(value.goal_type === null || goalTypes.includes(value.goal_type as GoalType)) || !natural(value.target) || !natural(value.current) || !percent(value.percentage) || typeof value.completed !== 'boolean' || value.has_goal && (!id(value.target) || value.goal_type === null) || !value.has_goal && (value.goal_type !== null || value.current !== 0 || value.target !== 0 || value.completed || value.percentage !== 0)) return invalid(); return value as unknown as GoalProgress; }
export function confirmGoal(value: unknown, input: GoalInput): GoalReceipt { if (!record(value) || !clock(value) || !id(value.id) || value.goal_type !== input.goal_type || value.target_value !== input.target_value || !natural(value.current_value) || typeof value.completed !== 'boolean' || !date(value.goal_date)) return invalid(true); return value as unknown as GoalReceipt; }
export function goalMatches(goal: GoalProgress, input: GoalInput): boolean { return goal.has_goal && goal.goal_type === input.goal_type && goal.target === input.target_value; }
export function goalInput(type: string, target: string, saveAsDefault: boolean): GoalInput | null { const number = Number(target); return goalTypes.includes(type as GoalType) && /^\d+$/.test(target) && Number.isSafeInteger(number) && number > 0 && number <= 2_147_483_647 ? {goal_type: type as GoalType, target_value: number, save_as_default: saveAsDefault} : null; }
