import { useState } from 'react';
import { Link, useSearchParams } from 'react-router';
import { useTranslation } from 'react-i18next';
import { useAuth } from '@/app/AuthProvider';
import { formatTimestamp } from '@/lib/time';
import { Badge, Card, EmptyState, Field, PageHeader, Select } from '@/components/ui';
import { isMaterialList } from '@/features/courses/contracts';
import { parseTimezone } from '@/features/settings/contracts';
import { DailyGoal } from './DailyGoal';
import { parseActivity, parseBadges, parseDue, parseEvidence, parseLeaderboard, parseParticipation, parseStats } from './contracts';
import { ReadState, useRead, validated } from './shared';
const tabs=['summary','reviews','activity','goal','leaderboard'] as const;
export function ProgressPage() {
 const {t}=useTranslation('progress');const {user,scope}=useAuth();const [params]=useSearchParams();const selected=tabs.find(tab=>tab===params.get('tab')) || 'summary';
 if(!user)return null;
 return <div className="stack"><PageHeader title={t('title')} description={t('ownScope',{name:user.username})}/><nav className="cluster" aria-label={t('sections')}>{tabs.map(tab=><Link key={tab} to={`/progreso?tab=${tab}`} aria-current={selected===tab?'page':undefined}>{t(tab)}</Link>)}</nav><div key={`${scope}:${selected}`}>{selected==='summary'?<Summary/>:selected==='reviews'?<Reviews/>:selected==='activity'?<Activity/>:selected==='goal'?<DailyGoal/>:<Participation/>}</div></div>;
}
function Summary() {
 const {t,i18n}=useTranslation('progress');const {user}=useAuth();const teacher=user?.role==='teacher';
 const stats=useRead(['progress','stats'],'/api/dashboard/stats',value=>parseStats(value,teacher));
 const evidence=useRead(['progress','evidence'],'/api/mastery/evidence',parseEvidence);
 const final=evidence.data?.filter(item=>item.evidence_type==='final_assessment' && item.assessment_percent!==null);
 return <div className="stack"><Card><h2>{t('recordedWork')}</h2><ReadState query={stats}>{stats.data && <><dl className="grid"><div><dt>{t('completedSessions')}</dt><dd>{stats.data.completed_lessons}</dd></div><div><dt>{t('knownMinutes')}</dt><dd>{stats.data.total_study_time_minutes}</dd></div><div><dt>{t('unknownDurations')}</dt><dd>{stats.data.unknown_duration_sessions}</dd></div></dl><p className="muted">{t('elapsedHint')}</p>{teacher && <><h3>{t('teacherScope')}</h3><dl className="grid"><div><dt>{t('activeStudents')}</dt><dd>{stats.data.active_students}</dd></div><div><dt>{t('assessmentsCreated')}</dt><dd>{stats.data.assessments_created}</dd></div><div><dt>{t('authoredAverage')}</dt><dd>{stats.data.average_score==null?t('noFinalScore'):new Intl.NumberFormat(i18n.language,{style:'percent',maximumFractionDigits:1}).format(stats.data.average_score/100)}</dd></div><div><dt>{t('ownMaterials')}</dt><dd>{stats.data.total_content}</dd></div></dl></>}</>}</ReadState></Card>
 <Card><h2>{t('evidence')}</h2><p className="muted">{t('evidenceHint')}</p><ReadState query={evidence}>{final && <><p>{t('checkedContents',{count:final.length})}</p><p>{t('checkedAverage')}: {final.length?new Intl.NumberFormat(i18n.language,{style:'percent',maximumFractionDigits:1}).format(final.reduce((sum,item)=>sum+item.assessment_percent!,0)/final.length/100):t('noFinalScore')}</p><Link to="/progreso?tab=reviews">{t('reviewEvidence')}</Link></>}</ReadState></Card>
 <Card><h2>{t('history')}</h2><p>{t('historyHint')}</p><div className="cluster"><Link to="/cursos">{t('courseProgress')}</Link>{user?.role==='student' && <Link to="/evaluaciones/historial">{t('assessmentHistory')}</Link>}<Link to="/progreso?tab=activity">{t('activity')}</Link></div></Card></div>;
}
function Reviews() {
 const {t,i18n}=useTranslation('progress');const due=useRead(['progress','due'],'/api/mastery/due',parseDue);const evidence=useRead(['progress','evidence'],'/api/mastery/evidence',parseEvidence);const materials=useRead(['progress','material-titles'],'/api/content/',value=>validated(value,isMaterialList));
 const title=(id:number)=>materials.data?.find(item=>item.id===id)?.title || t('contentIdentity',{id});
 return <div className="stack"><Card><h2>{t('dueReviews')}</h2><p>{t('scheduleHint')}</p><ReadState query={due}>{due.data && (due.data.length?<ul className="list">{due.data.map(item=><li key={item.content_id}><Link to={`/materiales/${item.content_id}?mode=review`}>{item.content_title}</Link><p>{t('overdue',{days:item.days_overdue})}</p><Badge>{t(item.evidence_type)}</Badge></li>)}</ul>:<EmptyState title={t('noDue')}/>)}</ReadState></Card><Card><h2>{t('evidence')}</h2><p>{t('evidenceHint')}</p><ReadState query={evidence}>{evidence.data && (evidence.data.length?<ul className="list">{evidence.data.map(item=><li key={item.content_id}><h3><Link to={`/materiales/${item.content_id}`}>{title(item.content_id)}</Link></h3><Badge>{t(item.evidence_type)}</Badge><p>{t('finalScore')}: {item.evidence_type==='final_assessment' && item.assessment_percent!==null?new Intl.NumberFormat(i18n.language,{style:'percent',maximumFractionDigits:1}).format(item.assessment_percent/100):t('noFinalScore')}</p><p>{t('confidence')}: {item.self_confidence===null?t('notRecorded'):`${item.self_confidence}/5`}</p></li>)}</ul>:<EmptyState title={t('noEvidence')}/>)}</ReadState>{!!materials.error && <p className="muted">{t('titlesUnavailable')}</p>}</Card></div>;
}
function Activity() {
 const {t}=useTranslation('progress');const activity=useRead(['progress','activity'],'/api/dashboard/activity',parseActivity);
 return <Card><h2>{t('activity')}</h2><p className="muted">{t('activityScope')}</p><ReadState query={activity}>{activity.data && (activity.data.length?<ul className="list">{activity.data.map(item=><li key={item.id}><p>{item.text}</p><p className="muted">{item.time}</p></li>)}</ul>:<EmptyState title={t('noActivity')}/>)}</ReadState></Card>;
}
function Participation() {
 const {t,i18n}=useTranslation('progress');const {user}=useAuth();const [period,setPeriod]=useState('weekly');
 const profile=useRead(['progress','participation'],'/api/gamification/profile',parseParticipation);const badges=useRead(['progress','badges'],'/api/gamification/badges',parseBadges);const policy=useRead(['settings','timezone'],'/api/settings/timezone',parseTimezone);const board=useRead(['progress','leaderboard',period],`/api/gamification/leaderboard?period=${period}`,value=>parseLeaderboard(value,user?.role==='student'?user.id:undefined));
 return <div className="stack"><Card><h2>{t('participation')}</h2><p>{t('participationHint')}</p><ReadState query={profile}>{profile.data && <><dl className="grid"><div><dt>{t('xp')}</dt><dd>{profile.data.xp}</dd></div><div><dt>{t('level')}</dt><dd>{profile.data.level}</dd></div><div><dt>{t('streak')}</dt><dd>{profile.data.current_streak}</dd></div><div><dt>{t('longestStreak')}</dt><dd>{profile.data.longest_streak}</dd></div></dl><p>{t('lastActivityDate')}: {profile.data.last_activity_date || t('notRecorded')}{profile.data.last_activity_date && profile.data.day_provenance==='legacy_unknown'?` (${t('unknownTime')})`:''}</p>{profile.data.day_provenance==='legacy_unknown' && <p className="muted">{t('legacyDays')}</p>}<p className="muted">{t('civilDayHint',{zone:profile.data.timezone})}</p></>}</ReadState></Card>
 <Card><h2>{t('badges')}</h2><p>{t('ownBadges')}</p><ReadState query={badges}>{badges.data && (badges.data.length?<ul className="list">{badges.data.map(badge=><li key={badge.id}><h3>{badge.name}</h3><Badge tone={badge.earned?'success':'neutral'}>{t(badge.earned?'earned':'notEarned')}</Badge><p>{badge.description}</p><p>{t('badgeXP',{value:badge.xp_value})}</p>{badge.earned && <p>{formatTimestamp(badge.earned_at,{locale:i18n.language,timezone:policy.data?.timezone,unknownLabel:t('unknownTime')})}</p>}</li>)}</ul>:<EmptyState title={t('noBadges')}/>)}</ReadState>{!!policy.error && <p className="muted">{t('timezoneFallback')}</p>}</Card>
 <Card><h2>{t('leaderboard')}</h2><p>{t(`scope_${user?.role}`)}</p><p className="muted">{t('periodFallback')}</p><Field label={t('period')}><Select value={period} onChange={event=>setPeriod(event.target.value)}>{['weekly','monthly','all_time'].map(value=><option key={value} value={value}>{t(value)}</option>)}</Select></Field><ReadState query={board}>{board.data && (board.data.length?<div className="table-wrap"><table><caption>{t(`scope_${user?.role}`)}</caption><thead><tr><th scope="col">{t('rank')}</th><th scope="col">{t('account')}</th><th scope="col">{t('xp')}</th><th scope="col">{t('level')}</th></tr></thead><tbody>{board.data.map(item=><tr key={item.user_id}><td>{item.rank}</td><td>{item.username}</td><td>{item.xp}</td><td>{item.level}</td></tr>)}</tbody></table></div>:<EmptyState title={t('noParticipation')}/>)}</ReadState></Card></div>;
}
