"""Add Phase 1-3 models

Revision ID: 7924cdebd9c6
Revises: 
Create Date: 2025-11-22 15:43:39.912936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '7924cdebd9c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon_path', sa.String(length=255), nullable=True),
    sa.Column('xp_value', sa.Integer(), nullable=False),
    sa.Column('criteria_type', sa.String(length=50), nullable=False),
    sa.Column('criteria_value', sqlite.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('daily_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_date', sa.Date(), nullable=False),
    sa.Column('goal_type', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_goal_date', 'daily_goals', ['user_id', 'goal_date'], unique=True)
    op.create_index(op.f('ix_daily_goals_goal_date'), 'daily_goals', ['goal_date'], unique=False)
    op.create_index(op.f('ix_daily_goals_user_id'), 'daily_goals', ['user_id'], unique=False)
    op.create_table('leaderboard_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_period_rank', 'leaderboard_entries', ['period', 'rank'], unique=False)
    op.create_index('idx_user_period', 'leaderboard_entries', ['user_id', 'period'], unique=True)
    op.create_index(op.f('ix_leaderboard_entries_period'), 'leaderboard_entries', ['period'], unique=False)
    op.create_index(op.f('ix_leaderboard_entries_rank'), 'leaderboard_entries', ['rank'], unique=False)
    op.create_index(op.f('ix_leaderboard_entries_user_id'), 'leaderboard_entries', ['user_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'badge_id')
    )
    op.create_index(op.f('ix_user_badges_badge_id'), 'user_badges', ['badge_id'], unique=False)
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text_selection_start', sa.Integer(), nullable=True),
    sa.Column('text_selection_end', sa.Integer(), nullable=True),
    sa.Column('annotation_text', sa.Text(), nullable=False),
    sa.Column('annotation_type', sa.String(length=50), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_content_id'), 'annotations', ['content_id'], unique=False)
    op.create_index(op.f('ix_annotations_user_id'), 'annotations', ['user_id'], unique=False)
    op.create_table('mastery_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('mastery_level', sa.Integer(), nullable=False),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.Column('next_review_due', sa.DateTime(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_student_content', 'mastery_nodes', ['student_id', 'content_id'], unique=True)
    op.create_index(op.f('ix_mastery_nodes_content_id'), 'mastery_nodes', ['content_id'], unique=False)
    op.create_index(op.f('ix_mastery_nodes_next_review_due'), 'mastery_nodes', ['next_review_due'], unique=False)
    op.create_index(op.f('ix_mastery_nodes_student_id'), 'mastery_nodes', ['student_id'], unique=False)
    op.create_table('help_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('study_plan_id', sa.Integer(), nullable=True),
    sa.Column('request_text', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['study_plan_id'], ['study_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_help_requests_content_id'), 'help_requests', ['content_id'], unique=False)
    op.create_index(op.f('ix_help_requests_created_at'), 'help_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_help_requests_question_id'), 'help_requests', ['question_id'], unique=False)
    op.create_index(op.f('ix_help_requests_resolved_by_id'), 'help_requests', ['resolved_by_id'], unique=False)
    op.create_index(op.f('ix_help_requests_status'), 'help_requests', ['status'], unique=False)
    op.create_index(op.f('ix_help_requests_student_id'), 'help_requests', ['student_id'], unique=False)
    op.create_index(op.f('ix_help_requests_study_plan_id'), 'help_requests', ['study_plan_id'], unique=False)
    op.add_column('users', sa.Column('xp', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('current_streak', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('longest_streak', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('last_activity_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_activity_date')
    op.drop_column('users', 'longest_streak')
    op.drop_column('users', 'current_streak')
    op.drop_column('users', 'level')
    op.drop_column('users', 'xp')
    op.drop_index(op.f('ix_help_requests_study_plan_id'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_student_id'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_status'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_resolved_by_id'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_question_id'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_created_at'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_content_id'), table_name='help_requests')
    op.drop_table('help_requests')
    op.drop_index(op.f('ix_mastery_nodes_student_id'), table_name='mastery_nodes')
    op.drop_index(op.f('ix_mastery_nodes_next_review_due'), table_name='mastery_nodes')
    op.drop_index(op.f('ix_mastery_nodes_content_id'), table_name='mastery_nodes')
    op.drop_index('idx_student_content', table_name='mastery_nodes')
    op.drop_table('mastery_nodes')
    op.drop_index(op.f('ix_annotations_user_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_content_id'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_badge_id'), table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_leaderboard_entries_user_id'), table_name='leaderboard_entries')
    op.drop_index(op.f('ix_leaderboard_entries_rank'), table_name='leaderboard_entries')
    op.drop_index(op.f('ix_leaderboard_entries_period'), table_name='leaderboard_entries')
    op.drop_index('idx_user_period', table_name='leaderboard_entries')
    op.drop_index('idx_period_rank', table_name='leaderboard_entries')
    op.drop_table('leaderboard_entries')
    op.drop_index(op.f('ix_daily_goals_user_id'), table_name='daily_goals')
    op.drop_index(op.f('ix_daily_goals_goal_date'), table_name='daily_goals')
    op.drop_index('idx_user_goal_date', table_name='daily_goals')
    op.drop_table('daily_goals')
    op.drop_table('badges')
    # ### end Alembic commands ###
