/* Provider repair uses fake HTTP only; no credential or inference calls. */
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {JSDOM,VirtualConsole}=require('jsdom');
const root=path.resolve(__dirname,'../../src/web');const read=p=>fs.readFileSync(path.join(root,p),'utf8');const reply=(data,status=200)=>({ok:status>=200&&status<300,status,json:async()=>data});
async function fixture(){const dom=new JSDOM(read('dashboard.html'),{url:'http://localhost/dashboard.html',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:new VirtualConsole()});await new Promise(r=>setImmediate(r));const w=dom.window;w.AuthService={getToken:()=> 'synthetic',getUser:()=>({id:7}),getRole:()=> 'teacher'};w.I18n={t:k=>k};w.applyTheme=()=>{};w.eval(read('static/js/learning-client.js'));const code=read('static/js/dashboard.js');w.eval(code.slice(code.indexOf('const supportedAIProviders'),code.indexOf('function setSettingsTab'))+code.slice(code.indexOf('function buildAIConfigPayload'),code.indexOf('// --- AI SETTINGS HELPER FUNCTIONS ---'))+code.slice(code.indexOf('window.onProviderChange ='),code.indexOf('/**\n * Test AI connection')));return{dom,w};}
test('legacy unsupported config shows explicit repair choice; only supported providers can be saved',async()=>{
 const {dom,w}=await fixture();const posts=[];w.fetch=async(url,options={})=>{if(options.method==='POST'){const data=JSON.parse(options.body);posts.push(data);return reply({...data,has_api_key:false});}return url.endsWith('/ai')?reply({detail:'Unsupported legacy provider'},409):reply({language:'es',theme:'auto'});};
 await w.loadSettings();assert.equal(w.document.querySelector('option[value=anthropic]'),null);assert.equal(w.document.getElementById('ai-preprocessing'),null);assert.equal(w.document.getElementById('ai-provider').value,'');assert.match(w.document.getElementById('ai-config-status').textContent,/has not changed/);assert.equal(w.document.getElementById('save-ai-config').disabled,true);
 await w.saveAISettings();assert.equal(posts.length,0);w.document.getElementById('ai-provider').value='ollama';w.document.getElementById('ai-model').value='synthetic-local';w.onProviderChange();await w.saveAISettings();assert.equal(posts.length,1);assert.equal('enable_preprocessing' in posts[0],false);assert.equal('preprocessing_model' in posts[0],false);assert.ok(w.document.getElementById('ai-test-result').classList.contains('alert-success'));dom.window.close();
});
for(const kind of ['http500','malformed'])test('AI save '+kind+' retains entered values and never reports success',async()=>{
 const {dom,w}=await fixture();w.fetch=async(url,options={})=>options.method?reply(kind==='malformed'?{}:{detail:'Save rejected'},kind==='malformed'?200:500):reply(url.endsWith('/ai')?{provider:'ollama',model:'before',has_api_key:false}:{language:'en',theme:'auto'});await w.loadSettings();w.document.getElementById('ai-model').value='keep-model';w.document.getElementById('ai-key').value='synthetic-only-key';await w.saveAISettings();assert.equal(w.document.getElementById('ai-model').value,'keep-model');assert.equal(w.document.getElementById('ai-key').value,'synthetic-only-key');assert.ok(w.document.getElementById('ai-test-result').classList.contains('alert-danger'));assert.equal(w.document.getElementById('save-ai-config').disabled,false);dom.window.close();
});
test('failed config load requires a successful reload before it can overwrite saved settings',async()=>{
 const {dom,w}=await fixture();let posts=0;w.fetch=async(url,options={})=>{if(options.method)posts++;return reply({detail:'Unavailable'},500);};await w.loadSettings();w.document.getElementById('ai-provider').value='openai';w.onProviderChange();await w.saveAISettings();assert.equal(posts,0);assert.equal(w.document.getElementById('save-ai-config').disabled,true);dom.window.close();
});
