import { toolLocales } from './tool-locales';
import { helpLocales } from './help-locales';
export const locales = {
 en: {
  ...toolLocales.en, ...helpLocales.en,
  sourceCounts: 'Source context: {{supplied}}/{{total}} characters.',
  title: 'Study', readingSize: 'Reading text size', readingSizeValue: '{{size}} px', elapsed: 'Time since session start', elapsedHint: 'Includes time away from this session; it is not a progress or mastery measure.', back: 'Back to course', backCourses: 'My courses', unavailable: 'This study session is unavailable', invalidLink: 'Open the material from your course to start or continue studying.', materialPreview: 'Read the material. Start a study session when you are ready to take notes or record completion.',
  start: 'Start studying', continue: 'Continue session', restore: 'Restore previous session', restart: 'Start fresh', restartTitle: 'Start a fresh session?', restartDescription: 'Your previous notes stay in session history. Any active session for this material and course will close without completing it. A fresh session captures the current material.',
  history: 'Previous sessions', noHistory: 'No previous sessions for this material and course.', sessionNumber: 'Session {{id}}', active: 'Active', completed: 'Completed', closed: 'Closed without completion', failed: 'Interrupted', dateUnknown: '{{date}} (timezone unknown)', dateUtc: 'Dates are shown in UTC.',
  snapshot: 'Saved lesson version', snapshotDescription: 'This session uses the material captured when it started. Changes to the current material do not replace this version.', missingSnapshot: 'This older session has no saved material version. Your notes are preserved. Start a fresh session to capture the current material.', sourcePartial: 'Partial source: some material was not included.', sourceReceipt: 'Source information describes text supplied to the model; it does not verify the answer.',
  openAssessment: 'Open assessment preview', assessmentPreview: 'Reading this preview does not start an assessment attempt.', needsReview: 'This material needs teacher review before it can be used.', startPractice: 'Start a study session to answer this practice and keep a recovery draft.',
  tools: 'Study tools', index: 'Course index', notes: 'Notes and annotations', helpTab: 'Help', closeTool: 'Back to reading', notesLabel: 'My session notes', notesHint: 'Notes belong to this account, material and session. Save to the server before leaving.', saveNotes: 'Save notes', localNotes: 'Recovery draft saved on this device. Server save is still needed.', storageFailed: 'A recovery draft could not be saved on this device. Keep this page open and save to the server.', savedNotes: 'Notes saved to the server.', notesDirty: 'Notes have unsaved changes.', notesSaving: 'Saving notes…', noteUncertain: 'The server save is unconfirmed. Your text is kept. Retry to check and save.',
  draftRemoveFailed: 'The server notes are preserved, but the device draft could not be removed. Check browser storage before leaving.', draftFound: 'A recovery draft was found', draftDescription: 'The draft belongs to this account and session. Restore it, or keep the server notes and discard it.', restoreDraft: 'Restore draft', discardDraft: 'Discard draft', leaveDraft: 'Leave and keep draft',
  nextMaterial: 'Next material', pause: 'Save and pause', previous: 'Previous material', complete: 'Complete session', completeNext: 'Complete and continue', completeReturn: 'Complete and return', completing: 'Saving completion…', completionPending: 'Session completion was confirmed. Course progress is still pending. Retry completion to finish saving it.', completionUncertain: 'Completion is unconfirmed. Your original notes are kept for the retry. No progress is marked complete yet.', completionSaved: 'Session and course progress were saved.', sessionSaved: 'Session completion was saved.', completeTitle: 'Complete this session?', completeDescription: 'This records participation and saves your notes. It does not grade your answers or prove mastery.', confidence: 'Self-rated confidence (optional)', confidenceHint: 'This is separate from assessed mastery.', noRating: 'Do not add a rating', confidence1: '1 · Very low', confidence2: '2 · Low', confidence3: '3 · Moderate', confidence4: '4 · High', confidence5: '5 · Very high',
  progress: '{{completed}} of {{total}} materials completed', current: 'Current material', done: 'Completed', notComplete: 'Not completed', noPlan: 'This material is not in a selected course.', serverNeeded: 'Prepared lessons work without a teacher or AI provider online while the local application server is running. A stopped server cannot save notes or progress.', toolsUnavailable: 'Start or restore a session to use its notes and contextual help.', readOnlySession: 'This session is no longer active. Restore it before editing notes.', duration: '{{minutes}} minutes recorded', durationUnknown: 'Duration unknown',
  lesson: { objectives: 'Learning objectives', summary: 'Summary', vocabulary: 'Key terms', key_concepts: 'Key concepts', discussion_questions: 'Discussion questions', worked_example: 'Worked example', independent_attempt: 'Independent attempt', feedback: 'Feedback', delayed_review: 'Later review', prerequisite_check: 'Before you start' },
 },
 es: {
  ...toolLocales.es, ...helpLocales.es,
  sourceCounts: 'Contexto de la fuente: {{supplied}}/{{total}} caracteres.',
  title: 'Estudiar', readingSize: 'Tamaño del texto de lectura', readingSizeValue: '{{size}} px', elapsed: 'Tiempo desde el inicio de la sesión', elapsedHint: 'Incluye el tiempo fuera de esta sesión; no mide el progreso ni el dominio.', back: 'Volver al curso', backCourses: 'Mis cursos', unavailable: 'Esta sesión de estudio no está disponible', invalidLink: 'Abre el material desde tu curso para empezar o continuar estudiando.', materialPreview: 'Lee el material. Inicia una sesión cuando quieras tomar notas o registrar que has terminado.',
  start: 'Empezar a estudiar', continue: 'Continuar sesión', restore: 'Restaurar sesión anterior', restart: 'Empezar de nuevo', restartTitle: '¿Empezar una sesión nueva?', restartDescription: 'Tus notas anteriores se conservan en el historial. La sesión activa de este material y curso se cerrará sin completarse. La nueva sesión conservará la versión actual del material.',
  history: 'Sesiones anteriores', noHistory: 'No hay sesiones anteriores de este material y curso.', sessionNumber: 'Sesión {{id}}', active: 'Activa', completed: 'Completada', closed: 'Cerrada sin completar', failed: 'Interrumpida', dateUnknown: '{{date}} (zona horaria desconocida)', dateUtc: 'Las fechas se muestran en UTC.',
  snapshot: 'Versión guardada de la lección', snapshotDescription: 'La sesión usa el material conservado al iniciarla. Los cambios posteriores no sustituyen esta versión.', missingSnapshot: 'Esta sesión antigua no tiene una versión guardada del material. Tus notas se conservan. Inicia una sesión nueva para guardar la versión actual.', sourcePartial: 'Fuente parcial: no se incluyó todo el material.', sourceReceipt: 'La información de la fuente describe el texto enviado al modelo; no verifica la respuesta.',
  openAssessment: 'Abrir vista previa de evaluación', assessmentPreview: 'Leer esta vista previa no inicia ningún intento de evaluación.', needsReview: 'Este material necesita revisión del docente antes de utilizarlo.', startPractice: 'Inicia una sesión para responder a esta práctica y conservar un borrador de recuperación.',
  tools: 'Herramientas de estudio', index: 'Índice del curso', notes: 'Notas y anotaciones', helpTab: 'Ayuda', closeTool: 'Volver a la lectura', notesLabel: 'Mis notas de la sesión', notesHint: 'Las notas pertenecen a esta cuenta, material y sesión. Guárdalas en el servidor antes de salir.', saveNotes: 'Guardar notas', localNotes: 'Borrador de recuperación guardado en este dispositivo. Falta guardar en el servidor.', storageFailed: 'No se pudo guardar un borrador en este dispositivo. Mantén esta página abierta y guarda en el servidor.', savedNotes: 'Notas guardadas en el servidor.', notesDirty: 'Hay cambios sin guardar en las notas.', notesSaving: 'Guardando notas…', noteUncertain: 'El guardado en el servidor no está confirmado. Tu texto se conserva. Reintenta para comprobarlo y guardarlo.',
  draftRemoveFailed: 'Las notas del servidor se conservan, pero no se pudo eliminar el borrador del dispositivo. Comprueba el almacenamiento antes de salir.', draftFound: 'Se encontró un borrador de recuperación', draftDescription: 'El borrador pertenece a esta cuenta y sesión. Restáuralo o conserva las notas del servidor y descártalo.', restoreDraft: 'Restaurar borrador', discardDraft: 'Descartar borrador', leaveDraft: 'Salir y conservar borrador',
  nextMaterial: 'Material siguiente', pause: 'Guardar y pausar', previous: 'Material anterior', complete: 'Completar sesión', completeNext: 'Completar y continuar', completeReturn: 'Completar y volver', completing: 'Guardando finalización…', completionPending: 'La finalización de la sesión está confirmada. El progreso del curso sigue pendiente. Reintenta completar para terminar el guardado.', completionUncertain: 'La finalización no está confirmada. Tus notas originales se conservan para el reintento. Todavía no se marca el progreso como completado.', completionSaved: 'Sesión y progreso del curso guardados.', sessionSaved: 'Finalización de la sesión guardada.', completeTitle: '¿Completar esta sesión?', completeDescription: 'Esto registra la participación y guarda tus notas. No califica tus respuestas ni demuestra dominio.', confidence: 'Confianza que sientes (opcional)', confidenceHint: 'Se guarda por separado del dominio evaluado.', noRating: 'No añadir valoración', confidence1: '1 · Muy baja', confidence2: '2 · Baja', confidence3: '3 · Moderada', confidence4: '4 · Alta', confidence5: '5 · Muy alta',
  progress: '{{completed}} de {{total}} materiales completados', current: 'Material actual', done: 'Completado', notComplete: 'Sin completar', noPlan: 'Este material no tiene un curso seleccionado.', serverNeeded: 'Puedes estudiar las lecciones preparadas sin docente ni proveedor de IA conectado mientras el servidor local esté funcionando. Un servidor detenido no puede guardar notas ni progreso.', toolsUnavailable: 'Inicia o restaura una sesión para usar sus notas y ayuda contextual.', readOnlySession: 'Esta sesión ya no está activa. Restáurala antes de editar las notas.', duration: '{{minutes}} minutos registrados', durationUnknown: 'Duración desconocida',
  lesson: { objectives: 'Objetivos de aprendizaje', summary: 'Resumen', vocabulary: 'Términos clave', key_concepts: 'Conceptos clave', discussion_questions: 'Preguntas para reflexionar', worked_example: 'Ejemplo resuelto', independent_attempt: 'Intento independiente', feedback: 'Comentarios', delayed_review: 'Repaso posterior', prerequisite_check: 'Antes de empezar' },
 },
};
