import { useCallback, useEffect, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router';
import { useForm, useWatch } from 'react-hook-form';
import { useTranslation } from 'react-i18next';
import { useAuth } from '@/app/AuthProvider';
import { useDirtyGuard } from '@/app/DirtyGuard';
import { ApiError } from '@/lib/api';
import { DraftAdapter } from '@/lib/drafts';
import { positiveId } from '@/lib/ids';
import { useInvalidate, useOperation, useResource } from '@/lib/query';
import { isCourse, isCourseTree, isWorkflow } from '@/features/courses/contracts';
import { Badge, Button, Card, ConfirmDialog, EmptyState, ErrorState, Field, Input, PageHeader, Select, Textarea } from '@/components/ui';
import { legacyDesignerSetup } from './legacy-designer';
import { CourseChoice } from './CourseChoice';
import { AssessmentProposalEditor } from '@/features/assessments/AssessmentEditor';
import { MaterialComposer, StaffRequired, useContinuation } from './MaterialEditor';
import { GenerationItems, GenerationJobs } from './GenerationJobs';
import { generationDefaults, generationRequest, isGenerationDraft, isPackageFor, isSourceDocument, isSourceReceipt, materialForm, materialPayload, outlineFrom, outlinePayload, record, responseError, sourceInput, validationError, type GenerationDraft, type GenerationForm, type MaterialKind, type Outline, type PackageResult, type SourceDocument, type SourceInput } from './contracts';

type Preview = {id:number;kind:MaterialKind;data:Record<string,unknown>;title:string;sourceName?:string};
type AssessmentPreview = {id:number;value:Record<string,unknown>};
type GenerateInput = {form:GenerationForm;request:ReturnType<typeof generationRequest>;source:SourceDocument|null};
type GenerateResult = {kind:'material';preview:Preview}|{kind:'outline';outline:Outline}|{kind:'package';package:PackageResult};
export function GenerationPage() {const {user,scope}=useAuth(),{t}=useTranslation('authoring'),[search]=useSearchParams(),planId=positiveId(search.get('plan_id'));if(user?.role==='student')return <StaffRequired/>;if(search.has('plan_id')&&!planId)return <EmptyState title={t('unavailable')}/>;return <GenerationWorkspace key={`${scope}:${planId}`} initialPlan={planId}/>;}
function PreviewEditor({preview,onDirty,onSaved}:{preview:Preview;onDirty:(id:number,value:boolean)=>void;onSaved:(id:number)=>void}) {const dirty=useCallback((value:boolean)=>onDirty(preview.id,value),[onDirty,preview.id]);return <MaterialComposer proposal={preview} onDirty={dirty} onSaved={onSaved}/>;}
function AssessmentPreviewEditor({preview,onDirty,onSaved}:{preview:AssessmentPreview;onDirty:(id:number,value:boolean)=>void;onSaved:(id:number)=>void}) {const dirty=useCallback((value:boolean)=>onDirty(preview.id,value),[onDirty,preview.id]);return <AssessmentProposalEditor value={preview.value} onDirtyChange={dirty} onSaved={onSaved}/>;}
function GenerationWorkspace({initialPlan}:{initialPlan:number|null}) {
 const {api,user,status}=useAuth(),{t}=useTranslation('authoring'),current=useContinuation(),invalidate=useInvalidate();
 const form=useForm<GenerationForm>({defaultValues:{...generationDefaults,planId:initialPlan?String(initialPlan):''}}),values=useWatch({control:form.control}) as GenerationForm,planId=positiveId(values.planId);
 const tree=useResource<unknown>(['courses',planId,'tree'],planId?`/api/study-plans/${planId}/tree`:null),workflow=useResource<unknown>(['courses',planId,'workflow'],planId?`/api/study-plans/${planId}/workflow`:null),source=useResource<unknown>(['authoring','source',planId],planId?`/api/study-plans/${planId}/source`:null);
 const savedSource=record(source.data)&&isSourceDocument(source.data.source)?source.data.source:null;
 const sourceReady=!planId||(record(source.data)&&(source.data.source===null||isSourceDocument(source.data.source)));
 const [assessmentPreviews,setAssessmentPreviews]=useState<AssessmentPreview[]>([]);
 const [previews,setPreviews]=useState<Preview[]>([]),[previewDirty,setPreviewDirty]=useState<Record<number,boolean>>({}),[packages,setPackages]=useState<{id:number;value:PackageResult;planId:number|null}[]>([]),[outline,setOutline]=useState<Outline|null>(null),[outlineProposal,setOutlineProposal]=useState<{outline:Outline;source:SourceDocument|null;sourcePlanId:number|null}|null>(null),[outlineSource,setOutlineSource]=useState<SourceDocument|null>(null),[outlineSourcePlanId,setOutlineSourcePlanId]=useState<number|null>(null),[sourceCopied,setSourceCopied]=useState(false),[destinationSource,setDestinationSource]=useState<SourceDocument|null|undefined>(undefined),[createdPlanId,setCreatedPlanId]=useState<number|null>(null),[last,setLast]=useState<GenerateInput|null>(null),[decision,setDecision]=useState<'outline'|'retry'|'source'|'recovered-source'|null>(null),[notice,setNotice]=useState(''),[localState,setLocalState]=useState('');
 const [drafts]=useState(()=>{try{return new DraftAdapter(user!.id);}catch{return null;}}),[recovery,setRecovery]=useState<GenerationDraft|null>(()=>drafts?.read('course','generation','active',isGenerationDraft)||null);
 const [legacyDraft,setLegacyDraft]=useState(()=>drafts?.read('course','designer','active',record)||null);
 const legacySetup=legacyDraft?legacyDesignerSetup(legacyDraft):null;
 const legacyPlan=typeof legacyDraft?.createdStudyPlanId==='number'?positiveId(legacyDraft.createdStudyPlanId):null;
 const legacyCourse=useResource<unknown>(['courses',legacyPlan,'tree'],legacyPlan?`/api/study-plans/${legacyPlan}/tree`:null);
 const legacyReadable=!!legacyDraft&&(legacyDraft.createdStudyPlanId==null||!!legacyPlan&&!legacyCourse.error&&isCourseTree(legacyCourse.data)&&legacyCourse.data.id===legacyPlan&&(user?.role==='admin'||legacyCourse.data.creator_id===user?.id));
 const [recoveredSource,setRecoveredSource]=useState<SourceInput|null>(null),[hasRestored,setHasRestored]=useState(false);
 const serial=useRef(0),controller=useRef<AbortController|null>(null),stop=useRef(false);
 const onDirty=useCallback((id:number,value:boolean)=>setPreviewDirty(previous=>previous[id]===value?previous:{...previous,[id]:value}),[]);
 const onSaved=useCallback(()=>setNotice(t('itemSaved')), [t]);
 const generate=useOperation<GenerateInput,GenerateResult>(async input=>{
  controller.current=new AbortController();
  if(input.form.mode==='package'&&input.form.autoSave){const liveSource=await api.get<unknown>(`/api/study-plans/${positiveId(input.form.planId)}/source`);if(!record(liveSource)||!(liveSource.source===null||isSourceDocument(liveSource.source)))throw responseError();if((liveSource.source?.document_id||null)!==(input.source?.document_id||null))throw new ApiError(409);if(!current())throw new ApiError(0,'stale',false,'cancelled');}
  const result=await api.post<unknown>(input.request.path,input.request.body,{signal:controller.current.signal});
  if(input.form.mode==='plan'||input.form.mode==='outline'){const parsed=outlineFrom(result,input.form.mode);if(!parsed)throw responseError();return {kind:'outline',outline:parsed};}
  if(input.form.mode==='package'){if(!isPackageFor(result,input.form))throw responseError(input.form.autoSave);return {kind:'package',package:result};}
  if(!record(result))throw responseError();
  const candidate=materialForm(input.form.mode,result,input.form.topic);if(input.form.mode==='lesson')materialPayload(candidate,result);else if(!candidate.question.trim()||(candidate.exerciseType==='multiple_choice'&&!candidate.options.length))throw responseError();
  return {kind:'material',preview:{id:++serial.current,kind:input.form.mode,data:result,title:input.form.topic,sourceName:input.source?.filename}};
 },async(result,input)=>{
  if(!current())return;
  if(result.kind==='outline'){setOutlineProposal({outline:result.outline,source:input.form.mode==='plan'?null:input.source,sourcePlanId:input.form.mode==='plan'?null:positiveId(input.form.planId)});setNotice(t('proposalReady'));}
  if(result.kind==='material'){setPreviews(previous=>[...previous,result.preview]);setNotice(t('proposalReady'));}
  if(result.kind==='package'){
   setPackages(previous=>[...previous,{id:++serial.current,value:result.package,planId:input.form.autoSave?positiveId(input.form.planId):null}]);
   if(!input.form.autoSave){const next:Preview[]=[];if(result.package.lesson)next.push({id:++serial.current,kind:'lesson',data:result.package.lesson,title:String(result.package.lesson.title||input.form.topic),sourceName:input.source?.filename});for(const exercise of result.package.exercises||[])next.push({id:++serial.current,kind:'exercise',data:exercise,title:String(exercise.title||input.form.topic),sourceName:input.source?.filename});setPreviews(previous=>[...previous,...next]);if(result.package.assessment){const preview={id:++serial.current,value:result.package.assessment};setAssessmentPreviews(previous=>[...previous,preview]);}}
   setNotice(t(result.package.success?'generationDone':'partial'));
   if(input.form.autoSave){await invalidate(['authoring']);await invalidate(['courses']);}
  }
 });
 const saveOutline=useOperation(async()=>{if(!outline||createdPlanId)throw validationError();const payload=outlinePayload(outline),result=await api.post<unknown>('/api/study-plans/',payload);if(!isCourse(result)||result.creator_id!==user?.id||result.title!==payload.title||result.is_public)throw responseError(true);return result;},async result=>{if(!current())return;setCreatedPlanId(result.id);setNotice(t('outlineSaved'));await invalidate(['courses']);});
 const checkSource=useOperation(async()=>{
  if(!createdPlanId||!outlineSource)throw validationError();
  const result=await api.get<unknown>(`/api/study-plans/${createdPlanId}/source`);
  if(!record(result)||!(result.source===null||isSourceDocument(result.source)))throw responseError();
  return result.source;
 },result=>{if(!current())return;if(result?.document_id===outlineSource?.document_id){setSourceCopied(true);return;}setDestinationSource(result);setDecision('source');});
 const copySource=useOperation(async()=>{
  if(!createdPlanId||!outlineSource||destinationSource===undefined)throw validationError();
  const latest=await api.get<unknown>(`/api/study-plans/${createdPlanId}/source`);
  if(!record(latest)||!(latest.source===null||isSourceDocument(latest.source)))throw responseError();
  if(latest.source?.document_id===outlineSource.document_id)return;
  if((latest.source?.metadata_revision||latest.source?.document_id||null)!==(destinationSource?.metadata_revision||destinationSource?.document_id||null))throw new ApiError(409);
  if(!current())throw new ApiError(0,'stale',false,'cancelled');
  const result=await api.put<unknown>(`/api/study-plans/${createdPlanId}/source`,sourceInput(outlineSource));
  if(!isSourceReceipt(result,outlineSource.extracted_text))throw responseError(true);
 },async()=>{if(!current())return;setSourceCopied(true);await invalidate(['authoring','source',createdPlanId]);await invalidate(['courses']);});
 const batch=useOperation(async()=>{
  if(!outline||!createdPlanId||recoveredSource)throw validationError();
  stop.current=false;const frozen=structuredClone(outline),config=form.getValues(),results:PackageResult[]=[];
  // Revalidate destination and source before every explicit batch. No timer replays mutations.
  const destination=await api.get<unknown>(`/api/study-plans/${createdPlanId}/workflow`);if(!isWorkflow(destination)||destination.read_only)throw new ApiError(409);
  const sourceResult=await api.get<unknown>(`/api/study-plans/${createdPlanId}/source`);if(!record(sourceResult)||!(sourceResult.source===null||isSourceDocument(sourceResult.source)))throw responseError();
  if(outlineSource&&(!sourceResult.source||sourceResult.source.document_id!==outlineSource.document_id))throw new ApiError(409);
  for(let phase=0;phase<frozen.units.length;phase++)for(const lesson of frozen.units[phase]!.lessons){
   if(!lesson.selected||stop.current||!current())continue;
   const taskForm={...config,mode:'package' as const,topic:lesson.title,objectives:lesson.learning_objectives.join('\n'),planId:String(createdPlanId),phase,autoSave:true};
   const request=generationRequest(taskForm,sourceResult.source);
   const result=await api.post<unknown>(request.path,request.body);if(!isPackageFor(result,taskForm))throw responseError(true);
   if(!current())throw new ApiError(0,'stale',true,'uncertain');results.push(result);setPackages(previous=>[...previous,{id:++serial.current,value:result,planId:createdPlanId}]);
  }
  return results;
 },async results=>{if(!current())return;setNotice(t(stop.current?'batchStopped':results.some(result=>!result.success)?'partial':'generationDone'));await invalidate(['authoring']);await invalidate(['courses']);});
 const recover=useOperation(async(candidate:GenerationDraft)=>{
  const ids=new Set([positiveId(candidate.form.planId),candidate.createdPlanId,candidate.outlineSourcePlanId].filter((id):id is number=>!!id));
  for(const id of ids){const result=await api.get<unknown>(`/api/study-plans/${id}/tree`);if(!isCourseTree(result)||result.id!==id||(user?.role!=='admin'&&result.creator_id!==user?.id))throw responseError();}
  let copied=false;
  if(candidate.createdPlanId&&candidate.outlineSource){const result=await api.get<unknown>(`/api/study-plans/${candidate.createdPlanId}/source`);if(!record(result)||!(result.source===null||isSourceDocument(result.source)))throw responseError();copied=result.source?.document_id===candidate.outlineSource.document_id;}
  if(candidate.recoveredSource && candidate.createdPlanId){const result=await api.get<unknown>(`/api/study-plans/${candidate.createdPlanId}/source`);if(!record(result)||!(result.source===null||isSourceDocument(result.source)))throw responseError();if(result.source?.extracted_text===candidate.recoveredSource.extracted_text){candidate={...candidate,recoveredSource:null,outlineSource:result.source,outlineSourcePlanId:candidate.createdPlanId};copied=true;}}
  return {candidate,copied};
 },({candidate,copied})=>{if(!current())return;form.reset(candidate.form);setOutline(candidate.outline);setOutlineSource(candidate.outlineSource||null);setOutlineSourcePlanId(candidate.outlineSourcePlanId||null);setSourceCopied(copied);setRecoveredSource(candidate.recoveredSource||null);setCreatedPlanId(candidate.createdPlanId);setRecovery(null);setHasRestored(true);setNotice(t('restored'));setLocalState(drafts?.write('course','generation','active',candidate)?'localSaved':'localFailed');});
 useEffect(()=>()=>{controller.current?.abort();stop.current=true;},[]);
 const localChanged=hasRestored||form.formState.isDirty||!!outline||!!createdPlanId;
 useEffect(()=>{if(recovery||!localChanged||status!=='authenticated')return;const timer=window.setTimeout(()=>{if(current())setLocalState(drafts?.write('course','generation','active',{form:values,outline,createdPlanId,outlineSource,outlineSourcePlanId,recoveredSource})?'localSaved':'localFailed');},400);return()=>window.clearTimeout(timer);},[values,outline,createdPlanId,outlineSource,outlineSourcePlanId,recoveredSource,recovery,localChanged,status,drafts,current]);
 const recoveredTarget=createdPlanId||planId;
 const checkRecoveredSource=useOperation(async()=>{if(!recoveredTarget||!recoveredSource)throw validationError();const result=await api.get<unknown>(`/api/study-plans/${recoveredTarget}/source`);if(!record(result)||!(result.source===null||isSourceDocument(result.source)))throw responseError();return result.source;},result=>{if(!current())return;setDestinationSource(result);setDecision('recovered-source');});
 const saveRecoveredSource=useOperation(async()=>{
  if(!recoveredTarget||!recoveredSource||destinationSource===undefined)throw validationError();
  const destination=await api.get<unknown>(`/api/study-plans/${recoveredTarget}/tree`);if(!isCourseTree(destination)||destination.id!==recoveredTarget||(user?.role!=='admin'&&destination.creator_id!==user?.id))throw responseError();
  const state=await api.get<unknown>(`/api/study-plans/${recoveredTarget}/workflow`);if(!isWorkflow(state)||state.read_only)throw new ApiError(409);
  const latest=await api.get<unknown>(`/api/study-plans/${recoveredTarget}/source`);if(!record(latest)||!(latest.source===null||isSourceDocument(latest.source)))throw responseError();
  if((latest.source?.metadata_revision||latest.source?.document_id||null)!==(destinationSource?.metadata_revision||destinationSource?.document_id||null))throw new ApiError(409);
  if(!current())throw new ApiError(0,'stale',false,'cancelled');
  const result=await api.put<unknown>(`/api/study-plans/${recoveredTarget}/source`,recoveredSource);if(!isSourceReceipt(result,recoveredSource.extracted_text))throw responseError(true);return result.source;
 },async result=>{if(!current())return;setRecoveredSource(null);setOutlineSource(result);setOutlineSourcePlanId(recoveredTarget);setSourceCopied(true);setNotice(t('sourceSaved'));await invalidate(['authoring','source',recoveredTarget]);await invalidate(['courses']);});
 const busy=checkRecoveredSource.isPending||saveRecoveredSource.isPending||generate.isPending||saveOutline.isPending||batch.isPending||recover.isPending||copySource.isPending||checkSource.isPending;
 useDirtyGuard(form.formState.isDirty||Object.values(previewDirty).some(Boolean)||!!outlineProposal||!!outline&&!createdPlanId||busy);
 const persist=()=>{const value:GenerationDraft={form:form.getValues(),outline,createdPlanId,outlineSource,outlineSourcePlanId,recoveredSource};setLocalState(drafts?.write('course','generation','active',value)?'localSaved':'localFailed');};
 const run=(value:GenerationForm)=>{
  try{
   if(recoveredSource||!sourceReady||(value.autoSave&&value.mode==='package'&&(!isCourseTree(tree.data)||tree.data.id!==planId||!isWorkflow(workflow.data)||workflow.data.read_only||value.phase>=Math.max(1,tree.data.phases.length))))throw validationError();
   const input={form:structuredClone(value),request:generationRequest(value,savedSource),source:savedSource?structuredClone(savedSource):null};setLast(input);setNotice('');setLocalState(drafts?.write('course','generation','active',{form:value,outline,createdPlanId,outlineSource,outlineSourcePlanId,recoveredSource})?'localSaved':'localFailed');generate.mutate(input);
  }catch{setNotice(t('invalidConfiguration'));}
 };
 const sourceErrors=tree.error||workflow.error||source.error;
 const phases=isCourseTree(tree.data)?tree.data.phases:[];
 const frozenOutline=!!createdPlanId;
 return <div className="stack"><PageHeader title={t('generate')} description={t('aiHint')} actions={<Link to="/materiales">{t('library')}</Link>}/>
 {legacyDraft&&<Card><div className="stack"><h2>{t('legacyDesignerTitle')}</h2><p>{t('legacyDesignerHint')}</p>{!legacySetup&&<p role="alert">{t('legacyDesignerUnsupported')}</p>}{legacyReadable&&<details><summary>{t('legacyDesignerSnapshot')}</summary><Field label={t('legacyDesignerSnapshot')}><Textarea readOnly rows={8} value={JSON.stringify(legacyDraft,null,2)}/></Field></details>}{!legacyReadable&&<ErrorState error={legacyCourse.error||(!legacyPlan||!legacyCourse.isPending?responseError():null)} retry={()=>{if(legacyPlan)void legacyCourse.refetch();}}/>}<div className="cluster"><Button disabled={busy||!!recovery||localChanged||!legacySetup||!legacyReadable} busy={recover.isPending} onClick={()=>{if(legacySetup)recover.mutate(legacySetup);}}>{t('legacyDesignerRestore')}</Button><Button variant="secondary" disabled={busy} onClick={()=>{if(drafts?.remove('course','designer','active'))setLegacyDraft(null);else setLocalState('localRemoveFailed');}}>{t('legacyDesignerDiscard')}</Button></div><ErrorState error={recover.error}/></div></Card>}
 {recovery&&<Card><div className="stack"><h2>{t('recoverTitle')}</h2><p>{t('recoverDescription')}</p><div className="cluster"><Button busy={recover.isPending} disabled={busy} onClick={()=>recover.mutate(recovery)}>{t('restore')}</Button><Button variant="secondary" disabled={busy} onClick={()=>{if(drafts?.remove('course','generation','active')){setRecovery(null);setLocalState('');}else setLocalState('localRemoveFailed');}}>{t('discardLocal')}</Button></div>{recover.error&&<ErrorState error={recover.error}/>}</div></Card>}
 {recoveredSource&&<Card><div className="stack"><h2>{t('recoveredSourceTitle')}</h2><p>{t('recoveredSourceHint')}</p><Field label={t('sourceText')}><Textarea readOnly rows={8} value={recoveredSource.extracted_text}/></Field>{recoveredTarget?<Button variant="secondary" disabled={busy} onClick={()=>checkRecoveredSource.mutate(undefined)}>{t('saveRecoveredSource',{id:recoveredTarget})}</Button>:<Link to="/cursos/nuevo">{t('createCourse')}</Link>}<ErrorState error={checkRecoveredSource.error||saveRecoveredSource.error}/></div></Card>}
 <form className="stack" onSubmit={form.handleSubmit(run)}><fieldset disabled={!!recovery}><div className="stack"><div className="form-grid"><Field label={t('mode')}><Select {...form.register('mode')}><option value="lesson">{t('singleLesson')}</option><option value="exercise">{t('singleExercise')}</option><option value="plan">{t('studyPlan')}</option><option value="outline">{t('courseOutline')}</option><option value="package">{t('topicPackage')}</option></Select></Field><Field label={t('subject')} error={form.formState.errors.subject?.message}><Input {...form.register('subject',{required:t('required')})}/></Field><Field label={t('grade')} error={form.formState.errors.grade?.message}><Input {...form.register('grade',{required:t('required')})}/></Field></div>
 {!['plan','outline'].includes(values.mode)&&<Field label={t('topic')}><Input {...form.register('topic')}/></Field>}<Field label={t('objectives')}><Textarea {...form.register('objectives')}/></Field>
 {['plan','outline'].includes(values.mode)&&<Field label={t('weeks')}><Input type="number" min={1} max={104} {...form.register('weeks',{valueAsNumber:true,min:1,max:104})}/></Field>}
 {values.mode==='lesson'&&<Field label={t('minutes')}><Input type="number" min={1} max={240} {...form.register('minutes',{valueAsNumber:true,min:1,max:240})}/></Field>}
 {(values.mode==='exercise'||values.mode==='package')&&<Field label={t('generationDifficulty')}><Select {...form.register('difficulty')}>{['easy','medium','hard'].map(level=><option key={level} value={level}>{t(level)}</option>)}</Select></Field>}
 {values.mode==='exercise'&&<Field label={t('exerciseType')}><Select {...form.register('exerciseType')}>{['multiple_choice','true_false','short_answer'].map(kind=><option key={kind} value={kind}>{t(kind)}</option>)}</Select></Field>}
 <fieldset disabled={checkRecoveredSource.isPending||saveRecoveredSource.isPending}><CourseChoice value={values.planId} onChange={value=>{form.setValue('planId',value,{shouldDirty:true});form.setValue('phase',0,{shouldDirty:true});}}/></fieldset>
 {planId&&<div className="stack"><Link to={`/fuentes?plan_id=${planId}`}>{t('editSource')}</Link>{sourceErrors?<ErrorState error={sourceErrors}/>:!sourceReady?<p>{t('loadingSource')}</p>:savedSource?<p>{t('usingSource',{filename:savedSource.filename})}</p>:<p>{t('noSource')}</p>}{isWorkflow(workflow.data)&&workflow.data.read_only&&<p>{t('revisionHint')}</p>}</div>}
 {values.mode==='plan'&&<p>{t('planNoSource')}</p>}
 {(values.mode==='package'||!!outline)&&<Card><div className="stack"><fieldset><legend>{t('includeItems')}</legend><div className="cluster"><label><input type="checkbox" {...form.register('lesson')}/> {t('lesson')}</label><label><input type="checkbox" {...form.register('exercises')}/> {t('exercise')}</label><label><input type="checkbox" {...form.register('assessment')}/> {t('assessment')}</label></div></fieldset><div className="form-grid">{values.exercises&&<Field label={t('exerciseCount')}><Input type="number" min={0} max={12} {...form.register('exerciseCount',{valueAsNumber:true,min:0,max:12})}/></Field>}{values.assessment&&<><Field label={t('questionCount')}><Input type="number" min={1} max={20} {...form.register('questionCount',{valueAsNumber:true,min:1,max:20})}/></Field><Field label={t('questionTypes')}><Select {...form.register('questionType')}>{['mixed','multiple_choice','true_false','short_answer','long_answer','fill_in_blank'].map(kind=><option key={kind} value={kind}>{t(kind)}</option>)}</Select></Field></>}</div>{values.mode==='package'&&<label><input type="checkbox" {...form.register('autoSave')}/> {t('saveEachItem')}</label>}{values.mode==='package'&&values.autoSave&&planId&&isCourseTree(tree.data)&&<Field label={t('phase')}><Select {...form.register('phase',{valueAsNumber:true})}>{(phases.length?phases:[{}]).map((phase,index)=><option key={index} value={index}>{phase.name||phase.title||t('phaseNumber',{number:index+1})}</option>)}</Select></Field>}<p>{t(values.mode!=='package'||values.autoSave?'autoSaveHint':'previewOnly')}</p></div></Card>}
 </div></fieldset><div className="cluster"><Button type="submit" busy={generate.isPending} disabled={busy||!!recovery||!!recoveredSource||!sourceReady}>{t('generate')}</Button><Button type="button" variant="secondary" disabled={busy||!!recovery} onClick={persist}>{t('saveLocal')}</Button>{generate.isPending&&<Button type="button" variant="secondary" onClick={()=>{controller.current?.abort();setNotice(t('deliveryStopped'));}}>{t('stopDelivery')}</Button>}</div></form>
 {localState&&<p role="status">{t(localState)}</p>}{notice&&<p role="status">{notice}</p>}{generate.error&&<ErrorState error={generate.error}/>}{last&&!busy&&(generate.error||packages.at(-1)?.value.success===false)&&<Button variant="secondary" onClick={()=>setDecision('retry')}>{t('retrySame')}</Button>}
 {outlineProposal&&<Card><div className="stack"><h2>{t('outlineProposal')}</h2><h3>{outlineProposal.outline.title}</h3><ul>{outlineProposal.outline.units.map((unit,index)=><li key={index}>{unit.title} ({unit.lessons.length})</li>)}</ul><Button disabled={busy} onClick={()=>setDecision('outline')}>{t('useOutline')}</Button><Button variant="secondary" onClick={()=>setOutlineProposal(null)}>{t('discardProposal')}</Button></div></Card>}
 {outline&&<section className="stack"><h2>{t('editableOutline')}</h2><fieldset disabled={busy||frozenOutline}><div className="stack"><Field label={t('courseTitle')}><Input value={outline.title} maxLength={200} onChange={event=>setOutline({...outline,title:event.target.value})}/></Field><Field label={t('description')}><Textarea value={outline.description} onChange={event=>setOutline({...outline,description:event.target.value})}/></Field>{outline.units.map((unit,index)=><Card key={index}><div className="stack"><Field label={t('unitTitle',{number:index+1})}><Input value={unit.title} onChange={event=>setOutline({...outline,units:outline.units.map((entry,i)=>i===index?{...entry,title:event.target.value}:entry)})}/></Field>{unit.lessons.map((lesson,lessonIndex)=><div className="stack" key={lessonIndex}><label className="cluster"><input type="checkbox" checked={lesson.selected} onChange={event=>setOutline({...outline,units:outline.units.map((entry,i)=>i===index?{...entry,lessons:entry.lessons.map((item,j)=>j===lessonIndex?{...item,selected:event.target.checked}:item)}:entry)})}/>{t('includeTopic')}</label><Field label={t('topicTitle',{number:lessonIndex+1})}><Input value={lesson.title} onChange={event=>setOutline({...outline,units:outline.units.map((entry,i)=>i===index?{...entry,lessons:entry.lessons.map((item,j)=>j===lessonIndex?{...item,title:event.target.value}:item)}:entry)})}/></Field></div>)}<Button variant="secondary" onClick={()=>setOutline({...outline,units:outline.units.map((entry,i)=>i===index?{...entry,lessons:[...entry.lessons,{title:'',learning_objectives:[],selected:true}]}:entry)})}>{t('addTopic')}</Button></div></Card>)}<Button variant="secondary" disabled={outline.units.length>=101} onClick={()=>setOutline({...outline,units:[...outline.units,{title:'',lessons:[]}]})}>{t('addUnit')}</Button></div></fieldset>
 {!createdPlanId?<Button disabled={busy||(saveOutline.error instanceof ApiError&&saveOutline.error.uncertain)} busy={saveOutline.isPending} onClick={()=>saveOutline.mutate(undefined)}>{t('saveOutline')}</Button>:<Card><div className="stack"><p>{t('outlineSaved')}</p><div className="cluster"><Link to={`/cursos/${createdPlanId}/editar`}>{t('courseWorkflow')}</Link><Link to={`/fuentes?plan_id=${createdPlanId}`}>{t('editSource')}</Link></div>{outlineSource&&!sourceCopied&&<div className="stack"><p>{t('copySourceHint',{filename:outlineSource.filename})}</p><Button variant="secondary" disabled={busy} onClick={()=>checkSource.mutate(undefined)}>{t('copyOutlineSource')}</Button>{copySource.error&&<ErrorState error={copySource.error}/>}<ErrorState error={checkSource.error}/></div>}<p>{t('batchHint')}</p><Button busy={batch.isPending} disabled={busy||!!recoveredSource||!!outlineSource&&!sourceCopied||!outline.units.some(unit=>unit.lessons.some(lesson=>lesson.selected))} onClick={()=>batch.mutate(undefined)}>{t('generateSelected')}</Button>{batch.isPending&&<Button variant="secondary" onClick={()=>{stop.current=true;setNotice(t('batchStopRequested'));}}>{t('stopAfterItem')}</Button>}</div></Card>}{saveOutline.error&&<ErrorState error={saveOutline.error}/>} {batch.error&&<ErrorState error={batch.error}/>}</section>}
 {packages.map(item=><Card key={item.id}><div className="stack"><h2>{item.value.topic_name}</h2>{item.planId&&<Link to={`/cursos/${item.planId}`}>{t('savedInCourse',{id:item.planId})}</Link>}<Badge>{t(item.value.success?'generationDone':'partial')}</Badge><p>{t('savedCount',{saved:item.value.saved_content_ids.length,total:item.value.items.length})}</p><GenerationItems items={item.value.items}/></div></Card>)}
 {previews.map(preview=><section className="stack" key={preview.id}><h2>{t('proposalNumber',{number:preview.id})}</h2><p>{t('proposalHint')}</p>{preview.sourceName&&<p>{t('proposalSource',{filename:preview.sourceName})}</p>}<PreviewEditor preview={preview} onDirty={onDirty} onSaved={onSaved}/></section>)}
 {assessmentPreviews.map(preview=><section className="stack" key={preview.id}><h2>{t('assessmentProposal')}</h2><p>{t('proposalHint')}</p><AssessmentPreviewEditor preview={preview} onDirty={onDirty} onSaved={onSaved}/></section>)}
 {(createdPlanId||planId)&&<GenerationJobs key={createdPlanId||planId} planId={(createdPlanId||planId)!} running={(generate.isPending||batch.isPending)&&status==='authenticated'}/>}
 <ConfirmDialog open={decision!==null} onOpenChange={open=>{if(!open)setDecision(null);}} title={t(decision==='outline'?'useOutline':decision==='recovered-source'?'saveRecoveredSource':decision==='source'?'copyOutlineSource':'retrySame',{id:recoveredTarget})} description={t(decision==='outline'?'replaceOutlineDescription':(decision==='source'||decision==='recovered-source')?'replaceSourceDescription':'retryDescription')} confirmLabel={t(decision==='outline'?'useOutline':decision==='recovered-source'?'saveRecoveredSource':decision==='source'?'copyOutlineSource':'retrySame',{id:recoveredTarget})} onConfirm={()=>{if(decision==='outline'&&outlineProposal){setOutline(outlineProposal.outline);setOutlineSource(outlineProposal.source);setOutlineSourcePlanId(outlineProposal.sourcePlanId);setSourceCopied(false);setOutlineProposal(null);setCreatedPlanId(null);}else if(decision==='source'&&!busy)copySource.mutate(undefined);else if(decision==='recovered-source'&&!busy)saveRecoveredSource.mutate(undefined);else if(last&&!busy)generate.mutate(last);setDecision(null);}}>{decision==='recovered-source'&&<p>{t('saveRecoveredSource',{id:recoveredTarget})}: {recoveredSource?.filename}</p>}{decision==='source'&&<p>{destinationSource?t('replaceCapturedSource',{previous:destinationSource.filename,next:outlineSource?.filename,id:createdPlanId}):t('copyCapturedSource',{filename:outlineSource?.filename,id:createdPlanId})}</p>}</ConfirmDialog>
 </div>;
}
