export const locales = {
 en: {
  title:'Welcome, {{name}}',intro_student:'Continue studying or return to an assessment.',intro_teacher:'See what needs your attention, then continue teaching.',intro_admin:'Manage people, application status and installation backups.',
  continueCourse:'Continue course',resumeAssessment:'Resume assessment',attemptHint:'These are existing attempts. Home never starts an attempt; timed attempts keep their original deadline.',attemptIdentity:'Assessment #{{assessment}} · Attempt #{{attempt}}',resumeNamed:'Resume {{title}}',noAttempt:'No open assessments',browseAssessments:'Browse assessments',studySupport:'Your study space',supportHint:'Assigned material stays available when your teacher is away. Help replies may take time.',allCourses:'All my courses',help:'Tutor and questions',progress:'My progress',continueMaterial:'Continue material',materialIdentity:'Material #{{id}}',sessionIdentity:'Session #{{id}}',resumeMaterial:'Resume this session',chooseCourse:'Course to continue',noCourse:'No courses available',noCourseHint:'Your teacher can assign a course. You can still open Tutor and questions.',completed:'{{count}} of {{total}} items completed',continueNamed:'Continue: {{title}}',courseCompleted:'All course items are completed. Reopen the course to review.',courseEmpty:'This course has no material yet.',openCourse:'Open course',progressChanged:'Course structure and recorded progress differ. Open the course to review.',
  grading:'Corrections',gradingScope:'Pending work on assessments you can manage, including historical assignments. AI-suggested scores remain provisional.',waitingCount:'{{count}} submissions need review',noGrading:'No submissions waiting for correction',openGrading:'Open correction queue',helpRequests:'Help requests',openRequests:'{{count}} open requests',requestIdentity:'Request #{{id}}',studentIdentity:'Student #{{id}}',priority:'Priority {{value}} of 5',noRequests:'No open help requests',openHelp:'Open help queue',teaching:'Teaching',courses:'Courses and materials',students:'My students',createStudent:'Create student',messages:'Messages',participation:'Participation feedback',
  people:'People',peopleHint:'Manage students, teachers and administrators, including active and inactive accounts.',managePeople:'Manage people',createPerson:'Create account',status:'Application status',serverVersion:'Application server responded · Version {{version}}',statusHint:'AI providers and the browser connection have separate checks.',openStatus:'View status and guidance',backups:'Private backups',backupHint:'Review scope and handling instructions before downloading an installation backup.',openBackups:'Open backup tools',
 },
 es: {
  title:'Hola, {{name}}',intro_student:'Continúa estudiando o vuelve a una evaluación.',intro_teacher:'Consulta lo que necesita tu atención y continúa enseñando.',intro_admin:'Gestiona personas, estado de la aplicación y copias de la instalación.',
  continueCourse:'Continuar curso',resumeAssessment:'Reanudar evaluación',attemptHint:'Son intentos existentes. Inicio nunca inicia un intento; los intentos con tiempo mantienen su plazo original.',attemptIdentity:'Evaluación #{{assessment}} · Intento #{{attempt}}',resumeNamed:'Reanudar {{title}}',noAttempt:'No hay evaluaciones abiertas',browseAssessments:'Ver evaluaciones',studySupport:'Tu espacio de estudio',supportHint:'El material asignado sigue disponible cuando tu docente está ausente. Las respuestas de ayuda pueden tardar.',allCourses:'Todos mis cursos',help:'Tutor y preguntas',progress:'Mi progreso',continueMaterial:'Continuar material',materialIdentity:'Material #{{id}}',sessionIdentity:'Sesión #{{id}}',resumeMaterial:'Reanudar esta sesión',chooseCourse:'Curso para continuar',noCourse:'No hay cursos disponibles',noCourseHint:'Tu docente puede asignarte un curso. Mientras tanto, puedes abrir Tutor y preguntas.',completed:'{{count}} de {{total}} elementos completados',continueNamed:'Continuar: {{title}}',courseCompleted:'Todos los elementos están completados. Abre el curso para repasar.',courseEmpty:'Este curso aún no tiene material.',openCourse:'Abrir curso',progressChanged:'La estructura del curso y el progreso registrado difieren. Abre el curso para revisarlo.',
  grading:'Correcciones',gradingScope:'Trabajo pendiente en evaluaciones que puedes gestionar, incluidas asignaciones históricas. Las notas sugeridas por IA siguen siendo provisionales.',waitingCount:'{{count}} entregas necesitan revisión',noGrading:'No hay entregas pendientes de corrección',openGrading:'Abrir cola de correcciones',helpRequests:'Solicitudes de ayuda',openRequests:'{{count}} solicitudes abiertas',requestIdentity:'Solicitud #{{id}}',studentIdentity:'Estudiante #{{id}}',priority:'Prioridad {{value}} de 5',noRequests:'No hay solicitudes de ayuda abiertas',openHelp:'Abrir cola de ayuda',teaching:'Docencia',courses:'Cursos y materiales',students:'Mis estudiantes',createStudent:'Crear estudiante',messages:'Mensajes',participation:'Datos de participación',
  people:'Personas',peopleHint:'Gestiona estudiantes, docentes y administradores, con cuentas activas e inactivas.',managePeople:'Gestionar personas',createPerson:'Crear cuenta',status:'Estado de la aplicación',serverVersion:'El servidor de la aplicación ha respondido · Versión {{version}}',statusHint:'Los proveedores de IA y la conexión del navegador tienen comprobaciones independientes.',openStatus:'Ver estado e instrucciones',backups:'Copias privadas',backupHint:'Revisa el alcance y el manejo antes de descargar una copia de la instalación.',openBackups:'Abrir herramientas de copia',
 },
};
